#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, extname, join, relative, resolve } from 'node:path'
import { buildTraceability } from './traceability.mjs'
import { currentBackendSurfaces, extensionSurfaceMatrix, matrixFamilies } from './surfaces.mjs'

const root = resolve(import.meta.dirname, '../..')
const check = process.argv.includes('--check')
const bootstrapIdentities = process.argv.includes('--bootstrap-identities')
const outputs = new Map()
const identitiesPath = 'docs/extensions/v3/catalog-identities.json'

function read(path) {
  return readFileSync(resolve(root, path), 'utf8')
}

function walk(path, suffix) {
  const absolute = resolve(root, path)
  const result = []
  for (const name of readdirSync(absolute)) {
    const child = join(absolute, name)
    if (statSync(child).isDirectory()) result.push(...walk(relative(root, child), suffix))
    else if (!suffix || child.endsWith(suffix)) result.push(relative(root, child))
  }
  return result.sort()
}

function put(path, content) {
  outputs.set(path, content.endsWith('\n') ? content : `${content}\n`)
}

function json(path, value) {
  put(path, `${JSON.stringify(value, null, 2)}\n`)
}

function cell(value) {
  return String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function parseAuthoritativeRows() {
  const source = read('knowledge/decisions/2026-07-13-trusted-plugin-theme-platform-v3.md')
  const sections = [
    ['theme', '### Template And Theme Mechanism Comparison', '### Plugin Mechanism Comparison'],
    ['plugin', '### Plugin Mechanism Comparison', '## Architecture Mind Map']
  ]
  const rows = []
  for (const [family, startMarker, endMarker] of sections) {
    const start = source.indexOf(startMarker)
    const end = source.indexOf(endMarker, start + startMarker.length)
    if (start < 0 || end < 0) throw new Error(`cannot find ADR table: ${family}`)
    const lines = source.slice(start, end).split('\n').filter(line => line.startsWith('| '))
    for (const line of lines.slice(2)) {
      const columns = line.split('|').slice(1, -1).map(item => item.trim())
      if (columns.length !== 3) throw new Error(`invalid ${family} table row: ${line}`)
      rows.push({ family, surface: columns[0], current: columns[1], target: columns[2] })
    }
  }
  if (rows.length !== 99) throw new Error(`ADR must contain 99 authoritative rows, found ${rows.length}`)
  return rows
}

function renderTraceability(rows) {
  const lines = [
    '# Trusted Plugin And Theme Platform V3 Traceability Matrix',
    '',
    '<!-- Generated by scripts/v3-catalog/generate.mjs. Do not edit by hand. -->',
    '',
    'This matrix maps all 27 theme rows and 72 plugin rows from the accepted V3 ADR.',
    'A row remains incomplete until its named test exists and the phase exit gate passes.',
    '',
    '| # | Family | Surface | Current | V3 target | Phase | Contract | Test ID | Rollback |',
    '| ---: | --- | --- | --- | --- | --- | --- | --- | --- |'
  ]
  for (const row of rows) {
    lines.push(`| ${row.row} | ${cell(row.family)} | ${cell(row.surface)} | ${cell(row.current)} | ${cell(row.target)} | ${row.phase} | ${cell(row.contract)} | \`${row.test}\` | ${cell(row.rollback)} |`)
  }
  lines.push('')
  return lines.join('\n')
}

function normalizePath(...parts) {
  const value = parts.join('/').replaceAll(/\/+/g, '/')
  return value === '/' ? value : value.replace(/\/$/, '')
}

function snake(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
}

function routePolicy(route) {
  const { handler, method, module, path } = route
  if (path === '/api/v1/health' || path === '/api/v1/ready') return ['public', 'host liveness/readiness; non-overridable recovery prerequisite']
  if (path === '/api/v1/extensions/:extensionId/*') return ['declared', 'enabled plugin route declaration and manifest access policy']
  if (path.startsWith('/api/v1/admin/extensions/') && /frontend\/(confirmation|trust)$/.test(path)) return ['super_admin', 'active super_admin plus exact frontend artifact confirmation']
  if (path.startsWith('/api/v1/admin/extensions')) return ['permission', method === 'GET' ? 'extension.view or matching manage permission' : 'extension.plugin.manage or extension.theme.manage; operation-specific service policy']
  if (path.startsWith('/api/v1/admin/pages')) return ['permission', 'extension.view for inspection; theme/plugin manage and super_admin approval where required']
  if (path.startsWith('/api/v1/admin/attachment-settings')) return ['permission', 'attachment.settings.manage']
  if (path.startsWith('/api/v1/admin/attachments')) return ['permission', 'attachment.manage']
  if (path.startsWith('/api/v1/admin/database')) return ['permission', 'database.manage']
  if (path.startsWith('/api/v1/admin/entity-meta')) return ['permission', 'entity_meta.manage or settings.manage']
  if (path.startsWith('/api/v1/admin/forum/search')) return ['permission', 'search.manage']
  if (path.startsWith('/api/v1/admin/forum/categories') || path.startsWith('/api/v1/admin/forum/category-groups')) return ['permission', 'category.manage']
  if (path.startsWith('/api/v1/admin/forum/tags')) return ['permission', 'tag.manage']
  if (path.startsWith('/api/v1/admin/forum/settings')) return ['permission', 'category.manage, tag.manage, or forum.settings.manage; field owner recheck']
  if (path.startsWith('/api/v1/admin/jobs')) return ['permission', method === 'GET' ? 'jobs.view' : 'jobs.manage']
  if (path.startsWith('/api/v1/admin/mail')) return ['permission', 'settings.mail.manage or settings.manage compatibility policy']
  if (path.startsWith('/api/v1/admin/moderation')) return ['permission', 'moderation.manage']
  if (path.startsWith('/api/v1/moderation/workbench')) return ['permission', 'moderation.review; moderation.view_ip controls sensitive fields']
  if (path.startsWith('/api/v1/admin/notifications')) return ['permission', 'settings.manage']
  if (path.startsWith('/api/v1/admin/seo')) return ['permission', 'seo.manage']
  if (path.startsWith('/api/v1/admin/site')) return ['permission', 'settings.site.manage']
  if (path.startsWith('/api/v1/admin/webhooks')) return ['permission', 'settings.manage or settings.site.manage']
  if (path.startsWith('/api/v1/admin/features')) return ['permission', 'settings.site.manage']
  if (path.startsWith('/api/v1/admin/web-options')) return ['permission', 'option-owner permission dispatch']
  if (path === '/api/v1/admin/overview') return ['permission', 'admin.access']
  if (/^\/api\/v1\/(permissions|roles|users)(\/|$)/.test(path)) return ['permission', 'identity service route-specific user.view/user.manage/role.manage/user.ban policy']
  if (path.startsWith('/api/v1/auth/sessions') || path.startsWith('/api/v1/auth/tokens')) return ['login', 'current active actor; token/session ownership']
  if (path === '/api/v1/auth/logout' || path === '/api/v1/auth/session') return ['login', 'current browser session']
  if (/^\/api\/v1\/auth\/(registration-status|register|login|password-reset)/.test(path)) return ['public', 'identity bootstrap, risk, rate-limit, and human-verification policy']
  if (path === '/api/v1/human-verification/challenge') return ['public', 'purpose allowlist and Redis rate/replay policy']
  if (path.startsWith('/api/v1/profile') && !path.startsWith('/api/v1/profiles')) return ['login', 'current active actor; attachment.upload for avatar upload']
  if (path.startsWith('/api/v1/notifications')) return ['login', 'current recipient ownership']
  if (path === '/api/v1/moderation/reports') return ['login', 'active actor and report deduplication policy']
  if (path === '/api/v1/me/content-review') return ['login', 'current active author ownership']
  if (path.startsWith('/api/v1/entity-meta/') && method !== 'GET') return ['permission', 'entity ownership plus field definition write policy']
  if (path.startsWith('/api/v1/entity-meta/')) return ['contextual', 'public definition visibility or actor/resource read policy']
  if (path === '/api/v1/attachments' && method === 'POST') return ['permission', 'attachment.upload plus upload/media policy']
  if (path.startsWith('/api/v1/attachments/')) return ['contextual', 'attachment visibility and referenced resource read policy']
  if (path === '/api/v1/topics' && method === 'POST') return ['permission', 'topic.create plus forum publication policy']
  if (/\/topics\/:topicID\/(hide|restore)$/.test(path)) return ['permission', 'topic.delete_any plus state policy']
  if (/\/topics\/:topicID\/(lock|unlock)$/.test(path)) return ['permission', 'topic.lock or allowed author close policy']
  if (/\/topics\/:topicID\/(pin|unpin)$/.test(path)) return ['permission', 'topic.pin']
  if (path === '/api/v1/topics/:topicID' && method === 'PATCH') return ['permission', 'topic.edit_own or topic.edit_any']
  if (path === '/api/v1/topics/:topicID' && method === 'DELETE') return ['permission', 'topic.delete_own or topic.delete_any']
  if (path.endsWith('/comments') && method === 'POST') return ['permission', 'post.create plus topic/publication policy']
  if (path.startsWith('/api/v1/comments/') && method !== 'GET') return ['permission', 'post edit/delete own or any policy']
  if (path === '/api/v1/web-options' && method === 'PUT') return ['permission', 'option-owner permission dispatch']
  if (path.startsWith('/api/v1/webhooks/inbound')) return ['public', 'source-specific signature/idempotency policy']
  if (path.startsWith('/api/v1/pages/resolve')) return ['contextual', 'resolved Page Registry access enum; loader receives no raw session authority']
  if (path.startsWith('/api/v1/site/theme-assets')) return ['public', 'active package containment, digest, MIME, and path policy']
  if (path.startsWith('/api/v1/site/') || path.startsWith('/api/v1/web-options') || path.startsWith('/api/v1/profiles/')) return ['public', 'public read contract']
  if (method === 'GET') return ['public', `${module} public read policy; visibility rechecked by service`]
  return ['service-policy', `${module}.${handler} authoritative actor/action/resource policy`]
}

function discoverRoutes() {
  const files = walk('apps/api/app/Http/Controllers', '.go').filter(path => !path.endsWith('_test.go'))
  const routes = []
  for (const source of files) {
    const content = read(source)
    if (!content.includes('RegisterRoutes')) continue
    const module = snake(source.split('/').at(-2))
    const routers = new Map([['api', '']])
    const lines = content.split('\n')
    for (let index = 0; index < lines.length; index++) {
      const line = lines[index]
      const group = line.match(/(\w+)\s*:=\s*(\w+)\.Group\("([^"]*)"\)/)
      if (group && routers.has(group[2])) routers.set(group[1], normalizePath(routers.get(group[2]), group[3]))
      for (const match of line.matchAll(/(\w+)\.(Get|Post|Put|Patch|Delete|All)\("([^"]*)"\s*,([^)]*)\)/g)) {
        if (!routers.has(match[1])) continue
        const handlerMatch = [...match[4].matchAll(/h\.([A-Za-z0-9_]+)/g)].at(-1)
        if (!handlerMatch) continue
        const path = normalizePath('/api/v1', routers.get(match[1]), match[3])
        const method = match[2] === 'All' ? '*' : match[2].toUpperCase()
        routes.push({ module, handler: handlerMatch[1], method, path, source: `${source}:${index + 1}` })
      }
    }
  }
  routes.push(
    { module: 'system', handler: 'health', method: 'GET', path: '/api/v1/health', source: 'apps/api/app/Http/server.go:169' },
    { module: 'system', handler: 'ready', method: 'GET', path: '/api/v1/ready', source: 'apps/api/app/Http/server.go:182' }
  )
  const unique = new Map()
  for (const route of routes) unique.set(`${route.method} ${route.path} ${route.handler}`, route)
  const items = [...unique.values()].sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
  const idCount = new Map()
  for (const item of items) idCount.set(`${item.module}.${snake(item.handler)}`, (idCount.get(`${item.module}.${snake(item.handler)}`) || 0) + 1)
  return items.map(item => {
    const base = `${item.module}.${snake(item.handler)}`
    const suffix = idCount.get(base) > 1 ? `.${item.method.toLowerCase().replace('*', 'all')}` : ''
    const [access, policy] = routePolicy(item)
    return {
      id: `core.route.${base}${suffix}`,
      contractVersion: `sforum.route.${base}@1`,
      ...item,
      access,
      policy
    }
  })
}

function routeFromPage(source) {
  const parts = source.replace('apps/web/app/pages/', '').replace(/\.vue$/, '').split('/')
  if (parts.at(-1) === 'index') parts.pop()
  return `/${parts.map(part => part.replace(/^\[\.\.\.(.+)\]$/, ':$1*').replace(/^\[(.+)\]$/, ':$1')).join('/')}`.replace(/\/$/, '') || '/'
}

function pageCatalogMap() {
  const source = read('apps/api/app/Support/Pages/catalog.go')
  const map = new Map()
  for (const match of source.matchAll(/ID:\s*"([^"]+)"[\s\S]*?CoreComponent:\s*"([^"]+)"/g)) {
    map.set(`apps/web/app/${match[2]}.vue`, match[1])
  }
  return map
}

function discoverUISurfaces() {
  const pageIDs = pageCatalogMap()
  const pages = walk('apps/web/app/pages', '.vue').map(source => {
    const route = routeFromPage(source)
    const scope = source.includes('/pages/admin/') ? 'admin' : 'public'
    const knownPageID = pageIDs.get(source)
    const name = knownPageID ? knownPageID : snake(route.replace(/^\//, '') || 'home').replaceAll('_', '.')
    return {
      id: `core.component.page.${name}`,
      contractVersion: `sforum.component.page.${name}@1`,
      kind: 'page', scope, route, source,
      targetRegistry: scope === 'admin' ? 'P7 Admin Surface Registry' : 'P9 Component Registry'
    }
  })
  const components = walk('apps/web/app/components', '.vue').map(source => {
    const filename = source.split('/').at(-1).replace(/\.vue$/, '')
    const scope = source.includes('/components/admin/') || source.includes('/components/extensions/settings/') || filename.startsWith('SFAdmin') ? 'admin' : 'shared'
    const name = snake(filename)
    return {
      id: `core.component.${scope}.${name}`,
      contractVersion: `sforum.component.${scope}.${name}@1`,
      kind: 'component', scope, source,
      targetRegistry: scope === 'admin' ? 'P7/P9 Admin and Component Registries' : 'P9 Component Registry'
    }
  })
  return [...pages, ...components].sort((a, b) => a.id.localeCompare(b.id))
}

function stableIdentityDocument(routes, ui) {
  return {
    schemaVersion: 1,
    routes: routes.map(({ id, contractVersion, method, path }) => ({ id, contractVersion, method, path })),
    ui: ui.map(({ id, contractVersion, source }) => ({ id, contractVersion, source }))
  }
}

function applyStableIdentities(routes, ui) {
  const absolute = resolve(root, identitiesPath)
  if (!existsSync(absolute)) {
    if (!bootstrapIdentities) {
      throw new Error(`missing reviewed stable identity map: ${identitiesPath}; run with --bootstrap-identities once`)
    }
    mkdirSync(dirname(absolute), { recursive: true })
    writeFileSync(absolute, `${JSON.stringify(stableIdentityDocument(routes, ui), null, 2)}\n`)
  }
  const identities = JSON.parse(readFileSync(absolute, 'utf8'))
  if (identities.schemaVersion !== 1) throw new Error('unsupported V3 catalog identity schema')
  const routeMap = new Map(identities.routes.map(item => [`${item.method} ${item.path}`, item]))
  const uiMap = new Map(identities.ui.map(item => [item.source, item]))
  const seenRoutes = new Set()
  const seenUI = new Set()
  for (const route of routes) {
    const key = `${route.method} ${route.path}`
    const identity = routeMap.get(key)
    if (!identity) throw new Error(`new or moved route needs a reviewed stable identity mapping: ${key}`)
    route.id = identity.id
    route.contractVersion = identity.contractVersion
    seenRoutes.add(key)
  }
  for (const item of ui) {
    const identity = uiMap.get(item.source)
    if (!identity) throw new Error(`new or moved UI surface needs a reviewed stable identity mapping: ${item.source}`)
    item.id = identity.id
    item.contractVersion = identity.contractVersion
    seenUI.add(item.source)
  }
  const staleRoutes = [...routeMap.keys()].filter(key => !seenRoutes.has(key))
  const staleUI = [...uiMap.keys()].filter(key => !seenUI.has(key))
  if (staleRoutes.length || staleUI.length) {
    throw new Error(`stable identity map contains removed sources; preserve ids through an explicit move or record deprecation:\n${[...staleRoutes, ...staleUI].map(value => `- ${value}`).join('\n')}`)
  }
}

function tableFirstColumn(path) {
  const lines = read(path).split('\n')
  const start = lines.findIndex(line => line.startsWith('| ') && line.includes('|'))
  if (start < 0) return []
  return lines.slice(start + 2).filter(line => line.startsWith('| ')).map(line => line.split('|')[1].trim().replaceAll('`', ''))
}

function discoverJobKinds() {
  const values = []
  for (const source of walk('apps/api/app', '.go').filter(path => !path.endsWith('_test.go'))) {
    for (const match of read(source).matchAll(/Kind\(\) string \{ return "([^"]+)" \}/g)) values.push({ id: match[1], source })
  }
  return [...new Map(values.map(value => [value.id, value])).values()].sort((a, b) => a.id.localeCompare(b.id))
}

function buildBackendInventory() {
  return {
    generatedAt: 'source-controlled',
    events: tableFirstColumn('docs/extensions/catalogs/events.md'),
    contributionPoints: tableFirstColumn('docs/extensions/catalogs/contribution-points.md'),
    providerSlots: tableFirstColumn('docs/extensions/catalogs/provider-slots.md'),
    schedules: tableFirstColumn('docs/extensions/catalogs/schedules.md'),
    jobKinds: discoverJobKinds(),
    ...currentBackendSurfaces
  }
}

function marker(content, expressions) {
  return expressions.some(expression => content.toLowerCase().includes(expression))
}

function buildAdminInventory() {
  return walk('apps/web/app/pages/admin', '.vue').map(source => {
    const content = read(source)
    const lower = content.toLowerCase()
    return {
      id: `core.admin.page.${snake(routeFromPage(source).replace(/^\/admin\/?/, '') || 'dashboard')}`,
      source,
      navigation: true,
      dashboard: source.endsWith('/admin/index.vue'),
      list: marker(content, ['utable', 'v-for', 'items']),
      columns: marker(content, ['columns', 'table.columns']),
      filters: marker(content, ['filter', 'search']),
      rowActions: marker(content, ['row.actions', 'dropdownmenu', 'actions']),
      bulkActions: marker(content, ['bulk', 'selectedrows', 'selecteditem']),
      forms: marker(content, ['uform', '<form', 'v-model']),
      notices: marker(content, ['ualert', 'toast', 'notice']),
      editorPanels: marker(content, ['editor', 'tiptap']),
      detailRegions: marker(content, ['drawer', 'modal', 'detail', 'slideover']),
      importer: lower.includes('import'),
      exporter: lower.includes('export')
    }
  })
}

function renderRoutes(routes) {
  const lines = ['# Core Route Catalog', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '', '| Stable ID | Contract | Method | Path | Access | Policy | Handler source |', '| --- | --- | --- | --- | --- | --- | --- |']
  for (const route of routes) lines.push(`| \`${route.id}\` | \`${route.contractVersion}\` | ${route.method} | \`${route.path}\` | ${route.access} | ${cell(route.policy)} | \`${route.source}\` |`)
  return `${lines.join('\n')}\n`
}

function renderGoRouteCatalog(routes) {
  const lines = [
    '// Code generated by scripts/v3-catalog/generate.mjs. DO NOT EDIT.',
    '',
    'package routes',
    '',
    'var generatedCoreRouteCatalog = [...]CoreRoute{'
  ]
  for (const route of routes) {
    lines.push(`\t{ID: ${JSON.stringify(route.id)}, ContractVersion: ${JSON.stringify(route.contractVersion)}, Method: ${JSON.stringify(route.method)}, Path: ${JSON.stringify(route.path)}},`)
  }
  lines.push(
    '}',
    '',
    '// CoreRouteCatalog returns a caller-owned copy of the reviewed P0 catalog.',
    'func CoreRouteCatalog() []CoreRoute {',
    '\treturn append([]CoreRoute(nil), generatedCoreRouteCatalog[:]...)',
    '}',
    ''
  )
  return lines.join('\n')
}

function renderUISurfaces(items) {
  const lines = ['# UI Surface Catalog', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '', '| Stable ID | Contract | Kind | Scope | Route | Source | V3 registry |', '| --- | --- | --- | --- | --- | --- | --- |']
  for (const item of items) lines.push(`| \`${item.id}\` | \`${item.contractVersion}\` | ${item.kind} | ${item.scope} | ${item.route ? `\`${item.route}\`` : '—'} | \`${item.source}\` | ${item.targetRegistry} |`)
  return `${lines.join('\n')}\n`
}

function renderMatrix(matrix) {
  const lines = ['# Extension Surface Matrix', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '', 'Every module must keep all eleven families explicit. `closed` requires a reason; `planned` names its delivery phase.', '', `| Module | ${matrixFamilies.join(' | ')} |`, `| --- | ${matrixFamilies.map(() => '---').join(' | ')} |`]
  for (const [module, values] of Object.entries(matrix)) {
    const cells = matrixFamilies.map(family => {
      const value = values[family]
      if (value.state === 'closed') return `closed: ${value.reason}`
      return `${value.state} ${value.phase}: ${value.contract || 'contract pending'}`
    })
    lines.push(`| ${module} | ${cells.map(cell).join(' | ')} |`)
  }
  return `${lines.join('\n')}\n`
}

function renderBackend(inventory) {
  const lines = ['# Current Backend Extension Surface Inventory', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '']
  for (const key of ['events', 'contributionPoints', 'providerSlots', 'schedules']) lines.push(`## ${key}\n\n${inventory[key].map(item => `- \`${item}\``).join('\n')}\n`)
  lines.push(`## jobKinds\n\n${inventory.jobKinds.map(item => `- \`${item.id}\` — \`${item.source}\``).join('\n')}\n`)
  for (const key of ['cache', 'content', 'data']) lines.push(`## ${key}\n\n${inventory[key].map(item => `- \`${item[0]}\` — ${item[1]}`).join('\n')}\n`)
  return `${lines.join('\n').replace(/\n+$/, '')}\n`
}

function renderAdmin(items) {
  const keys = ['navigation', 'dashboard', 'list', 'columns', 'filters', 'rowActions', 'bulkActions', 'forms', 'notices', 'editorPanels', 'detailRegions', 'importer', 'exporter']
  const lines = ['# Current Admin Surface Inventory', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. Marker-based inventory; review semantic behavior before changing a contract. -->', '', `| Stable ID | Source | ${keys.join(' | ')} |`, `| --- | --- | ${keys.map(() => '---:').join(' | ')} |`]
  for (const item of items) lines.push(`| \`${item.id}\` | \`${item.source}\` | ${keys.map(key => item[key] ? 'yes' : 'no').join(' | ')} |`)
  return `${lines.join('\n')}\n`
}

const traceability = buildTraceability(parseAuthoritativeRows())
const routes = discoverRoutes()
const ui = discoverUISurfaces()
applyStableIdentities(routes, ui)
const backend = buildBackendInventory()
const admin = buildAdminInventory()

put('knowledge/plans/2026-07-13-trusted-plugin-theme-platform-v3-traceability.md', renderTraceability(traceability))
json('docs/extensions/v3/catalogs/routes.json', routes)
put('docs/extensions/v3/catalogs/routes.md', renderRoutes(routes))
put('apps/api/app/Support/Routes/core_catalog_gen.go', renderGoRouteCatalog(routes))
json('docs/extensions/v3/catalogs/ui-surfaces.json', ui)
put('docs/extensions/v3/catalogs/ui-surfaces.md', renderUISurfaces(ui))
json('docs/extensions/v3/catalogs/backend-surfaces.json', backend)
put('docs/extensions/v3/catalogs/backend-surfaces.md', renderBackend(backend))
json('docs/extensions/v3/extension-surface-matrix.json', extensionSurfaceMatrix)
put('docs/extensions/v3/extension-surface-matrix.md', renderMatrix(extensionSurfaceMatrix))
json('docs/extensions/v3/catalogs/admin-surfaces.json', admin)
put('docs/extensions/v3/catalogs/admin-surfaces.md', renderAdmin(admin))

const drift = []
for (const [path, expected] of outputs) {
  const absolute = resolve(root, path)
  if (check) {
    if (!existsSync(absolute) || readFileSync(absolute, 'utf8') !== expected) drift.push(path)
  } else {
    mkdirSync(dirname(absolute), { recursive: true })
    writeFileSync(absolute, expected)
  }
}
if (drift.length) throw new Error(`V3 P0 catalogs are stale:\n${drift.map(path => `- ${path}`).join('\n')}`)
console.log(check ? `V3 P0 catalogs are current (${outputs.size} files).` : `Generated ${outputs.size} V3 P0 catalog files.`)
