#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, extname, join, relative, resolve } from 'node:path'
import { buildTraceability } from './traceability.mjs'
import { currentBackendSurfaces, extensionSurfaceMatrix, matrixFamilies } from './surfaces.mjs'

const root = resolve(import.meta.dirname, '../..')
const check = process.argv.includes('--check')
const bootstrapIdentities = process.argv.includes('--bootstrap-identities')
const outputs = new Map()
const identitiesArgument = process.argv.find(argument => argument.startsWith('--identities='))
const identitiesPath = identitiesArgument?.slice('--identities='.length) || 'docs/extensions/v3/catalog-identities.json'
const retiredIdentitiesArgument = process.argv.find(argument => argument.startsWith('--retired-identities='))
const retiredIdentitiesPath = retiredIdentitiesArgument?.slice('--retired-identities='.length) || 'docs/extensions/v3/catalog-retired-identities.json'
const retiredCatalogArgument = process.argv.find(argument => argument.startsWith('--retired-catalog='))
const retiredCatalogPath = retiredCatalogArgument?.slice('--retired-catalog='.length) || 'docs/extensions/v3/catalogs/ui-retired-identities.json'
const retiredHistoryRootArgument = process.argv.find(argument => argument.startsWith('--retired-history-root='))
const retiredHistoryRoot = retiredHistoryRootArgument?.slice('--retired-history-root='.length) || root
const enforceRetiredHistory = !retiredIdentitiesArgument || Boolean(retiredHistoryRootArgument)
const coreComponentIDPattern = /^core\.component\.[a-z0-9][a-z0-9._-]*$/
const componentContractPattern = /^sforum\.component\.[a-z0-9][a-z0-9._-]*@[1-9][0-9]*$/

function read(path) {
  return readFileSync(resolve(root, path), 'utf8')
}

function walk(path, suffix) {
  const absolute = resolve(root, path)
  const result = []
  for (const name of readdirSync(absolute)) {
    const child = join(absolute, name)
    if (statSync(child).isDirectory()) result.push(...walk(relative(root, child), suffix))
    else if (!suffix || child.endsWith(suffix)) result.push(relative(root, child))
  }
  return result.sort()
}

function put(path, content) {
  outputs.set(path, content.endsWith('\n') ? content : `${content}\n`)
}

function json(path, value) {
  put(path, `${JSON.stringify(value, null, 2)}\n`)
}

function cell(value) {
  return String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function parseAuthoritativeRows() {
  const source = read('knowledge/decisions/2026-07-13-trusted-plugin-theme-platform-v3.md')
  const sections = [
    ['theme', '### Template And Theme Mechanism Comparison', '### Plugin Mechanism Comparison'],
    ['plugin', '### Plugin Mechanism Comparison', '## Architecture Mind Map']
  ]
  const rows = []
  for (const [family, startMarker, endMarker] of sections) {
    const start = source.indexOf(startMarker)
    const end = source.indexOf(endMarker, start + startMarker.length)
    if (start < 0 || end < 0) throw new Error(`cannot find ADR table: ${family}`)
    const lines = source.slice(start, end).split('\n').filter(line => line.startsWith('| '))
    for (const line of lines.slice(2)) {
      const columns = line.split('|').slice(1, -1).map(item => item.trim())
      if (columns.length !== 3) throw new Error(`invalid ${family} table row: ${line}`)
      rows.push({ family, surface: columns[0], current: columns[1], target: columns[2] })
    }
  }
  if (rows.length !== 99) throw new Error(`ADR must contain 99 authoritative rows, found ${rows.length}`)
  return rows
}

function renderTraceability(rows) {
  const lines = [
    '# Trusted Plugin And Theme Platform V3 Traceability Matrix',
    '',
    '<!-- Generated by scripts/v3-catalog/generate.mjs. Do not edit by hand. -->',
    '',
    'This matrix maps all 27 theme rows and 72 plugin rows from the accepted V3 ADR.',
    'A row remains incomplete until its named test exists and the phase exit gate passes.',
    '',
    '| # | Family | Surface | Current | V3 target | Phase | Contract | Test ID | Rollback |',
    '| ---: | --- | --- | --- | --- | --- | --- | --- | --- |'
  ]
  for (const row of rows) {
    lines.push(`| ${row.row} | ${cell(row.family)} | ${cell(row.surface)} | ${cell(row.current)} | ${cell(row.target)} | ${row.phase} | ${cell(row.contract)} | \`${row.test}\` | ${cell(row.rollback)} |`)
  }
  lines.push('')
  return lines.join('\n')
}

function normalizePath(...parts) {
  const value = parts.join('/').replaceAll(/\/+/g, '/')
  return value === '/' ? value : value.replace(/\/$/, '')
}

function snake(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
}

function routeRegistrationSource(source, receiver, method, path) {
  const needle = `${receiver}.${method}(${JSON.stringify(path)}`
  const lines = read(source).split('\n')
  const matches = lines.flatMap((line, index) => line.includes(needle) ? [index + 1] : [])
  if (matches.length !== 1) {
    throw new Error(`expected exactly one route registration ${needle} in ${source}, found ${matches.length}`)
  }
  return `${source}:${matches[0]}`
}

function routePolicy(route) {
  const { handler, method, module, path } = route
  if (path === '/api/v1/health' || path === '/api/v1/ready') return ['public', 'host liveness/readiness; non-overridable recovery prerequisite']
  if (path === '/api/v1/extensions/:extensionId/*') return ['declared', 'enabled plugin route declaration and manifest access policy']
  if (path.startsWith('/api/v1/extensions/runtime/')) return ['public', 'exact public frontend artifact trust, digest, and live runtime policy']
  if (path === '/api/v1/admin/extensions/:id/frontend/confirmation' && method === 'POST') return ['super_admin', 'active super_admin challenge issuance']
  if (path === '/api/v1/admin/extensions/:id/frontend/trust' && method === 'POST') return ['super_admin', 'active super_admin plus actor-bound exact frontend artifact confirmation']
  if (path === '/api/v1/admin/extensions/:id/frontend/trust' && method === 'DELETE') return ['super_admin', 'active super_admin trust revocation']
  if (path.startsWith('/api/v1/admin/extensions')) return ['permission', method === 'GET' ? 'extension.view or matching manage permission' : 'extension.plugin.manage or extension.theme.manage; operation-specific service policy']
  if (path.startsWith('/api/v1/admin/pages')) return ['permission', 'extension.view for inspection; theme/plugin manage and super_admin approval where required']
  if (path.startsWith('/api/v1/admin/attachment-settings')) return ['permission', 'attachment.settings.manage']
  if (path.startsWith('/api/v1/admin/attachments')) return ['permission', 'attachment.manage']
  if (path.startsWith('/api/v1/admin/database')) return ['permission', 'database.manage']
  if (path.startsWith('/api/v1/admin/entity-meta')) return ['permission', 'entity_meta.manage or settings.manage']
  if (path.startsWith('/api/v1/admin/forum/search')) return ['permission', 'search.manage']
  if (path.startsWith('/api/v1/admin/forum/categories') || path.startsWith('/api/v1/admin/forum/category-groups')) return ['permission', 'category.manage']
  if (path.startsWith('/api/v1/admin/forum/tags')) return ['permission', 'tag.manage']
  if (path.startsWith('/api/v1/admin/forum/settings')) return ['permission', 'category.manage, tag.manage, or forum.settings.manage; field owner recheck']
  if (path.startsWith('/api/v1/admin/jobs')) return ['permission', method === 'GET' ? 'jobs.view' : 'jobs.manage']
  if (path.startsWith('/api/v1/admin/mail')) return ['permission', 'settings.mail.manage or settings.manage compatibility policy']
  if (path.startsWith('/api/v1/admin/moderation')) return ['permission', 'moderation.manage']
  if (path.startsWith('/api/v1/moderation/workbench')) return ['permission', 'moderation.review; moderation.view_ip controls sensitive fields']
  if (path.startsWith('/api/v1/admin/notifications')) return ['permission', 'settings.manage']
  if (path.startsWith('/api/v1/admin/seo')) return ['permission', 'seo.manage']
  if (path.startsWith('/api/v1/admin/site')) return ['permission', 'settings.site.manage']
  if (path.startsWith('/api/v1/admin/webhooks')) return ['permission', 'settings.manage or settings.site.manage']
  if (path.startsWith('/api/v1/admin/features')) return ['permission', 'settings.site.manage']
  if (path.startsWith('/api/v1/admin/web-options')) return ['permission', 'option-owner permission dispatch']
  if (path === '/api/v1/admin/overview') return ['permission', 'admin.access']
  if (path.startsWith('/api/v1/admin/admin-surfaces')) return ['permission', 'admin.access']
  if (path.startsWith('/api/v1/roles/suggestions')) return ['permission', 'active cookie session with role.manage; PAT denied; Host explicit decision']
  if (/^\/api\/v1\/(permissions|roles|users)(\/|$)/.test(path)) return ['permission', 'identity service route-specific user.view/user.manage/role.manage/user.ban policy']
  if (path.startsWith('/api/v1/auth/sessions') || path.startsWith('/api/v1/auth/tokens')) return ['login', 'current active actor; token/session ownership']
  if (path === '/api/v1/auth/logout' || path === '/api/v1/auth/session') return ['login', 'current browser session']
  if (/^\/api\/v1\/auth\/(registration-status|register|login|password-reset)/.test(path)) return ['public', 'identity bootstrap, risk, rate-limit, and human-verification policy']
  if (path === '/api/v1/human-verification/challenge') return ['public', 'purpose allowlist and Redis rate/replay policy']
  if (path.startsWith('/api/v1/profile') && !path.startsWith('/api/v1/profiles')) return ['login', 'current active actor; attachment.upload for avatar upload']
  if (path.startsWith('/api/v1/notifications')) return ['login', 'current recipient ownership']
  if (path === '/api/v1/moderation/reports') return ['login', 'active actor and report deduplication policy']
  if (path === '/api/v1/me/content-review') return ['login', 'current active author ownership']
  if (path.startsWith('/api/v1/entity-meta/') && method !== 'GET') return ['permission', 'entity ownership plus field definition write policy']
  if (path.startsWith('/api/v1/entity-meta/')) return ['contextual', 'public definition visibility or actor/resource read policy']
  if (path === '/api/v1/attachments' && method === 'POST') return ['permission', 'attachment.upload plus upload/media policy']
  if (path.startsWith('/api/v1/attachments/')) return ['contextual', 'attachment visibility and referenced resource read policy']
  if (path === '/api/v1/topics' && method === 'POST') return ['permission', 'topic.create plus forum publication policy']
  if (/\/topics\/:topicID\/(hide|restore)$/.test(path)) return ['permission', 'topic.delete_any plus state policy']
  if (/\/topics\/:topicID\/(lock|unlock)$/.test(path)) return ['permission', 'topic.lock or allowed author close policy']
  if (/\/topics\/:topicID\/(pin|unpin)$/.test(path)) return ['permission', 'topic.pin']
  if (path === '/api/v1/topics/:topicID' && method === 'PATCH') return ['permission', 'topic.edit_own or topic.edit_any']
  if (path === '/api/v1/topics/:topicID' && method === 'DELETE') return ['permission', 'topic.delete_own or topic.delete_any']
  if (path.endsWith('/comments') && method === 'POST') return ['permission', 'post.create plus topic/publication policy']
  if (path.startsWith('/api/v1/comments/') && method !== 'GET') return ['permission', 'post edit/delete own or any policy']
  if (path === '/api/v1/web-options' && method === 'PUT') return ['permission', 'option-owner permission dispatch']
  if (path.startsWith('/api/v1/webhooks/inbound')) return ['public', 'source-specific signature/idempotency policy']
  if (path.startsWith('/api/v1/pages/resolve')) return ['contextual', 'resolved Page Registry access enum; loader receives no raw session authority']
  if (path.startsWith('/api/v1/site/theme-assets')) return ['public', 'active package containment, digest, MIME, and path policy']
  if (path.startsWith('/api/v1/site/') || path.startsWith('/api/v1/web-options') || path.startsWith('/api/v1/profiles/')) return ['public', 'public read contract']
  if (method === 'GET') return ['public', `${module} public read policy; visibility rechecked by service`]
  return ['service-policy', `${module}.${handler} authoritative actor/action/resource policy`]
}

const reviewedGuardPolicies = new Map([
  ['admin.access', { kind: 'permission_any', permissions: ['admin.access'] }],
  ['attachment.manage', { kind: 'permission_any', permissions: ['attachment.manage'] }],
  ['attachment.settings.manage', { kind: 'permission_any', permissions: ['attachment.settings.manage'] }],
  ['category.manage', { kind: 'permission_any', permissions: ['category.manage'] }],
  ['database.manage', { kind: 'permission_any', permissions: ['database.manage'] }],
  ['entity_meta.manage or settings.manage', { kind: 'permission_any', permissions: ['entity_meta.manage', 'settings.manage'] }],
  ['jobs.manage', { kind: 'permission_any', permissions: ['jobs.manage'] }],
  ['jobs.view', { kind: 'permission_any', permissions: ['jobs.view'] }],
  ['moderation.manage', { kind: 'permission_any', permissions: ['moderation.manage'] }],
  ['search.manage', { kind: 'permission_any', permissions: ['search.manage'] }],
  ['seo.manage', { kind: 'permission_any', permissions: ['seo.manage'] }],
  ['settings.mail.manage or settings.manage compatibility policy', { kind: 'permission_any', permissions: ['settings.mail.manage', 'settings.manage'] }],
  ['settings.manage', { kind: 'permission_any', permissions: ['settings.manage'] }],
  ['settings.manage or settings.site.manage', { kind: 'permission_any', permissions: ['settings.manage', 'settings.site.manage'] }],
  ['settings.site.manage', { kind: 'permission_any', permissions: ['settings.site.manage'] }],
  ['tag.manage', { kind: 'permission_any', permissions: ['tag.manage'] }],
  ['topic.pin', { kind: 'permission_any', permissions: ['topic.pin'] }],
  ['active super_admin challenge issuance', { kind: 'super_admin' }],
  ['active super_admin plus actor-bound exact frontend artifact confirmation', { kind: 'super_admin' }],
  ['active super_admin trust revocation', { kind: 'super_admin' }],
  ['host liveness/readiness; non-overridable recovery prerequisite', { kind: 'public' }],
  ['public read contract', { kind: 'public' }],
  ['exact public frontend artifact trust, digest, and live runtime policy', { kind: 'public' }],
  ['current browser session', { kind: 'login' }],

  ['attachment.upload plus upload/media policy', { kind: 'contextual', permissions: ['attachment.upload'], evaluatorId: 'core.guard.attachments.upload' }],
  ['attachment visibility and referenced resource read policy', { kind: 'contextual', evaluatorId: 'core.guard.attachments.read' }],
  ['category.manage, tag.manage, or forum.settings.manage; field owner recheck', { kind: 'contextual', permissions: ['category.manage', 'tag.manage', 'forum.settings.manage'], evaluatorId: 'core.guard.forum.settings' }],
  ['enabled plugin route declaration and manifest access policy', { kind: 'contextual', evaluatorId: 'core.guard.extensions.declared_route' }],
  ['entity ownership plus field definition write policy', { kind: 'contextual', evaluatorId: 'core.guard.entity_meta.write' }],
  ['extension.plugin.manage or extension.theme.manage; operation-specific service policy', { kind: 'contextual', evaluatorId: 'core.guard.extensions.mutation' }],
  ['extension.view for inspection; theme/plugin manage and super_admin approval where required', { kind: 'contextual', evaluatorId: 'core.guard.pages.admin' }],
  ['extension.view or matching manage permission', { kind: 'contextual', evaluatorId: 'core.guard.extensions.read' }],
  ['active cookie session with role.manage; PAT denied; Host explicit decision', { kind: 'contextual', evaluatorId: 'core.guard.identity.admin' }],
  ['identity service route-specific user.view/user.manage/role.manage/user.ban policy', { kind: 'contextual', evaluatorId: 'core.guard.identity.admin' }],
  ['moderation.review; moderation.view_ip controls sensitive fields', { kind: 'contextual', permissions: ['moderation.review'], evaluatorId: 'core.guard.moderation.review' }],
  ['option-owner permission dispatch', { kind: 'contextual', evaluatorId: 'core.guard.options.owner' }],
  ['post edit/delete own or any policy', { kind: 'contextual', permissions: ['post.edit_own', 'post.edit_any', 'post.delete_own', 'post.delete_any'], evaluatorId: 'core.guard.forum.comment_write' }],
  ['post.create plus topic/publication policy', { kind: 'contextual', permissions: ['post.create'], evaluatorId: 'core.guard.forum.comment_create' }],
  ['topic.create plus forum publication policy', { kind: 'contextual', permissions: ['topic.create'], evaluatorId: 'core.guard.forum.topic_create' }],
  ['topic.delete_any plus state policy', { kind: 'contextual', permissions: ['topic.delete_any'], evaluatorId: 'core.guard.forum.topic_state' }],
  ['topic.delete_own or topic.delete_any', { kind: 'contextual', permissions: ['topic.delete_own', 'topic.delete_any'], evaluatorId: 'core.guard.forum.topic_delete' }],
  ['topic.edit_own or topic.edit_any', { kind: 'contextual', permissions: ['topic.edit_own', 'topic.edit_any'], evaluatorId: 'core.guard.forum.topic_edit' }],
  ['topic.lock or allowed author close policy', { kind: 'contextual', permissions: ['topic.lock'], evaluatorId: 'core.guard.forum.topic_lock' }],
  ['active actor and report deduplication policy', { kind: 'contextual', evaluatorId: 'core.guard.moderation.report' }],
  ['current active actor; attachment.upload for avatar upload', { kind: 'contextual', evaluatorId: 'core.guard.profile.self' }],
  ['current active actor; token/session ownership', { kind: 'contextual', evaluatorId: 'core.guard.identity.self_credentials' }],
  ['current active author ownership', { kind: 'contextual', evaluatorId: 'core.guard.forum.author_review' }],
  ['current recipient ownership', { kind: 'contextual', evaluatorId: 'core.guard.notifications.recipient' }],
  ['active package containment, digest, MIME, and path policy', { kind: 'contextual', evaluatorId: 'core.guard.pages.theme_asset' }],
  ['forum public read policy; visibility rechecked by service', { kind: 'contextual', evaluatorId: 'core.guard.forum.read' }],
  ['identity bootstrap, risk, rate-limit, and human-verification policy', { kind: 'contextual', evaluatorId: 'core.guard.identity.bootstrap' }],
  ['pages public read policy; visibility rechecked by service', { kind: 'contextual', evaluatorId: 'core.guard.pages.catalog' }],
  ['public definition visibility or actor/resource read policy', { kind: 'contextual', evaluatorId: 'core.guard.entity_meta.read' }],
  ['purpose allowlist and Redis rate/replay policy', { kind: 'contextual', evaluatorId: 'core.guard.identity.human_verification' }],
  ['resolved Page Registry access enum; loader receives no raw session authority', { kind: 'contextual', evaluatorId: 'core.guard.pages.resolve' }],
  ['seo public read policy; visibility rechecked by service', { kind: 'contextual', evaluatorId: 'core.guard.seo.read' }],
  ['source-specific signature/idempotency policy', { kind: 'contextual', evaluatorId: 'core.guard.webhooks.inbound' }]
])

function reviewedRouteGuard(route, access, policy) {
  const reviewed = reviewedGuardPolicies.get(policy)
  if (!reviewed) throw new Error(`route ${route.method} ${route.path} has no reviewed guard classification: ${access} / ${policy}`)
  return {
    kind: reviewed.kind,
    permissions: [...(reviewed.permissions || [])],
    evaluatorId: reviewed.evaluatorId || ''
  }
}

function discoverRoutes() {
  const files = walk('apps/api/app/Http/Controllers', '.go').filter(path => !path.endsWith('_test.go'))
  const routes = []
  for (const source of files) {
    const content = read(source)
    if (!content.includes('RegisterRoutes')) continue
    const module = snake(source.split('/').at(-2))
    const routers = new Map([['api', '']])
    const lines = content.split('\n')
    for (let index = 0; index < lines.length; index++) {
      const line = lines[index]
      const group = line.match(/(\w+)\s*:=\s*(\w+)\.Group\("([^"]*)"\)/)
      if (group && routers.has(group[2])) routers.set(group[1], normalizePath(routers.get(group[2]), group[3]))
      for (const match of line.matchAll(/(\w+)\.(Get|Post|Put|Patch|Delete|All)\("([^"]*)"\s*,([^)]*)\)/g)) {
        if (!routers.has(match[1])) continue
        const handlerMatch = [...match[4].matchAll(/h\.([A-Za-z0-9_]+)/g)].at(-1)
        if (!handlerMatch) continue
        const path = normalizePath('/api/v1', routers.get(match[1]), match[3])
        const method = match[2] === 'All' ? '*' : match[2].toUpperCase()
        routes.push({ module, handler: handlerMatch[1], method, path, source: `${source}:${index + 1}` })
      }
    }
  }
  routes.push(
    { module: 'system', handler: 'health', method: 'GET', path: '/api/v1/health', source: routeRegistrationSource('apps/api/app/Http/server.go', 'api', 'Get', '/health') },
    { module: 'system', handler: 'ready', method: 'GET', path: '/api/v1/ready', source: routeRegistrationSource('apps/api/app/Http/server.go', 'api', 'Get', '/ready') }
  )
  const unique = new Map()
  for (const route of routes) unique.set(`${route.method} ${route.path} ${route.handler}`, route)
  const items = [...unique.values()].sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
  const idCount = new Map()
  for (const item of items) idCount.set(`${item.module}.${snake(item.handler)}`, (idCount.get(`${item.module}.${snake(item.handler)}`) || 0) + 1)
  return items.map(item => {
    const base = `${item.module}.${snake(item.handler)}`
    const suffix = idCount.get(base) > 1 ? `.${item.method.toLowerCase().replace('*', 'all')}` : ''
    const [access, policy] = routePolicy(item)
    return {
      id: `core.route.${base}${suffix}`,
      contractVersion: `sforum.route.${base}@1`,
      ...item,
      access,
      policy,
      guard: reviewedRouteGuard(item, access, policy)
    }
  })
}

function routeFromPage(source) {
  const parts = source.replace('apps/web/app/pages/', '').replace(/\.vue$/, '').split('/')
  if (parts.at(-1) === 'index') parts.pop()
  return `/${parts.map(part => part.replace(/^\[\.\.\.(.+)\]$/, ':$1*').replace(/^\[(.+)\]$/, ':$1')).join('/')}`.replace(/\/$/, '') || '/'
}

function pageCatalogMap() {
  const source = read('apps/api/app/Support/Pages/catalog.go')
  const map = new Map()
  for (const match of source.matchAll(/ID:\s*"([^"]+)"[\s\S]*?CoreComponent:\s*"([^"]+)"/g)) {
    map.set(`apps/web/app/${match[2]}.vue`, match[1])
  }
  return map
}

function discoverUISurfaces() {
  const pageIDs = pageCatalogMap()
  const pages = walk('apps/web/app/pages', '.vue').map(source => {
    const route = routeFromPage(source)
    const discoveredOwner = source.includes('/pages/admin/') ? 'admin' : 'public'
    const knownPageID = pageIDs.get(source)
    const name = knownPageID ? knownPageID : snake(route.replace(/^\//, '') || 'home').replaceAll('_', '.')
    return {
      id: `core.component.page.${name}`,
      contractVersion: `sforum.component.page.${name}@1`,
      kind: 'page', discoveredOwner, route, source
    }
  })
  const components = walk('apps/web/app/components', '.vue').map(source => {
    const filename = source.split('/').at(-1).replace(/\.vue$/, '')
    const discoveredOwner = source.includes('/components/admin/') || source.includes('/components/extensions/settings/') || filename.startsWith('SFAdmin') ? 'admin' : ''
    const namespace = discoveredOwner || 'shared'
    const name = snake(filename)
    return {
      id: `core.component.${namespace}.${name}`,
      contractVersion: `sforum.component.${namespace}.${name}@1`,
      kind: 'component', discoveredOwner, source
    }
  })
  return [...pages, ...components].sort((a, b) => a.id.localeCompare(b.id))
}

function stableIdentityDocument(routes, ui) {
  return {
    schemaVersion: 2,
    routes: routes.map(({ id, contractVersion, method, path }) => ({ id, contractVersion, method, path })),
    ui: ui.map(({ id, contractVersion, kind, discoveredOwner, source }) => ({
      id,
      contractVersion,
      kind,
      // Empty ownership is deliberate: newly discovered shared components need human review.
      owners: discoveredOwner ? [discoveredOwner] : [],
      state: 'active',
      source
    }))
  }
}

function reviewedIdentityMap(items, key, label) {
  if (!Array.isArray(items)) throw new Error(`stable identity map ${label} must be an array`)
  const result = new Map()
  for (const item of items) {
    const value = key(item)
    if (!value) throw new Error(`stable identity map ${label} contains an empty identity`)
    if (result.has(value)) throw new Error(`stable identity map ${label} contains duplicate ${value}`)
    result.set(value, item)
  }
  return result
}

function loadHistoricalRetiredUI(ledgerAbsolute) {
  if (!enforceRetiredHistory) return []
  const historyRoot = resolve(retiredHistoryRoot)
  const ledgerPath = relative(historyRoot, ledgerAbsolute)
  if (ledgerPath.startsWith('..') || ledgerPath === '') {
    throw new Error(`retired identity ledger is outside history root: ${ledgerAbsolute}`)
  }
  const shallow = spawnSync('git', ['rev-parse', '--is-shallow-repository'], { cwd: historyRoot, encoding: 'utf8' })
  if (shallow.status !== 0) throw new Error('retired identity append-only validation requires a Git worktree')
  if (shallow.stdout.trim() === 'true') {
    throw new Error('retired identity append-only validation requires full Git history; fetch the shallow clone before checking catalogs')
  }
  const renames = spawnSync('git', ['log', '--format=', '--name-status', '--follow', '--find-renames', '--', ledgerPath], { cwd: historyRoot, encoding: 'utf8' })
  if (renames.status !== 0) throw new Error(renames.stderr || 'cannot inspect retired identity ledger renames')
  if (/^R[0-9]+\t/m.test(renames.stdout)) {
    throw new Error(`retired identity ledger path is immutable and was renamed: ${ledgerPath}`)
  }
  const log = spawnSync('git', ['log', '--format=%H', '--', ledgerPath], { cwd: historyRoot, encoding: 'utf8' })
  if (log.status !== 0) throw new Error(log.stderr || 'cannot read retired identity history')

  const byID = new Map()
  const byContract = new Map()
  for (const revision of log.stdout.trim().split('\n').filter(Boolean)) {
    const shown = spawnSync('git', ['show', `${revision}:${ledgerPath}`], { cwd: historyRoot, encoding: 'utf8' })
    if (shown.status !== 0) {
      throw new Error(`immutable retired identity ledger is unreadable at revision ${revision}: ${ledgerPath}`)
    }
    const document = JSON.parse(shown.stdout)
    if (document.schemaVersion !== 1 || !Array.isArray(document.ui)) {
      throw new Error(`revision ${revision} has an invalid retired identity ledger`)
    }
    for (const item of document.ui) {
      if (!coreComponentIDPattern.test(item.id) || !componentContractPattern.test(item.contractVersion)) {
        throw new Error(`revision ${revision} has an invalid retired identity ${item.id}`)
      }
      const priorID = byID.get(item.id)
      const priorContract = byContract.get(item.contractVersion)
      if (priorID && priorID.contractVersion !== item.contractVersion || priorContract && priorContract.id !== item.id) {
        throw new Error(`retired identity history conflicts at ${item.id} / ${item.contractVersion}`)
      }
      byID.set(item.id, item)
      byContract.set(item.contractVersion, item)
    }
  }
  return [...byID.values()]
}

function validateStableIdentities(identities, retiredIdentities, historicalRetiredUI) {
  if (identities.schemaVersion !== 2) throw new Error('unsupported V3 catalog identity schema')
  if (retiredIdentities.schemaVersion !== 1 || !Array.isArray(retiredIdentities.ui)) {
    throw new Error('unsupported V3 retired catalog identity schema')
  }

  const routeMap = reviewedIdentityMap(identities.routes, item => `${item.method} ${item.path}`, 'route method/path')
  reviewedIdentityMap(identities.routes, item => item.id, 'route ids')
  reviewedIdentityMap(identities.routes, item => item.contractVersion, 'route contracts')
  reviewedIdentityMap(identities.ui, item => item.id, 'UI ids')
  reviewedIdentityMap(identities.ui, item => item.contractVersion, 'UI contracts')
  const activeUI = identities.ui.filter(item => item.state === 'active')
  const retiredUI = identities.ui.filter(item => item.state === 'retired')
  const uiMap = reviewedIdentityMap(activeUI, item => item.source, 'active UI sources')
  const retiredUIByID = reviewedIdentityMap(retiredUI, item => item.id, 'retired UI ids')
  const tombstonesByID = reviewedIdentityMap(retiredIdentities.ui, item => item.id, 'retired UI tombstone ids')
  const tombstonesByContract = reviewedIdentityMap(retiredIdentities.ui, item => item.contractVersion, 'retired UI tombstone contracts')

  for (const item of identities.ui) {
    if (!coreComponentIDPattern.test(item.id)) {
      throw new Error(`stable UI identity has invalid id ${item.id}`)
    }
    if (!componentContractPattern.test(item.contractVersion)) {
      throw new Error(`stable UI identity ${item.id} has invalid contract ${item.contractVersion}`)
    }
    if (!['active', 'retired'].includes(item.state)) {
      throw new Error(`stable UI identity ${item.id} has invalid state ${item.state}`)
    }
    if (!['page', 'component'].includes(item.kind)) {
      throw new Error(`stable UI identity ${item.id} has invalid kind ${item.kind}`)
    }
    if (!Array.isArray(item.owners) || item.owners.length === 0) {
      throw new Error(`stable UI identity ${item.id} needs explicit public/admin ownership`)
    }
    const owners = ['public', 'admin'].filter(owner => item.owners.includes(owner))
    if (owners.length !== item.owners.length || owners.some((owner, index) => owner !== item.owners[index])) {
      throw new Error(`stable UI identity ${item.id} has invalid or non-canonical owners`)
    }
    if (item.kind === 'page' && item.owners.length !== 1) {
      throw new Error(`stable page identity ${item.id} must have exactly one owner`)
    }
    if (item.state === 'active' && (typeof item.source !== 'string' || item.source === '')) {
      throw new Error(`active stable UI identity ${item.id} needs a source`)
    }
    if (item.state === 'retired' && item.source !== undefined && (typeof item.source !== 'string' || item.source === '')) {
      throw new Error(`retired stable UI identity ${item.id} has an invalid historical source`)
    }
  }
  for (const tombstone of retiredIdentities.ui) {
    if (!coreComponentIDPattern.test(tombstone.id) || !componentContractPattern.test(tombstone.contractVersion)) {
      throw new Error(`retired UI tombstone has invalid identity ${tombstone.id} / ${tombstone.contractVersion}`)
    }
  }
  for (const historical of historicalRetiredUI) {
    const current = tombstonesByID.get(historical.id)
    if (!current || current.contractVersion !== historical.contractVersion) {
      throw new Error(`append-only retired UI tombstone was deleted or changed: ${historical.id} / ${historical.contractVersion}`)
    }
  }
  for (const item of activeUI) {
    if (tombstonesByID.has(item.id)) {
      throw new Error(`active UI identity ${item.id} reuses a retired id`)
    }
    if (tombstonesByContract.has(item.contractVersion)) {
      throw new Error(`active UI identity ${item.id} reuses retired contract ${item.contractVersion}`)
    }
  }
  for (const item of retiredUI) {
    const tombstone = tombstonesByID.get(item.id)
    if (!tombstone || tombstone.contractVersion !== item.contractVersion) {
      throw new Error(`retired UI identity ${item.id} needs an exact append-only tombstone`)
    }
  }
  for (const tombstone of retiredIdentities.ui) {
    const item = retiredUIByID.get(tombstone.id)
    if (!item || item.contractVersion !== tombstone.contractVersion) {
      throw new Error(`retired UI tombstone ${tombstone.id} is missing its retired identity row`)
    }
  }
  return { routeMap, uiMap }
}

function applyStableIdentities(routes, ui) {
  const absolute = resolve(root, identitiesPath)
  if (!existsSync(absolute)) {
    if (!bootstrapIdentities) {
      throw new Error(`missing reviewed stable identity map: ${identitiesPath}; run with --bootstrap-identities once`)
    }
    mkdirSync(dirname(absolute), { recursive: true })
    writeFileSync(absolute, `${JSON.stringify(stableIdentityDocument(routes, ui), null, 2)}\n`)
  }
  const identities = JSON.parse(readFileSync(absolute, 'utf8'))
  const retiredAbsolute = resolve(root, retiredIdentitiesPath)
  if (!existsSync(retiredAbsolute)) {
    throw new Error(`missing reviewed retired identity ledger: ${retiredIdentitiesPath}`)
  }
  const retiredIdentities = JSON.parse(readFileSync(retiredAbsolute, 'utf8'))
  const historicalRetiredUI = loadHistoricalRetiredUI(retiredAbsolute)
  const { routeMap, uiMap } = validateStableIdentities(identities, retiredIdentities, historicalRetiredUI)
  const seenRoutes = new Set()
  const seenUI = new Set()
  for (const route of routes) {
    const key = `${route.method} ${route.path}`
    const identity = routeMap.get(key)
    if (!identity) throw new Error(`new or moved route needs a reviewed stable identity mapping: ${key}`)
    route.id = identity.id
    route.contractVersion = identity.contractVersion
    seenRoutes.add(key)
  }
  for (const item of ui) {
    const identity = uiMap.get(item.source)
    if (!identity) throw new Error(`new or moved UI surface needs a reviewed stable identity mapping: ${item.source}`)
    if (identity.kind !== item.kind) {
      throw new Error(`stable UI identity kind drift for ${item.source}: reviewed ${identity.kind}, discovered ${item.kind}`)
    }
    if (item.discoveredOwner && !identity.owners.includes(item.discoveredOwner)) {
      throw new Error(`stable UI identity ownership drift for ${item.source}: discovered ${item.discoveredOwner}, reviewed ${identity.owners.join(',')}`)
    }
    item.id = identity.id
    item.contractVersion = identity.contractVersion
    item.owners = [...identity.owners]
    item.targetRegistry = item.kind === 'page' && item.owners[0] === 'admin'
      ? 'P7 Admin Surface Registry'
      : item.owners.includes('admin')
        ? 'P7/P9 Admin and Component Registries'
        : 'P9 Component Registry'
    delete item.discoveredOwner
    seenUI.add(item.source)
  }
  const staleRoutes = [...routeMap.keys()].filter(key => !seenRoutes.has(key))
  const staleUI = [...uiMap.keys()].filter(key => !seenUI.has(key))
  if (staleRoutes.length || staleUI.length) {
    throw new Error(`stable identity map contains removed sources; preserve ids through an explicit move or record deprecation:\n${[...staleRoutes, ...staleUI].map(value => `- ${value}`).join('\n')}`)
  }
  return retiredIdentities
}

function tableFirstColumn(path) {
  const lines = read(path).split('\n')
  const start = lines.findIndex(line => line.startsWith('| ') && line.includes('|'))
  if (start < 0) return []
  const values = []
  for (const line of lines.slice(start + 2)) {
    if (!line.startsWith('| ')) break
    values.push(line.split('|')[1].trim().replaceAll('`', ''))
  }
  return values
}

function discoverJobKinds() {
  const values = []
  for (const source of walk('apps/api/app', '.go').filter(path => !path.endsWith('_test.go'))) {
    for (const match of read(source).matchAll(/Kind\(\) string \{ return "([^"]+)" \}/g)) values.push({ id: match[1], source })
  }
  return [...new Map(values.map(value => [value.id, value])).values()].sort((a, b) => a.id.localeCompare(b.id))
}

function buildBackendInventory() {
  return {
    generatedAt: 'source-controlled',
    events: tableFirstColumn('docs/extensions/catalogs/events.md'),
    contributionPoints: tableFirstColumn('docs/extensions/catalogs/contribution-points.md'),
    providerSlots: tableFirstColumn('docs/extensions/catalogs/provider-slots.md'),
    schedules: tableFirstColumn('docs/extensions/catalogs/schedules.md'),
    jobKinds: discoverJobKinds(),
    ...currentBackendSurfaces
  }
}

function marker(content, expressions) {
  return expressions.some(expression => content.toLowerCase().includes(expression))
}

function buildAdminInventory() {
  return walk('apps/web/app/pages/admin', '.vue').map(source => {
    const content = read(source)
    const lower = content.toLowerCase()
    return {
      id: `core.admin.page.${snake(routeFromPage(source).replace(/^\/admin\/?/, '') || 'dashboard')}`,
      source,
      navigation: true,
      dashboard: source.endsWith('/admin/index.vue'),
      list: marker(content, ['utable', 'v-for', 'items']),
      columns: marker(content, ['columns', 'table.columns']),
      filters: marker(content, ['filter', 'search']),
      rowActions: marker(content, ['row.actions', 'dropdownmenu', 'actions']),
      bulkActions: marker(content, ['bulk', 'selectedrows', 'selecteditem']),
      forms: marker(content, ['uform', '<form', 'v-model']),
      notices: marker(content, ['ualert', 'toast', 'notice']),
      editorPanels: marker(content, ['editor', 'tiptap']),
      detailRegions: marker(content, ['drawer', 'modal', 'detail', 'slideover']),
      importer: lower.includes('import'),
      exporter: lower.includes('export')
    }
  })
}

function renderRoutes(routes) {
  const lines = ['# Core Route Catalog', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '', '| Stable ID | Contract | Method | Path | Access | Guard kind | Permissions | Evaluator | Policy | Handler source |', '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
  for (const route of routes) lines.push(`| \`${route.id}\` | \`${route.contractVersion}\` | ${route.method} | \`${route.path}\` | ${route.access} | \`${route.guard.kind}\` | ${route.guard.permissions.map(value => `\`${value}\``).join(', ') || '-'} | ${route.guard.evaluatorId ? `\`${route.guard.evaluatorId}\`` : '-'} | ${cell(route.policy)} | \`${route.source}\` |`)
  return `${lines.join('\n')}\n`
}

function renderGoRouteCatalog(routes) {
  const lines = [
    '// Code generated by scripts/v3-catalog/generate.mjs. DO NOT EDIT.',
    '',
    'package routes',
    '',
    'var generatedCoreRouteCatalog = [...]CoreRoute{'
  ]
  for (const route of routes) {
    const permissions = route.guard.permissions.map(value => JSON.stringify(value)).join(', ')
    lines.push(`\t{ID: ${JSON.stringify(route.id)}, ContractVersion: ${JSON.stringify(route.contractVersion)}, Method: ${JSON.stringify(route.method)}, Path: ${JSON.stringify(route.path)}, Guard: CoreGuardDescriptor{RouteID: ${JSON.stringify(route.id)}, ContractVersion: ${JSON.stringify(route.contractVersion)}, Method: ${JSON.stringify(route.method)}, Kind: CoreGuardKind(${JSON.stringify(route.guard.kind)}), Permissions: []string{${permissions}}, EvaluatorID: ${JSON.stringify(route.guard.evaluatorId)}}},`)
  }
  lines.push(
    '}',
    '',
    '// CoreRouteCatalog returns a caller-owned copy of the reviewed P0 catalog.',
    'func CoreRouteCatalog() []CoreRoute {',
    '\tresult := append([]CoreRoute(nil), generatedCoreRouteCatalog[:]...)',
    '\tfor index := range result {',
    '\t\tresult[index].Guard = cloneCoreGuardDescriptor(result[index].Guard)',
    '\t}',
    '\treturn result',
    '}',
    ''
  )
  return lines.join('\n')
}

function renderUISurfaces(items) {
  const lines = [
    '# UI Surface Catalog',
    '',
    '<!-- Generated by scripts/v3-catalog/generate.mjs. -->',
    '',
    'Only active identities are listed. Retired IDs and contracts remain reserved in `../catalog-identities.json` and the append-only `../catalog-retired-identities.json` ledger through their LTS/deprecation window.',
    'Manifest V3 component targets declare both `targetId` and `targetContractVersion`; Core targets must match this catalog exactly.',
    '',
    '| Stable ID | Contract | Kind | Owners | Route | Source | V3 registry |',
    '| --- | --- | --- | --- | --- | --- | --- |'
  ]
  for (const item of items) lines.push(`| \`${item.id}\` | \`${item.contractVersion}\` | ${item.kind} | ${item.owners.map(owner => `\`${owner}\``).join(', ')} | ${item.route ? `\`${item.route}\`` : '—'} | \`${item.source}\` | ${item.targetRegistry} |`)
  return `${lines.join('\n')}\n`
}

function renderGoComponentCatalog(items) {
  const kindConstant = { page: 'KindPage', component: 'KindComponent' }
  const ownerConstant = { public: 'OwnerPublic', admin: 'OwnerAdmin' }
  const lines = [
    '// Code generated by scripts/v3-catalog/generate.mjs. DO NOT EDIT.',
    '',
    'package componentcatalog',
    '',
    'var generatedCoreComponentCatalog = [...]CoreComponent{'
  ]
  for (const item of items) {
    const owners = item.owners.map(owner => ownerConstant[owner]).join(', ')
    lines.push(`\t{ID: ${JSON.stringify(item.id)}, ContractVersion: ${JSON.stringify(item.contractVersion)}, Kind: ${kindConstant[item.kind]}, Owners: []Owner{${owners}}, Route: ${JSON.stringify(item.route || '')}, Source: ${JSON.stringify(item.source)}},`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

function renderAdminSurfaceClientCatalog(items) {
  const pages = items.filter(item => item.kind === 'page' && item.owners.includes('admin'))
  const lines = [
    '// Code generated by scripts/v3-catalog/generate.mjs. DO NOT EDIT.',
    '',
    'export type AdminSurfacePlacement = {',
    '  id: string',
    '  contractVersion: string',
    '  route: string',
    '}',
    '',
    'export const adminSurfacePlacements = [',
  ]
  for (const page of pages) {
    lines.push(`  { id: ${JSON.stringify(page.id)}, contractVersion: ${JSON.stringify(page.contractVersion)}, route: ${JSON.stringify(page.route)} },`)
  }
  lines.push('] as const satisfies readonly AdminSurfacePlacement[]', '')
  return lines.join('\n')
}

function renderMatrix(matrix) {
  const lines = ['# Extension Surface Matrix', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '', 'Every module must keep all eleven families explicit. `closed` requires a reason; `planned` names its delivery phase.', '', `| Module | ${matrixFamilies.join(' | ')} |`, `| --- | ${matrixFamilies.map(() => '---').join(' | ')} |`]
  for (const [module, values] of Object.entries(matrix)) {
    const cells = matrixFamilies.map(family => {
      const value = values[family]
      if (value.state === 'closed') return `closed: ${value.reason}`
      return `${value.state} ${value.phase}: ${value.contract || 'contract pending'}`
    })
    lines.push(`| ${module} | ${cells.map(cell).join(' | ')} |`)
  }
  return `${lines.join('\n')}\n`
}

function renderBackend(inventory) {
  const lines = ['# Current Backend Extension Surface Inventory', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. -->', '']
  for (const key of ['events', 'contributionPoints', 'providerSlots', 'schedules']) lines.push(`## ${key}\n\n${inventory[key].map(item => `- \`${item}\``).join('\n')}\n`)
  lines.push(`## jobKinds\n\n${inventory.jobKinds.map(item => `- \`${item.id}\` — \`${item.source}\``).join('\n')}\n`)
  for (const key of ['cache', 'content', 'data']) lines.push(`## ${key}\n\n${inventory[key].map(item => `- \`${item[0]}\` — ${item[1]}`).join('\n')}\n`)
  return `${lines.join('\n').replace(/\n+$/, '')}\n`
}

function renderAdmin(items) {
  const keys = ['navigation', 'dashboard', 'list', 'columns', 'filters', 'rowActions', 'bulkActions', 'forms', 'notices', 'editorPanels', 'detailRegions', 'importer', 'exporter']
  const lines = ['# Current Admin Surface Inventory', '', '<!-- Generated by scripts/v3-catalog/generate.mjs. Marker-based inventory; review semantic behavior before changing a contract. -->', '', `| Stable ID | Source | ${keys.join(' | ')} |`, `| --- | --- | ${keys.map(() => '---:').join(' | ')} |`]
  for (const item of items) lines.push(`| \`${item.id}\` | \`${item.source}\` | ${keys.map(key => item[key] ? 'yes' : 'no').join(' | ')} |`)
  return `${lines.join('\n')}\n`
}

const traceability = buildTraceability(parseAuthoritativeRows())
const routes = discoverRoutes()
const ui = discoverUISurfaces()
const retiredIdentities = applyStableIdentities(routes, ui)
const backend = buildBackendInventory()
const admin = buildAdminInventory()

put('knowledge/plans/2026-07-13-trusted-plugin-theme-platform-v3-traceability.md', renderTraceability(traceability))
json('docs/extensions/v3/catalogs/routes.json', routes)
put('docs/extensions/v3/catalogs/routes.md', renderRoutes(routes))
put('apps/api/app/Support/Routes/core_catalog_gen.go', renderGoRouteCatalog(routes))
json('docs/extensions/v3/catalogs/ui-surfaces.json', ui)
put('docs/extensions/v3/catalogs/ui-surfaces.md', renderUISurfaces(ui))
json(retiredCatalogPath, retiredIdentities)
put('apps/api/app/Support/ComponentCatalog/core_catalog_gen.go', renderGoComponentCatalog(ui))
put('apps/web/app/config/adminSurfaceCatalog.gen.ts', renderAdminSurfaceClientCatalog(ui))
json('docs/extensions/v3/catalogs/backend-surfaces.json', backend)
put('docs/extensions/v3/catalogs/backend-surfaces.md', renderBackend(backend))
json('docs/extensions/v3/extension-surface-matrix.json', extensionSurfaceMatrix)
put('docs/extensions/v3/extension-surface-matrix.md', renderMatrix(extensionSurfaceMatrix))
json('docs/extensions/v3/catalogs/admin-surfaces.json', admin)
put('docs/extensions/v3/catalogs/admin-surfaces.md', renderAdmin(admin))

const drift = []
for (const [path, expected] of outputs) {
  const absolute = resolve(root, path)
  if (check) {
    if (!existsSync(absolute) || readFileSync(absolute, 'utf8') !== expected) drift.push(path)
  } else {
    mkdirSync(dirname(absolute), { recursive: true })
    writeFileSync(absolute, expected)
  }
}
if (drift.length) throw new Error(`V3 P0 catalogs are stale:\n${drift.map(path => `- ${path}`).join('\n')}`)
console.log(check ? `V3 P0 catalogs are current (${outputs.size} files).` : `Generated ${outputs.size} V3 P0 catalog files.`)
