import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { compileScript, parse } from '@vue/compiler-sfc'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
// 首页呈现已迁到 SFHomePage 岛；pages/index 仅为 SEO + fail-closed 壳。
const homepageIsland = () => source('../../app/components/forum/SFHomePage.vue')
const homepageRoute = () => source('../../app/pages/index.vue')
const searchRoute = () => source('../../app/pages/search.vue')
const defaultHomeTemplate = () => source('../../../../extensions/builtin/themes/sforum-default/templates/home.html')
const defaultSearchTemplate = () => source('../../../../extensions/builtin/themes/sforum-default/templates/search.html')
const nocturneHomeTemplate = () => source('../../../../extensions/builtin/themes/sforum-nocturne/templates/home.html')
const themeTemplate = () => source('../../app/components/SFThemeTemplate.vue')
const topicRow = () => source('../../app/components/forum/SFHomeTopicRow.vue')
const homeNav = () => source('../../app/components/forum/SFHomeNavigation.vue')
const categoryNav = () => source('../../app/components/forum/navigation/SFCategoryNavigationBlock.vue')
const sidebarContent = () => source('../../app/components/forum/navigation/SFPublicSidebarContent.vue')
const defaultLayout = () => source('../../app/layouts/default.vue')
const hostConfig = () => source('../../nuxt.config.ts')
const homepageCss = () => source('../../app/assets/css/sforum-home.css')
const themeCss = () => source('../../app/assets/css/sforum-theme.css')
const defaultThemeHybridCss = () => source('../../../../extensions/builtin/themes/sforum-default/assets/hybrid-forum.css')
const themePackage = () => source('../../../../extensions/builtin/themes/sforum-default/theme.json')
const footer = () => source('../../app/components/SFFooter.vue')
const homeQueryCacheMiddleware = () => source('../../server/middleware/home-query-cache.ts')
const pluginDocsTemplate = () => source('../../../../extensions/fixtures/plugins/page-registry-demo/templates/docs.html')

describe('default theme V32 left-nav homepage contract', () => {
  test('route shell is thin SEO + outlet; presentation lives on SFHomePage island', () => {
    const route = homepageRoute()
    expect(route).toContain('SFPageOutlet')
    expect(route).toContain('page="forum.home"')
    expect(route).toContain('<SFHomePage')
    expect(route).toContain('useSForumSeo')
    expect(route).not.toContain('class="sforum-home"')
    expect(route).not.toContain('sforum-home__topic-table')
    expect(route).not.toContain('loadMoreTopics')

    const template = themeTemplate()
    expect(template).toContain("'forum.component.home_page': defineAsyncComponent(() => import('./forum/SFHomePage.vue'))")
    expect(template).not.toContain("'forum.component.home_page': HostPageIsland")

    const defaultTpl = defaultHomeTemplate()
    expect(defaultTpl).toContain('data-theme-owned="presentation"')
    expect(defaultTpl).toContain('<sf-home-page>')
    expect(defaultTpl).toContain('sf-theme-home-shell')
    expect(defaultTpl).toContain('data-layout="fullwidth-3col"')
    expect(defaultTpl).toContain('sf-theme-shell--fullwidth-3col')

    const nocturneTpl = nocturneHomeTemplate()
    expect(nocturneTpl).toContain('data-theme-owned="presentation"')
    expect(nocturneTpl).toContain('<sf-home-page>')
    expect(nocturneTpl).toContain('nh-hero')
  })

  test('search owns a distinct Page Registry route while reusing the forum feed island', () => {
    const route = searchRoute()
    expect(route).toContain('page="forum.search"')
    expect(route).toContain('<SFHomePage')
    expect(route).toContain("publicPagePath('/search'")
    expect(route).toContain('noindex: true')

    const template = defaultSearchTemplate()
    expect(template).toContain('data-page="forum.search"')
    expect(template).toContain('<sf-search-page>')
    expect(template).toContain('<sf-navbar>')
    expect(template).toContain('<sf-footer>')
    expect(homepageRoute()).toContain("localePath('/search')")
    expect(homepageRoute()).toContain('redirectCode: 301')
  })

  test('uses the shared public layout with left sidebar and topic table', () => {
    const page = homepageIsland()

    expect(page).toContain('class="sforum-home"')
    expect(page).toContain('sforum-home__layout')
    expect(page).toContain('sforum-home__layout--with-right')
    expect(page).toContain('rightRailEnabled')
    expect(page).toContain('class="sforum-home__sidebar"')
    expect(page).toContain('class="sforum-home__main sforum-content-column"')
    expect(page).toContain('data-sf-region="topic-list"')
    expect(page).toContain('useActiveThemeSettings')
    expect(page).toContain('v-if="homeNotice"')
    expect(page).toContain('homeEmptyTitle')
    expect(page).toContain('rightRailHotLimit')
    expect(page).toContain('rightRailTagLimit')
    expect(page).toContain('<SFHomeTopicRow')
    expect(page).toContain('<SFHomeNavigation')
    expect(page).toContain('<SFHomeRightRail')
    expect(page).toContain('v-if="rightRailEnabled"')
    expect(page).toContain(':hot-topics="hotTopics"')
    expect(page).toContain('desktop-only')
    expect(page).not.toContain('mobile-only')
    expect(page).toContain("t('home.filter.latest')")
    expect(page).toContain('forum-feed-title')
    // 列表呈现：宿主 Tailwind，不再依赖 BEM main-bar / topic-table
    expect(page).not.toContain('sforum-home__main-bar')
    expect(page).not.toContain('sforum-home__topic-table')
    expect(page).not.toContain('layout: false')
    expect(page).not.toContain('sforum-home__hero')
    expect(page).not.toContain('sforum-home__aside')
    expect(page).toContain('<SFContentColumnFooter')
    expect(page).not.toContain('participants')
    expect(page).not.toContain('latestTopics')
    expect(page).not.toContain('loadedReplyTotal')

    // Nuxt default layout 透传；chrome 在主题 L1 与 fail-closed 宿主壳上。
    const layout = defaultLayout()
    expect(layout).toContain('<slot')
    expect(layout).not.toContain('<SFNavbar')
    expect(defaultHomeTemplate()).toContain('<sf-navbar>')
    expect(defaultHomeTemplate()).toContain('<sf-footer>')
    expect(nocturneHomeTemplate()).toContain('<sf-navbar>')
    expect(nocturneHomeTemplate()).toContain('<sf-footer>')
    const hostChrome = source('../../app/components/SFHostPublicChrome.vue')
    expect(hostChrome).toContain('<SFNavbar layout="fullwidth-3col" />')
    expect(hostChrome).toContain('layoutShowFooter')
    expect(hostChrome).toContain('layoutShowAnnouncements')
    expect(hostChrome).toContain('sf-host-public-chrome--fullwidth-3col')
    expect(hostChrome).toContain('data-layout="fullwidth-3col"')
  })

  test('keeps Host fallback chrome on the same desktop rails as the selected default theme', () => {
    const css = themeCss()
    const home = homepageCss()
    const navbar = source('../../app/components/SFNavbar.vue')

    expect(navbar).toContain('.navbar--fullwidth-3col .navbar__inner')
    expect(navbar).toContain('var(--sf-public-sidebar-width, 230px)')
    expect(navbar).toContain('var(--sf-public-right-rail-width, 270px)')
    expect(navbar).toContain("layout?: 'default' | 'fullwidth-3col'")
    expect(css).toContain('.sf-host-public-chrome--fullwidth-3col .sforum-home__main')
    expect(home).toContain('.sf-host-public-chrome--fullwidth-3col .sforum-home__layout')
    expect(home).toContain('padding: 30px 24px 28px;')
    expect(home).toContain('padding: 24px 24px 20px 28px;')
    expect(home).toContain('padding: 34px 28px;')
  })

  test('renders topic table rows using only API-backed summary data', () => {
    const row = topicRow()

    expect(row).toContain('topic: ForumTopicSummary')
    expect(row).toContain('to: string')
    expect(row).toContain('createdLabel: string')
    expect(row).toContain('activityLabel: string')
    expect(row).toContain('topic.createdAt')
    expect(row).toContain('topic.lastReplyAuthor')
    expect(row).toContain('topic.commentCount')
    expect(row).toContain('topic.categoryName')
    expect(row).toContain('topic.author')
    expect(row).toContain('topic.isPinned')
    expect(row).toContain('SFAvatar')
    expect(row).toContain(':avatar="topic.author?.avatar"')
    expect(row).toContain(':prefetch="false"')
    // 列表头像只走全局 SFAvatar（size=list + AvatarView），禁止强制字头/局部改尺寸
    expect(row).toContain('size="list"')
    expect(row).not.toContain('prefer-initials')
    expect(row).not.toContain('!size-9')
    // fullwidth-3col：宿主 Tailwind 行 + 扩展钩子；chip 色板在组件内
    expect(row).toContain('data-sf-component="forum.topic_list_row"')
    expect(row).toContain('forumCategoryChipToneClass')
    expect(row).toContain('grid-cols-[42px_minmax(0,1fr)_96px_54px_104px]')
    expect(row).toContain('sf-home-topic-row__activity')
    expect(row).toContain('sf-home-topic-row__replies')
    expect(row).toContain('sf-home-topic-row__meta')
    expect(row).not.toContain('sf-home-topic-row__chip')
    expect(row).not.toContain('topic.excerpt')
    expect(row).not.toContain('participants')
    expect(row).not.toContain('$fetch')
    expect(row).not.toContain('useForumApi')
  })

  test('left navigation exposes compose, all topics, and category counts', () => {
    const nav = homeNav()
    const categories = categoryNav()
    const content = sidebarContent()
    const css = homepageCss()

    expect(nav).toContain('<SFPublicSidebarContent')
    expect(content).toContain('sf-home-navigation__compose')
    // 侧边栏分类：管理端 icon + iconColor
    expect(categories).toContain('sf-home-navigation__cat-icon')
    expect(categories).toContain('categoryIconColor')
    expect(categories).toContain('categoryIconName')
    expect(categories).not.toContain('sf-home-navigation__cat-dot')
    expect(categories).toContain('category.topicCount')
    expect(content).toContain("t('home.sidebar.newTopic')")
    expect(content).toContain('canCreateTopic')
    expect(content).toContain('navShowCompose')
    expect(content).toContain('navShowCounts')
    expect(nav).toContain('categories?: ForumCategory[]')
    expect(nav).toContain('categories: () => []')
    expect(nav).toContain("selectedCategorySlug: ''")
    expect(nav).toContain('totalTopics: 0')
    expect(nav).toContain("navigationMode?: 'filter' | 'route'")
    expect(content).toContain('forumCategoryPath')
    expect(content).not.toContain('unread')
    expect(content).not.toContain('ranking')
    expect(css).not.toContain('.sf-home-navigation__mobile')
    expect(css).not.toContain('.sforum-home__mobile-nav')
    expect(nav).not.toContain('sf-home-navigation__select')
  })

  test('legacy theme navigation islands compile with safe empty defaults', () => {
    const { descriptor, errors } = parse(homeNav(), { filename: 'SFHomeNavigation.vue' })
    expect(errors).toHaveLength(0)

    const compiled = compileScript(descriptor, { id: 'sf-home-navigation' }).content
    expect(pluginDocsTemplate()).toContain('<sf-home-navigation></sf-home-navigation>')
    expect(compiled).toContain('categories: { type: Array, required: false, default: () => [] }')
    expect(compiled).toContain("selectedCategorySlug: { type: String, required: false, default: '' }")
    expect(compiled).toContain('totalTopics: { type: Number, required: false, default: 0 }')
  })

  test('category and tag pages reuse the V32 left-nav topic table shell', () => {
    const categoryPage = source('../../app/components/forum/SFCategoryShowPage.vue')
    const tagPage = source('../../app/components/forum/SFTagShowPage.vue')

    for (const page of [categoryPage, tagPage]) {
      expect(page).toContain('sforum-home')
      expect(page).toContain('sforum-home__layout')
      expect(page).toContain('navigation-mode="route"')
      expect(page).toContain('<SFHomeTopicRow')
      expect(page).toContain('data-sf-region="topic-list"')
      expect(page).not.toContain('sforum-home__topic-table')
      expect(page).not.toContain('sf-public-page')
      expect(page).not.toContain('bg-[#E6F4F1]')
    }

    expect(categoryPage).toContain('sforum-home__main sforum-content-column')
    expect(categoryPage).toContain('SFContentColumnFooter')

    // 标签详情页已对齐索引页三栏壳与右栏
    expect(tagPage).toContain('sforum-home__layout--with-right')
    expect(tagPage).toContain('data-layout="fullwidth-3col"')
    expect(tagPage).toContain('forum.component.tag_show')
    expect(tagPage).toContain(':show-categories="false"')
    expect(tagPage).toContain('SFTagShowRightRail')
    expect(tagPage).toContain('SFContentColumnFooter')
    expect(tagPage).toContain('<SFResponsivePublicSidebar')
    expect(tagPage).not.toContain('sforum-mobile-drawer--left')
    expect(tagPage).toContain('sforum-mobile-drawer--right')
  })

  test('keeps tag SSR data stable across HMR transitions and starts independent reads concurrently', () => {
    const tagPage = source('../../app/components/forum/SFTagShowPage.vue')

    expect(tagPage).toContain('await Promise.all([')
    expect(tagPage).toContain('const activeTags = computed(() => activeTagsData.value || [])')
    expect(tagPage).toContain('return value && Array.isArray(value.items) ? value : emptyTopicList()')
    expect(tagPage).toContain("const value = params ? i18n.t(key, params) : i18n.t(key)")
    expect(tagPage).not.toContain('activeTags.length')
    expect(tagPage).not.toContain('topics.length')
  })

  test('commits filters through the URL with a debounced search draft', () => {
    const page = homepageIsland()

    expect(page).toContain('parseForumHomeQuery')
    expect(page).toContain('buildForumHomeQuery')
    expect(page).toContain('forumHomeFeedKey')
    expect(page).toContain('const committedFilters = computed')
    expect(page).toContain('const searchDraft = ref')
    expect(page).toContain('const SEARCH_DEBOUNCE_MS = 300')
    expect(page).toContain('setTimeout')
    expect(page).toContain('SEARCH_DEBOUNCE_MS')
    expect(page).toContain('router.replace({')
    expect(page).toContain('path: surfacePath.value')
    expect(page).toContain('query: buildForumHomeQuery(nextFilters)')
    expect(page).toContain('function resetFilters()')
    expect(page).toContain('@select-category="selectMobileCategory"')
    expect(page).toContain('@click="selectTag(tag.slug)"')
  })

  test('preserves SSR hydration, stale-response, deduplication, and infinite-loading guards', () => {
    const page = homepageIsland()
    const feedReset = page.slice(
      page.indexOf('watch(activePageFeedKey'),
      page.indexOf('async function loadMoreTopics')
    )

    expect(page).toContain("useState<ForumTopicSummary[]>('forum-home-loaded-topics'")
    expect(page).toContain('() => topicList.value.items')
    expect(page).toContain('() => topicList.value.total')
    expect(page).toContain("'forum-home-loaded-feed-key'")
    expect(page).toContain('shouldIgnoreClientEmptyHydration')
    expect(page).toContain('isForumHomeRequestCurrent')
    expect(page).toContain('hasReachedForumHomeEnd')
    expect(page).toContain('IntersectionObserver')
    expect(page).toContain('parsePublicPage(route.query.page)')
    expect(page).toContain(':page-to="homePageTo"')
    expect(page).toContain('feedGeneration')
    expect(feedReset).toContain('feedGeneration += 1')
    expect(page).toContain('existingIds')
  })

  test('registers three-column homepage stylesheet tokens with right rail', () => {
    const config = hostConfig()
    const css = homepageCss()
    const theme = themeCss()
    const themePkgCss = source('../../../../extensions/builtin/themes/sforum-default/assets/theme.css')
    const themeHybridCss = source('../../../../extensions/builtin/themes/sforum-default/assets/hybrid-forum.css')
    const themeTokens = source('../../../../extensions/builtin/themes/sforum-default/assets/tokens.css')
    const pkg = themePackage()
    const rightRail = source('../../app/components/forum/SFHomeRightRail.vue')
    const page = homepageIsland()
    const row = topicRow()

    expect(config).toContain('sforum-home.css')
    expect(pkg).toContain('forum.home')
    expect(page).toContain('data-layout="fullwidth-3col"')
    expect(css).toContain('.sforum-home__layout--with-right')
    expect(css).toContain('var(--sf-public-right-rail-width)')
    expect(css).toContain('.sforum-home__right')
    expect(css).toContain('.sf-home-right-rail')
    // 列表行 BEM 已迁出：宿主 Tailwind + 主题 token，禁止双写
    expect(css).not.toContain('.sf-home-topic-row__chip')
    expect(css).not.toContain('.sforum-home__main-bar')
    expect(css).toContain('width: 100%')
    expect(css).not.toContain('sforum-home__hero')
    expect(theme).toContain('--sf-public-sidebar-width')
    expect(theme).toContain('--sf-public-right-rail-width')
    expect(theme).toContain('--sf-public-bg: #ffffff')
    expect(theme).toContain('--sf-public-shadow: none')
    expect(themePkgCss).toContain('--sf-public-bg: #ffffff')
    expect(themePkgCss).toContain('.sforum-home__layout--with-right')
    expect(themePkgCss).not.toContain('.sf-home-topic-row__chip--tone-0')
    expect(themeTokens).toContain('--sf-public-bg: #ffffff')
    expect(themeTokens).toContain('--sf-public-sidebar-width: 230px')
    expect(themeTokens).toContain('--sf-public-right-rail-width: 270px')
    expect(themeTokens).toContain('--sf-public-topbar-height: 58px')
    expect(pkg).toContain('assets/hybrid-forum.css')
    // 主色归站点 appearance；默认主题 L0 tokens 不得硬锁 --sf-accent*。
    expect(themeTokens).not.toContain('--sf-accent:')
    expect(themeTokens).not.toContain('#d94763')
    expect(themeTokens).toContain('.dark')
    expect(themeTokens).not.toContain('#3b6cf5')
    expect(themePkgCss).not.toContain('--sf-accent: #d94763')
    expect(themeHybridCss).not.toContain('--sf-accent: #d94763')
    expect(themeHybridCss).toContain('color-scheme: light dark')
    expect(theme).toContain('var(--sf-accent)')
    expect(theme).not.toContain('#d94763')
    expect(css).not.toContain('#d94763')
    expect(rightRail).toContain('hotTopics')
    expect(rightRail).toContain(':prefetch="false"')
    expect(rightRail).toContain('home.sidebar.hotThreads')
    expect(rightRail).toContain('home.sidebar.forumStats')
    expect(rightRail).toContain('useAuthSession')
    expect(rightRail).toContain('home.sidebar.welcomeTitle')
    expect(rightRail).toContain('home.rightRail.welcomeUserTitle')
    expect(rightRail).toContain('home.rightRail.welcomeUserSubtitle')
    expect(rightRail).toContain('rightRailWelcome')
    expect(rightRail).toContain("emit('select-tag'")
    expect(page).toContain("const feedSort = ref<'latest' | 'replies'>('latest')")
    expect(page).toContain('const displayTopics = computed(')
    expect(page).toContain("t('home.filter.mostReplies')")
    expect(page).toContain('i-lucide-sliders-horizontal')
    expect(page).toContain('v-for="topic in displayTopics"')
    expect(page).toContain("t('home.sidebar.drawerTitle')")
    expect(page).toContain("t('home.rightRail.drawerTitle')")
    expect(row).toContain('sf-home-topic-row__mobile-replies')
    expect(row).toContain('sf-home-topic-row__replies')
    expect(row).toContain('max-[720px]:grid-cols-[36px_minmax(0,1fr)]')
    // 不伪造参与者堆/点赞等 demo 专属 UI
    expect(rightRail).not.toContain('participants')
    expect(page).not.toContain('participants')
  })

  test('keeps query-bearing public pages out of unsafe shared payload caches', () => {
    const middleware = homeQueryCacheMiddleware()
    const config = hostConfig()

    expect(middleware).toContain('no-store')
    for (const route of ['/c/**', '/tags/**']) {
      expect(config).toContain(`'${route}': { cache: false }`)
    }
    expect(config).not.toContain("'/en/c/**'")
    expect(config).not.toContain("'/en/tags/**'")
    expect(config).toContain('const payloadExtractionEnabled = false')
    expect(config).toContain('payloadExtraction: payloadExtractionEnabled')
  })

  test('footer remains available via theme L1 and fail-closed host chrome', () => {
    const contentFooter = source('../../app/components/forum/SFContentColumnFooter.vue')

    expect(footer()).toContain('sf-footer')
    expect(contentFooter).toContain('<SFFooter')
    expect(contentFooter).toContain('margin-top: auto')
    expect(contentFooter).toContain('padding-top: 20px')
    expect(contentFooter).toContain('margin-left: -24px')
    expect(contentFooter).toContain('margin-right: -24px')
    expect(contentFooter).toContain('padding-left: 24px')
    expect(contentFooter).toContain('padding-right: 24px')
    expect(homepageIsland()).toContain('sforum-home__main sforum-content-column')
    expect(themeCss()).toContain('.sforum-content-column')
    expect(themeCss()).toContain('.sf-host-public-chrome--fullwidth-3col:has(.sforum-content-footer)')
    expect(defaultHomeTemplate()).toContain('<sf-footer>')
    expect(source('../../app/components/SFHostPublicChrome.vue')).toContain('<SFFooter')
    expect(defaultThemeHybridCss()).not.toContain('.sf-theme--default:not(.sf-page--not-found) .sf-footer')
    expect(defaultThemeHybridCss()).toContain('.sf-page.sf-theme--default.sf-theme-shell--fullwidth-3col > .sf-footer')
    expect(defaultThemeHybridCss()).toContain('.sforum-content-footer .sf-footer')
    expect(defaultThemeHybridCss()).toContain('display: none')
    expect(themeCss()).toContain('.sf-page.sf-theme--default > .sf-footer')
    expect(themeCss()).toContain('.sf-page.sf-theme--default.sf-theme-shell--fullwidth-3col > .sf-footer')
    expect(themeCss()).toContain('.sforum-content-footer')
    expect(themeCss()).toContain('.sf-page--not-found > .sf-footer')
  })

  test('desktop shell keeps center scrolling while long rails use page scroll', () => {
    const css = homepageCss()
    const hybrid = defaultThemeHybridCss()

    expect(css).toContain('height: calc(100vh - var(--sf-public-topbar-height))')
    // host chrome 与主题壳同 edge-inset，避免 moderation 等非主题页左右更窄
    expect(css).toContain('padding-left: var(--sf-public-edge-inset, 24px);')
    expect(css).toContain('padding-right: var(--sf-public-edge-inset, 24px);')
    expect(css).toContain('padding: 24px 24px 20px 28px;')
    expect(css).toContain('padding: 34px 28px;')
    expect(css).toContain('height: 40px;')
    expect(css).toContain('.sforum-home__main {\n    height: calc(100vh - var(--sf-public-topbar-height));\n    min-height: 0;\n    overflow-y: auto;')
    expect(css).toContain('.sforum-home__sidebar,\n  .sforum-home__right {\n    position: static;')
    expect(css).toContain('height: auto;\n    min-height: 0;\n    overflow: visible;')
    expect(hybrid).toContain('.sf-page.sf-theme--default.sf-theme-shell--fullwidth-3col')
    expect(hybrid).not.toContain('\n    height: 100vh;')
    expect(hybrid).toContain('padding: 0 18px;')
    expect(hybrid).toContain('.sforum-home__main,\n  .sforum-topic-page__main,\n  .sforum-notifications__main')
    expect(hybrid).toContain('overflow-y: auto')
    expect(hybrid).toContain('.sforum-home__sidebar,\n  .sforum-home__right,\n  .sforum-topic-page__sidebar')
    expect(hybrid).toContain('height: auto;\n    min-height: 0;\n    overflow: visible;')
    expect(themeCss()).toContain('已安装的旧默认主题')
    expect(themeCss()).toContain('.sf-page.sf-theme--default.sf-theme-shell--fullwidth-3col')
    expect(themeCss()).toContain('padding-top: 0')
    expect(themeCss()).toContain('padding-bottom: 0')
    expect(themeCss()).toContain('中栏独立滚动，长侧栏参与页面滚动')
    expect(themeCss()).toContain('overflow-y: auto')
  })
})
