import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const composer = () => source('../../app/components/forum/SFTopicComposerPage.vue')
const composerStyles = () => source('../../app/components/forum/SFTopicComposerPage.css')
const leftRail = () => source('../../app/components/forum/SFTopicComposerLeftRail.vue')
const rightRail = () => source('../../app/components/forum/SFTopicComposerRightRail.vue')
const categorySelect = () => source('../../app/components/forum/SFCategorySelect.vue')
const tagInput = () => source('../../app/components/forum/SFTagInput.vue')
const route = () => source('../../app/pages/topics/new.vue')
const themeTemplate = () => source('../../../../extensions/builtin/themes/sforum-default/templates/topic-create.html')
const themePackage = () => source('../../../../extensions/builtin/themes/sforum-default/theme.json')
const zh = () => JSON.parse(source('../../i18n/locales/zh-CN.json'))
const en = () => JSON.parse(source('../../i18n/locales/en-US.json'))

describe('default theme topic composer native flow', () => {
  test('stays inside Page Registry and Host island boundaries', () => {
    expect(route()).toContain('page="forum.topic.create"')
    expect(route()).toContain('<SFTopicComposerPage')
    expect(route()).toContain('requiresAuth: true')
    expect(themeTemplate()).toContain('data-page="forum.topic.create"')
    expect(themeTemplate()).toContain('<sf-topic-composer>')
    // 与首页/设置同轨：全宽三栏壳，topbar 与侧栏边距对齐
    expect(themeTemplate()).toContain('sf-theme-shell--fullwidth-3col')
    expect(themeTemplate()).toContain('data-layout="fullwidth-3col"')
    expect(themePackage()).toContain('"target": "forum.topic.create"')
    expect(composer()).toContain('data-sforum-island-body="forum.component.topic_composer"')
    expect(composer()).toContain('data-layout="fullwidth-3col"')
    expect(composerStyles()).toContain('--sf-public-edge-inset')
  })

  test('reuses real navigation, taxonomy data, limits, editor, and submit API', () => {
    const page = composer()

    expect(page).toContain('<SFHomeNavigation')
    expect(page).toContain('navigation-mode="route"')
    expect(page).toContain(':show-categories="false"')
    expect(page).toContain('forumApi.listCategoryGroups()')
    expect(page).toContain('forumApi.listTags()')
    expect(page).toContain("filter((tag) => tag.status === 'active')")
    expect(page).toContain('useForumContentLimits()')
    expect(page).toContain('validateTopicTitle')
    expect(page).toContain('validateTopicBody')
    expect(page).toContain('validateTagCount')
    expect(page).toContain('<LazySFEditor')
    expect(page).toContain('@content-change="onEditorContentChange"')
    expect(page).toContain('forumContentFromEditorPayload')
    expect(page).toContain('forumApi.createTopic({')
    expect(page).toContain('categorySlug: selectedCategorySlug.value || undefined')
    expect(page).toContain('tagSlugs: tagDraft.value.length ? tagDraft.value : undefined')
    expect(page).toContain('await navigateTo(localePath(forumTopicPath(created, topicUrlMode.value)))')
    expect(page).toContain('<SFCategorySelect')
    expect(page).toContain('<SFTagInput')
    expect(page).toContain(':categories="categories"')
    expect(page).toContain(':options="tagOptions"')
    // 分类选择器展示管理端 icon + iconColor
    expect(categorySelect()).toContain('categoryIconColor')
    expect(categorySelect()).toContain('categoryIconName')
    expect(categorySelect()).toContain('iconColor')
    expect(tagInput()).toContain('tagIconColor')
    expect(tagInput()).toContain('iconColor')
    expect(page).not.toContain('allow replies')
    expect(page).not.toContain('participants')
  })

  test('uses shared home shell with practical left tools and right summary rail', () => {
    const page = composer()
    const styles = composerStyles()
    const left = leftRail()
    const right = rightRail()

    expect(page).toContain('sforum-home sforum-topic-composer')
    expect(page).toContain('sforum-home__layout')
    expect(page).toContain('sforum-home__layout--with-right')
    expect(page).toContain('sforum-home__sidebar')
    expect(page).toContain('sforum-home__main sforum-topic-composer__main')
    expect(page).toContain('sforum-home__right')
    expect(page).toContain('<SFTopicComposerLeftRail')
    expect(page).toContain('<SFTopicComposerRightRail')
    expect(page).toContain('#after-navigation')
    expect(page).toContain('focusComposerField')
    expect(page).toContain('topic-composer-title-input')
    expect(page).toContain('id="topic-composer-body"')
    expect(page).toContain('sforum-topic-composer__dock')
    expect(page).toContain('<style scoped src="./SFTopicComposerPage.css"></style>')
    expect(page).toContain('sforum-mobile-drawer--left')
    expect(page).toContain('sforum-mobile-drawer--right')
    expect(page).toContain("t('home.sidebar.drawerTitle')")
    expect(page).toContain("t('common.close')")
    expect(page).toContain("t('composer.rightRail.open')")
    expect(page).toContain('i-lucide-panel-right')
    // 主列不再挂 mobile 类别下拉
    expect(page).not.toContain('mobile-only')
    expect(page).not.toContain('sforum-topic-composer__mobile-nav')
    expect(styles).toContain('position: fixed')
    // dock 与 topbar/三栏同轨：edge-inset + 侧栏宽
    expect(styles).toContain('var(--sf-public-edge-inset, 24px)')
    expect(styles).toContain('var(--sf-public-sidebar-width)')
    expect(styles).toContain('var(--sf-public-right-rail-width)')
    expect(styles).toContain('@media (max-width: 960px)')
    // 左栏：进度 / 草稿 / 要点，无类别树
    expect(left).toContain("t('composer.leftRail.progressTitle')")
    expect(left).toContain("t('composer.leftRail.actionsTitle')")
    expect(left).toContain("t('composer.leftRail.tipsTitle')")
    expect(left).toContain("t('composer.leftRail.saveDraft')")
    expect(left).toContain('focus-field')
    expect(left).toContain('save-draft')
    expect(left).not.toContain('forumCategoryPath')
    // 右栏卡片语言
    expect(right).toContain('sf-home-right-rail')
    expect(right).toContain('sf-home-right-rail__card')
    expect(right).toContain("t('composer.summary.title')")
    expect(right).toContain("t('composer.summary.actor')")
    // 发布摘要不再展示标题/标签（由表单与发布前检查承担）
    expect(right).not.toContain("t('composer.summary.tagCount'")
    expect(right).not.toContain("t('composer.summary.noTags')")
    expect(right).not.toContain("t('composer.summary.untitled')")
    expect(right).not.toContain('sforum-topic-composer__title-text')
    expect(right).not.toContain('sforum-topic-composer__title-meter')
    // 紧凑检查：无状态徽章；仅未就绪展开说明
    expect(right).toContain("t('composer.checks.heading')")
    expect(right).toContain("t('composer.rightRail.tip')")
    expect(right).toContain("t('composer.rightRail.checksProgress'")
    expect(right).toContain('is-ok')
    expect(right).toContain('is-todo')
    expect(right).toContain('is-filled')
    expect(right).toContain('is-flash')
    expect(right).toContain('sforum-topic-composer__meta-list')
    expect(right).toContain('sforum-topic-composer__check-text')
    expect(right).toContain('v-if="!item.ok"')
    expect(right).not.toContain('sforum-topic-composer__check-status')
    expect(right).not.toContain("t('composer.leftRail.statusReady')")
    expect(page).toContain(':title-max="limits.topicTitleMaxRunes"')
    expect(page).not.toContain(':title-count=')
    expect(page).not.toContain(':tag-count=')
  })

  test('right rail summary and checks are derived from live form state', () => {
    const page = composer()
    const right = rightRail()

    expect(page).toContain('const selectedCategory = computed')
    expect(page).toContain('const summaryCategory = computed')
    expect(page).toContain('const effectiveText = computed')
    expect(page).toContain('const validationState = computed')
    expect(page).toContain('const prePublishChecks = computed')
    expect(page).toContain('title.value.trim()')
    expect(page).toContain('bodyCheckText')
    expect(page).toContain('categoryCheckText')
    expect(page).toContain('tagCheckText')
    expect(page).toContain('tagPolicyLabel')
    expect(page).toContain(':checks="prePublishChecks"')
    expect(page).toContain(':category-name="summaryCategory?.name"')
    expect(right).toContain("t('composer.settings.permissionValue')")
    expect(right).toContain("t('composer.settings.limitValue'")
    expect(right).toContain("t('composer.rightRail.tip')")
  })

  test('keeps field errors, draft feedback, duplicate-submit protection, and permission denial', () => {
    const page = composer()

    expect(page).toContain('fieldErrors.value = apiErrorFields(error)')
    expect(page).toContain('fieldErrors.categorySlug')
    expect(page).toContain('fieldErrors.tagSlugs')
    expect(page).toContain('fieldErrors.content')
    expect(page).toContain('submitState.value === \'submitting\'')
    expect(page).toContain(':disabled="!canSubmit"')
    expect(page).toContain("created.status === 'pending'")
    expect(page).toContain('submittedForReview')
    expect(page).toContain('clearDraft()')
    expect(page).toContain("user.value?.id || user.value?.username || 'authenticated'")
    expect(page).toContain('sessionStorage.setItem(topicDraftKey.value')
    expect(page).toContain('sessionStorage.getItem(topicDraftKey.value)')
    expect(page).toContain('sessionStorage.removeItem(topicDraftKey.value)')
    expect(page).not.toContain('tagOptions.value.length > 0')
    expect(page).toContain("color: 'error'")
    expect(page).toContain('duration: 0')
    expect(page).toContain('beforeunload')
    expect(page).toContain('onBeforeRouteLeave')
    expect(page).toContain('window.confirm')
    expect(page).toContain('permissionDenied')
    expect(page).toContain('can(FORUM_PERMISSIONS.topicCreate)')
  })

  test('localizes the new native flow in zh-CN and en-US', () => {
    for (const locale of [zh(), en()]) {
      const c = locale.composer
      expect(c.draft.save).toBeTruthy()
      expect(c.draft.leaveConfirm).toBeTruthy()
      expect(c.summary.title).toBeTruthy()
      // 面向用户的权限说明，使用权限目录 label，不暴露原始 permission key
      expect(c.settings.permissionValue).not.toMatch(/topic\.(create|edit_)/)
      expect(c.settings.permissionValue.length).toBeGreaterThan(0)
      expect(c.settings.editPermissionValue).not.toMatch(/topic\.(create|edit_)/)
      expect(c.settings.editPermissionValue.length).toBeGreaterThan(0)
      expect(c.checks.heading).toBeTruthy()
      expect(c.checks.title.ready).toBeTruthy()
      expect(c.checks.body.ready).toBeTruthy()
      expect(c.checks.category.serverDefault).toBeTruthy()
      expect(c.checks.tags.optional).toBeTruthy()
      expect(c.rightRail.tip).toBeTruthy()
      expect(c.rightRail.open).toBeTruthy()
      expect(c.rightRail.checksProgress).toContain('{ready}')
      expect(c.rightRail.titleOverflowHint).toBeTruthy()
      expect(c.rightRail.titleStatus.empty).toBeTruthy()
      expect(c.rightRail.titleStatus.over).toBeTruthy()
      expect(c.rightRail.titleHint.short).toContain('{min}')
      expect(c.leftRail.progressTitle).toBeTruthy()
      expect(c.leftRail.actionsTitle).toBeTruthy()
      expect(c.leftRail.tipsTitle).toBeTruthy()
      expect(c.leftRail.saveDraft).toBeTruthy()
      expect(c.tagPolicy.controlled).toBeTruthy()
    }
  })
})
