import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

describe('default theme profile page B1 contract', () => {
  test('uses Page Registry, shared three-column shell, and forum navigation', () => {
    const page = source('../../app/components/profile/SFProfileShowPage.vue')
    const route = source('../../app/pages/u/[username].vue')
    const template = source('../../../../extensions/builtin/themes/sforum-default/templates/profile-show.html')

    expect(route).toContain('SFPageOutlet')
    expect(route).toContain('page="forum.profile.show"')
    expect(template).toContain('<sf-profile-page>')
    expect(template).toContain('data-page="forum.profile.show"')
    expect(page).toContain('data-layout="fullwidth-3col"')
    expect(page).toContain('sforum-home__layout')
    expect(page).toContain('sforum-home__layout--with-right')
    expect(page).toContain('sforum-home__sidebar')
    expect(page).toContain('sforum-home__main')
    expect(page).toContain('sforum-home__right')
    expect(page).toContain('<SFHomeNavigation')
    expect(page).toContain('navigation-mode="route"')
    expect(page).toContain('desktop-only')
    expect(page).not.toContain('mobile-only')
    expect(page).toContain('<SFResponsivePublicSidebar')
    expect(page).toContain('owner-id="forum.profile.show"')
    expect(page).not.toContain("useState<boolean>('forum-mobile-menu-open'")
    expect(page).toContain("useState<boolean>('forum-mobile-info-open'")
    expect(page).not.toContain('sforum-mobile-drawer sforum-mobile-drawer--left')
    expect(page).toContain('sforum-mobile-drawer sforum-mobile-drawer--right')
    expect(page).toContain('<SFProfileRightRail')
  })

  test('renders only real public profile/activity concepts', () => {
    const page = source('../../app/components/profile/SFProfileShowPage.vue')
    const rail = source('../../app/components/profile/SFProfileRightRail.vue')
    const apiTypes = source('../../app/composables/profile/useProfileApi.ts')
    const css = source('../../app/assets/css/sforum-profile.css')

    expect(apiTypes).toContain('activities: ProfileActivity[]')
    expect(page).toContain('groupProfileActivitiesByDate')
    expect(page).toContain("activity.kind === 'topic'")
    expect(page).toContain("activity.kind === 'topic' ?")
    expect(page).toContain(": 'i-lucide-message-circle-reply'")
    expect(page).toContain('profile.topicCount')
    expect(page).toContain('profile.commentCount')
    expect(page).toContain('profile.value?.recentTopics')
    expect(rail).toContain('recentTopics')
    expect(page).toContain("t('profile.editProfile')")
    expect(page).toContain('v-if="isSelf"')
    expect(css).toContain('.sf-profile-activity-day__head')
    expect(css).toContain('@media (max-width: 680px)')

    expect(page).not.toContain('onFollowClick')
    expect(page).not.toContain('messageComingSoon')
    expect(page).not.toContain('coverComingSoon')
    expect(page).not.toContain('featuredWorks')
    expect(page).not.toContain('followersCount')
    expect(page).not.toContain('followingCount')
    expect(page).not.toContain('likesCount')
    expect(page).not.toContain('sf-profile-cover')
    expect(page).not.toContain('sf-profile-work')
  })

  test('matches B1 chrome: section tabs, primary edit action, and intro meta fields', () => {
    const page = source('../../app/components/profile/SFProfileShowPage.vue')
    const rail = source('../../app/components/profile/SFProfileRightRail.vue')
    const css = source('../../app/assets/css/sforum-profile.css')

    expect(page).toContain('sf-profile-tabs')
    expect(page).toContain("t('profile.tabs.topics')")
    expect(page).toContain("t('profile.tabs.replies')")
    expect(page).toContain("t('profile.tabs.about')")
    expect(page).toContain("activeTab === 'about'")
    expect(page).toContain('profile.profile.location')
    expect(page).toContain('websiteHref')
    expect(page).toContain("t('profile.joinedOn'")
    expect(page).toContain('sf-button sf-button--primary')
    expect(page).toContain('sf-profile-edit-link')
    expect(page).toContain('sf-profile-share-button')
    expect(page).toContain('shareProfile')
    expect(css).toContain('.sf-profile-tabs')
    expect(css).toContain('.sf-profile-tab.is-active')
    expect(css).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(rail).toContain("t('profile.joinedOn'")
    expect(rail).toContain('profile.profile.location')
    expect(rail).toContain('profile.profile.websiteUrl')
  })

  test('loads profile activities through paginated API with load-more', () => {
    const page = source('../../app/components/profile/SFProfileShowPage.vue')
    const api = source('../../app/composables/profile/useProfileApi.ts')
    const css = source('../../app/assets/css/sforum-profile.css')

    expect(api).toContain('listPublicActivities')
    expect(api).toContain('/activities')
    expect(api).toContain('hasMore: boolean')
    expect(page).toContain('listPublicActivities')
    expect(page).toContain('loadMoreActivities')
    expect(page).toContain('showLoadMore')
    expect(page).toContain("t('profile.timeline.loadMore')")
    expect(css).toContain('.sf-profile-load-more')
  })
})
