import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { normalizeSiteDomain, siteDomainFromUrl } from '../../app/utils/settings/siteDomain'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = () => source('../../app/components/settings/SFProfileSettingsPage.vue')
const shell = () => source('../../app/components/settings/SFSettingsShell.vue')
const preview = () => source('../../app/components/settings/SFProfileSettingsPreview.vue')
const accountNav = () => source('../../app/components/settings/SFSettingsAccountNav.vue')
const styles = () => source('../../app/assets/css/sforum-profile-settings.css')
const chrome = () => source('../../app/assets/css/sforum-settings.css')
const route = () => source('../../app/pages/settings/profile.vue')
const themeTemplate = () => source('../../../../extensions/builtin/themes/sforum-default/templates/settings-profile.html')
const zhCN = () => JSON.parse(source('../../i18n/locales/zh-CN.json'))
const enUS = () => JSON.parse(source('../../i18n/locales/en-US.json'))

describe('profile settings canvas', () => {
  test('keeps Page Registry and default theme ownership boundaries intact', () => {
    expect(route()).toContain('SFPageOutlet')
    expect(route()).toContain('page="forum.settings.profile"')
    expect(route()).toContain('<SFProfileSettingsPage')
    expect(themeTemplate()).toContain('data-theme-owned="presentation"')
    expect(themeTemplate()).toContain('data-page="forum.settings.profile"')
    expect(themeTemplate()).toContain('<sf-profile-settings')
  })

  test('loads and saves profile fields plus the private default language', () => {
    const src = page()
    expect(src).toContain('profileApi.getMyProfile()')
    expect(src).toContain('profileApi.updateMyProfile({')
    expect(src).toContain('bio: draft.bio')
    expect(src).toContain('signature: draft.signature')
    expect(src).toContain('location: draft.location')
    expect(src).toContain('websiteUrl: draft.websiteUrl')
    expect(src).toContain('updateLanguage(draft.locale)')
    expect(src).toContain('v-model="draft.locale"')
    expect(src).not.toContain('company')
    expect(src).not.toContain('portfolio')
    expect(src).not.toContain('followers')
    expect(src).not.toContain('privacy')
  })

  test('uses the runtime website domain for the public profile path', () => {
    const src = page()
    expect(src).toContain('const { siteDomain, avatarSettings } = useWebOptions()')
    expect(src).toContain('`${siteDomain.value}/u/`')
    expect(src).toContain('{{ publicProfilePrefix }}')
    expect(src).not.toContain("t('profileSettings.profilePathPrefix')")
    expect(normalizeSiteDomain(' https://Forum.Example.com/// ')).toBe('Forum.Example.com')
    expect(siteDomainFromUrl('https://forum.example.com:8443/base')).toBe('forum.example.com:8443')
  })

  test('preserves avatar upload and removal through the real profile API', () => {
    const src = page()
    expect(src).toContain('const avatarAccept = computed')
    expect(src).toContain('can(FORUM_PERMISSIONS.attachmentUpload)')
    expect(src).toContain('const canUploadAvatar = computed')
    expect(src).toContain('avatarSettings.value.allowGif')
    expect(src).toContain('file.size > avatarSettings.value.maxSizeKb * 1024')
    expect(src).toContain("file.type === 'image/gif'")
    expect(src).toContain('profileApi.uploadAvatar(file)')
    expect(src).toContain('profileApi.deleteAvatar()')
    expect(src).toContain('syncAuthAvatar(updated)')
    expect(src).toContain(':disabled="!canUploadAvatar || avatarBusy"')
    expect(src).toContain(':loading="avatarBusy"')
  })

  test('renders the public preview from the local draft and marks unsaved edits', () => {
    const src = page()
    const previewSrc = preview()
    expect(src).toContain('const isDirty = computed')
    expect(src).toContain('function resetDraft()')
    expect(src).toContain("title: t('profileSettings.resetDone')")
    expect(src).toContain('draft.bio !== baseline.value.bio')
    expect(src).toContain('draft.location !== baseline.value.location')
    expect(src).toContain('publicWebsiteHref')
    expect(previewSrc).toContain('v-if="!dirty && websiteHref"')
    expect(previewSrc).toContain('profileSettings.preview.unsaved')
    expect(previewSrc).toContain("t('profile.joinedOn'")
    expect(src).not.toContain('data-preview-signature')
    expect(src).not.toContain("i-lucide-quote")
  })

  test('uses public three-column chrome aligned with home and notifications', () => {
    const src = page()
    const shellSrc = shell()
    const css = styles()
    const chromeCss = chrome()
    const nav = accountNav()
    expect(src).toContain('<SFSettingsShell')
    expect(src).toContain('active="profile"')
    expect(src).toContain('class="sforum-settings-profile"')
    expect(src).toContain('<SFProfileSettingsPreview')
    expect(src).toContain('<style src="~/assets/css/sforum-profile-settings.css" lang="css"></style>')
    expect(shellSrc).toContain('data-layout="fullwidth-3col"')
    expect(shellSrc).toContain('sforum-settings__layout')
    expect(shellSrc).toContain('<SFHomeNavigation')
    expect(shellSrc).toContain('navigation-mode="route"')
    expect(shellSrc).toContain(':show-categories="false"')
    expect(shellSrc).toContain('<SFSettingsAccountNav')
    expect(shellSrc).toContain('<SFResponsivePublicSidebar')
    expect(shellSrc).toContain('owner-id="forum.settings"')
    expect(shellSrc).not.toContain("useState<boolean>('forum-mobile-menu-open'")
    expect(shellSrc).toContain("useState<boolean>('forum-mobile-info-open'")
    expect(shellSrc).not.toContain('@click="mobileInfoOpen = true"')
    expect(shellSrc).not.toContain('@click="openMobileMenu"')
    expect(shellSrc).toContain('sforum-mobile-drawer__backdrop')
    expect(shellSrc).not.toContain('sforum-mobile-drawer sforum-mobile-drawer--left')
    expect(shellSrc).toContain('sforum-mobile-drawer sforum-mobile-drawer--right')
    expect(shellSrc).toContain('<style src="~/assets/css/sforum-settings.css" lang="css"></style>')
    expect(chromeCss).toContain('grid-template-columns: var(--sf-public-sidebar-width) minmax(0, 1fr) var(--sf-public-right-rail-width)')
    expect(chromeCss).toMatch(/\.sforum-settings__main\s*\{[^}]*background: var\(--sf-public-surface\);/s)
    expect(chromeCss).toContain('@media (max-width: 1100px)')
    expect(chromeCss).toContain('@media (max-width: 980px)')
    expect(css).toContain('sforum-settings-profile__form')
    expect(nav).toContain("localePath('/settings/profile')")
    expect(nav).toContain("localePath('/settings/login-methods')")
    expect(nav).toContain("localePath('/settings/password')")
    expect(nav).toContain("localePath('/settings/security')")
    expect(nav).toContain("localePath('/settings/tokens')")
    expect(src).not.toContain('ssr: false')
    expect(src).not.toContain('layout: false')
    expect(src).not.toContain('sf-profile-settings-canvas__layout')
  })

  test('uses the active appearance color for successful profile actions', () => {
    const src = page()
    expect(src.match(/color: 'primary'/g)?.length).toBe(3)
    expect(src).not.toContain("color: 'success'")
  })

  test('keeps i18n complete for the canvas, preview, and visibility copy', () => {
    for (const messages of [zhCN(), enUS()]) {
      const copy = messages.profileSettings
      expect(copy.canvasTitle).toBeTruthy()
      expect(copy.sections.identity).toBeTruthy()
      expect(copy.sections.story).toBeTruthy()
      expect(copy.sections.links).toBeTruthy()
      expect(copy.preview.unsaved).toBeTruthy()
      expect(copy.preview.open).toBeTruthy()
      expect(copy.scope.publicFields).toBeTruthy()
      expect(copy.scope.privateFields).toBeTruthy()
      expect(copy.signaturePublicHint).toBeTruthy()
      expect(copy.avatarUploadPermissionDenied).toBeTruthy()
      expect(copy.resetChanges).toBeTruthy()
      expect(copy.resetDone).toBeTruthy()
      expect(copy.defaultLanguage).toBeTruthy()
      expect(copy.defaultLanguageHint).toBeTruthy()
      expect(copy.saved).toBeTruthy()
      expect(copy.saveFailed).toBeTruthy()
      expect(messages.accountSecurity.rail.devicesTitle).toBeTruthy()
      expect(messages.accountSecurity.rail.tokens).toBeTruthy()
      expect(messages.localPasswordSettings.title).toBeTruthy()
      expect(messages.localPasswordSettings.rail.passwordTitle).toBeTruthy()
    }
  })
})
