import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const composer = () => source('../app/components/SFTopicComposerPage.vue')
const composerStyles = () => source('../app/components/SFTopicComposerPage.css')
const route = () => source('../app/pages/topics/new.vue')
const themeTemplate = () => source('../../../extensions/builtin/themes/sforum-default/templates/topic-create.html')
const themePackage = () => source('../../../extensions/builtin/themes/sforum-default/theme.json')
const zh = () => JSON.parse(source('../i18n/locales/zh-CN.json'))
const en = () => JSON.parse(source('../i18n/locales/en-US.json'))

describe('default theme topic composer native flow', () => {
  test('stays inside Page Registry and Host island boundaries', () => {
    expect(route()).toContain('page="forum.topic.create"')
    expect(route()).toContain('<SFTopicComposerPage')
    expect(route()).toContain('requiresAuth: true')
    expect(themeTemplate()).toContain('data-page="forum.topic.create"')
    expect(themeTemplate()).toContain('<sf-topic-composer>')
    expect(themePackage()).toContain('"target": "forum.topic.create"')
    expect(composer()).toContain('data-sforum-island-body="forum.component.topic_composer"')
    expect(composer()).toContain('data-layout="fullwidth-3col"')
  })

  test('reuses real navigation, taxonomy data, limits, editor, and submit API', () => {
    const page = composer()

    expect(page).toContain('<SFHomeNavigation')
    expect(page).toContain('navigation-mode="route"')
    expect(page).toContain('forumApi.listCategoryGroups()')
    expect(page).toContain('forumApi.listTags()')
    expect(page).toContain("filter((tag) => tag.status === 'active')")
    expect(page).toContain('useForumContentLimits()')
    expect(page).toContain('validateTopicTitle')
    expect(page).toContain('validateTopicBody')
    expect(page).toContain('validateTagCount')
    expect(page).toContain('<LazySFEditor')
    expect(page).toContain('@content-change="onEditorContentChange"')
    expect(page).toContain('forumContentFromEditorPayload')
    expect(page).toContain('forumApi.createTopic({')
    expect(page).toContain('categorySlug: selectedCategorySlug.value || undefined')
    expect(page).toContain('tagSlugs: tagDraft.value.length ? tagDraft.value : undefined')
    expect(page).toContain('await navigateTo(localePath(forumTopicPath(created, topicUrlMode.value)))')
    expect(page).not.toContain('allow replies')
    expect(page).not.toContain('participants')
  })

  test('renders native three-column composer with a fixed publish dock and mobile collapse', () => {
    const page = composer()
    const styles = composerStyles()

    expect(page).toContain('sforum-topic-composer__layout--with-right')
    expect(page).toContain('sforum-topic-composer__sidebar')
    expect(page).toContain('sforum-topic-composer__main')
    expect(page).toContain('sforum-topic-composer__right')
    expect(page).toContain('sforum-topic-composer__dock')
    expect(page).toContain('<style scoped src="./SFTopicComposerPage.css"></style>')
    expect(styles).toContain('position: fixed')
    expect(styles).toContain('left: var(--sf-public-sidebar-width)')
    expect(styles).toContain('right: var(--sf-public-right-rail-width)')
    expect(styles).toContain('padding: 18px clamp(16px, 4vw, 56px) 112px')
    expect(styles).toContain('@media (max-width: 960px)')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(page).toContain('sforum-topic-composer__mobile-nav')
    expect(page).toContain('sforum-mobile-drawer--left')
    expect(page).toContain('sforum-mobile-drawer--right')
  })

  test('right rail summary and checks are derived from live form state', () => {
    const page = composer()

    expect(page).toContain('const selectedCategory = computed')
    expect(page).toContain('const summaryCategory = computed')
    expect(page).toContain('const activeTagMap = computed')
    expect(page).toContain('const effectiveText = computed')
    expect(page).toContain('const validationState = computed')
    expect(page).toContain('const prePublishChecks = computed')
    expect(page).toContain('title.value.trim()')
    expect(page).toContain('bodyCheckText')
    expect(page).toContain('categoryCheckText')
    expect(page).toContain('tagCheckText')
    expect(page).toContain('tagPolicyLabel')
    expect(page).toContain("t('composer.settings.permissionValue')")
    expect(page).toContain("t('composer.settings.limitValue'")
    expect(page).toContain("t('composer.rightRail.tip')")
  })

  test('keeps field errors, draft feedback, duplicate-submit protection, and permission denial', () => {
    const page = composer()

    expect(page).toContain('fieldErrors.value = apiErrorFields(error)')
    expect(page).toContain('fieldErrors.categorySlug')
    expect(page).toContain('fieldErrors.tagSlugs')
    expect(page).toContain('fieldErrors.content')
    expect(page).toContain('submitState.value === \'submitting\'')
    expect(page).toContain(':disabled="!canSubmit"')
    expect(page).toContain("created.status === 'pending'")
    expect(page).toContain('submittedForReview')
    expect(page).toContain('clearDraft()')
    expect(page).toContain("user.value?.id || user.value?.username || 'authenticated'")
    expect(page).toContain('sessionStorage.setItem(topicDraftKey.value')
    expect(page).toContain('sessionStorage.getItem(topicDraftKey.value)')
    expect(page).toContain('sessionStorage.removeItem(topicDraftKey.value)')
    expect(page).not.toContain('tagOptions.value.length > 0')
    expect(page).toContain("color: 'error'")
    expect(page).toContain('duration: 0')
    expect(page).toContain('beforeunload')
    expect(page).toContain('onBeforeRouteLeave')
    expect(page).toContain('window.confirm')
    expect(page).toContain('permissionDenied')
    expect(page).toContain('can(FORUM_PERMISSIONS.topicCreate)')
  })

  test('localizes the new native flow in zh-CN and en-US', () => {
    for (const locale of [zh(), en()]) {
      const c = locale.composer
      expect(c.draft.save).toBeTruthy()
      expect(c.draft.leaveConfirm).toBeTruthy()
      expect(c.summary.title).toBeTruthy()
      expect(c.settings.permissionValue).toContain('topic.create')
      expect(c.checks.heading).toBeTruthy()
      expect(c.checks.title.ready).toBeTruthy()
      expect(c.checks.body.ready).toBeTruthy()
      expect(c.checks.category.serverDefault).toBeTruthy()
      expect(c.checks.tags.optional).toBeTruthy()
      expect(c.rightRail.tip).toBeTruthy()
      expect(c.tagPolicy.controlled).toBeTruthy()
    }
  })
})
