// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_key)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID        int64
	PermissionKey string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionKey)
	return err
}

const anyUserExists = `-- name: AnyUserExists :one
SELECT EXISTS (SELECT 1 FROM users LIMIT 1)::boolean
`

func (q *Queries) AnyUserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyUserExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findRegistrationConflicts = `-- name: FindRegistrationConflicts :one
SELECT
  EXISTS (SELECT 1 FROM users WHERE username_lower = lower($1))::boolean AS username_taken,
  EXISTS (SELECT 1 FROM users WHERE email_lower = lower($2))::boolean AS email_taken
`

type FindRegistrationConflictsParams struct {
	Username string
	Email    string
}

type FindRegistrationConflictsRow struct {
	UsernameTaken bool
	EmailTaken    bool
}

func (q *Queries) FindRegistrationConflicts(ctx context.Context, arg FindRegistrationConflictsParams) (FindRegistrationConflictsRow, error) {
	row := q.db.QueryRow(ctx, findRegistrationConflicts, arg.Username, arg.Email)
	var i FindRegistrationConflictsRow
	err := row.Scan(&i.UsernameTaken, &i.EmailTaken)
	return i, err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (actor_user_id, target_user_id, action, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateAuditEventParams struct {
	ActorUserID  pgtype.Int8
	TargetUserID pgtype.Int8
	Action       string
	Metadata     []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ActorUserID,
		arg.TargetUserID,
		arg.Action,
		arg.Metadata,
	)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (key, alias, description, is_system, is_default, is_deletable, is_enabled)
VALUES ($1, $2, $3, FALSE, FALSE, TRUE, TRUE)
RETURNING id, key, alias, description, is_system, is_default, is_deletable, is_enabled
`

type CreateRoleParams struct {
	Key         string
	Alias       string
	Description string
}

type CreateRoleRow struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Key, arg.Alias, arg.Description)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Alias,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.IsDeletable,
		&i.IsEnabled,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, username_lower, email, email_lower, display_name, locale, is_initial_super_admin)
VALUES ($1, lower($1), $2, lower($2), $3, $4, $5)
RETURNING id, username, display_name, locale, status, is_initial_super_admin
`

type CreateUserParams struct {
	Username            string
	Email               string
	DisplayName         string
	Locale              string
	IsInitialSuperAdmin bool
}

type CreateUserRow struct {
	ID                  int64
	Username            string
	DisplayName         string
	Locale              string
	Status              string
	IsInitialSuperAdmin bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Locale,
		arg.IsInitialSuperAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.IsInitialSuperAdmin,
	)
	return i, err
}

const createUserCredential = `-- name: CreateUserCredential :exec
INSERT INTO user_credentials (user_id, password_hash)
VALUES ($1, $2)
`

type CreateUserCredentialParams struct {
	UserID       int64
	PasswordHash string
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) error {
	_, err := q.db.Exec(ctx, createUserCredential, arg.UserID, arg.PasswordHash)
	return err
}

const deleteRoleByKey = `-- name: DeleteRoleByKey :exec
DELETE FROM roles
WHERE key = $1 AND is_deletable = TRUE AND is_system = FALSE
`

func (q *Queries) DeleteRoleByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteRoleByKey, key)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT id, username, display_name, locale, status, is_initial_super_admin
FROM users
WHERE id = $1
`

type GetCurrentUserRow struct {
	ID                  int64
	Username            string
	DisplayName         string
	Locale              string
	Status              string
	IsInitialSuperAdmin bool
}

func (q *Queries) GetCurrentUser(ctx context.Context, id int64) (GetCurrentUserRow, error) {
	row := q.db.QueryRow(ctx, getCurrentUser, id)
	var i GetCurrentUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.IsInitialSuperAdmin,
	)
	return i, err
}

const getDefaultRole = `-- name: GetDefaultRole :one
SELECT id, key, alias, description, is_system, is_default, is_deletable, is_enabled
FROM roles
WHERE is_default = TRUE AND is_enabled = TRUE
`

type GetDefaultRoleRow struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
}

func (q *Queries) GetDefaultRole(ctx context.Context) (GetDefaultRoleRow, error) {
	row := q.db.QueryRow(ctx, getDefaultRole)
	var i GetDefaultRoleRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Alias,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.IsDeletable,
		&i.IsEnabled,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT id, key, alias, description, is_system, is_default, is_deletable, is_enabled
FROM roles
WHERE key = $1
`

type GetRoleByKeyRow struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
}

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (GetRoleByKeyRow, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, key)
	var i GetRoleByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Alias,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.IsDeletable,
		&i.IsEnabled,
	)
	return i, err
}

const getUserCredentialByLogin = `-- name: GetUserCredentialByLogin :one
SELECT users.id, users.username, users.display_name, users.locale, users.status, users.is_initial_super_admin, user_credentials.password_hash
FROM users
JOIN user_credentials ON user_credentials.user_id = users.id
WHERE users.username_lower = lower($1) OR users.email_lower = lower($1)
`

type GetUserCredentialByLoginRow struct {
	ID                  int64
	Username            string
	DisplayName         string
	Locale              string
	Status              string
	IsInitialSuperAdmin bool
	PasswordHash        string
}

func (q *Queries) GetUserCredentialByLogin(ctx context.Context, lower string) (GetUserCredentialByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByLogin, lower)
	var i GetUserCredentialByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.IsInitialSuperAdmin,
		&i.PasswordHash,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, key, alias, description, is_system, is_default, is_deletable, is_enabled
FROM roles
ORDER BY is_system DESC, key ASC
`

type ListRolesRow struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Alias,
			&i.Description,
			&i.IsSystem,
			&i.IsDefault,
			&i.IsDeletable,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
WITH role_permission_keys AS (
  SELECT DISTINCT permissions.key
  FROM user_roles
  JOIN roles ON roles.id = user_roles.role_id
  JOIN role_permissions ON role_permissions.role_id = roles.id
  JOIN permissions ON permissions.key = role_permissions.permission_key
  WHERE user_roles.user_id = $1 AND roles.is_enabled = TRUE
),
allowed_permission_keys AS (
  SELECT permission_key AS key
  FROM user_permission_overrides
  WHERE user_id = $1 AND effect = 'allow'
),
denied_permission_keys AS (
  SELECT permission_key AS key
  FROM user_permission_overrides
  WHERE user_id = $1 AND effect = 'deny'
),
candidate_permission_keys AS (
  SELECT key FROM role_permission_keys
  UNION
  SELECT key FROM allowed_permission_keys
)
SELECT candidate_permission_keys.key
FROM candidate_permission_keys
WHERE NOT EXISTS (
  SELECT 1
  FROM denied_permission_keys
  WHERE denied_permission_keys.key = candidate_permission_keys.key
)
ORDER BY candidate_permission_keys.key
`

func (q *Queries) ListUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleKeys = `-- name: ListUserRoleKeys :many
SELECT roles.key
FROM user_roles
JOIN roles ON roles.id = user_roles.role_id
WHERE user_roles.user_id = $1 AND roles.is_enabled = TRUE
ORDER BY roles.key
`

func (q *Queries) ListUserRoleKeys(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoleKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleAlias = `-- name: UpdateRoleAlias :one
UPDATE roles
SET alias = $2, description = $3, updated_at = now()
WHERE key = $1
RETURNING id, key, alias, description, is_system, is_default, is_deletable, is_enabled
`

type UpdateRoleAliasParams struct {
	Key         string
	Alias       string
	Description string
}

type UpdateRoleAliasRow struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
}

func (q *Queries) UpdateRoleAlias(ctx context.Context, arg UpdateRoleAliasParams) (UpdateRoleAliasRow, error) {
	row := q.db.QueryRow(ctx, updateRoleAlias, arg.Key, arg.Alias, arg.Description)
	var i UpdateRoleAliasRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Alias,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.IsDeletable,
		&i.IsEnabled,
	)
	return i, err
}
