// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           int64
	ActorUserID  pgtype.Int8
	TargetUserID pgtype.Int8
	Action       string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

type Permission struct {
	Key         string
	Module      string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Role struct {
	ID          int64
	Key         string
	Alias       string
	Description string
	IsSystem    bool
	IsDefault   bool
	IsDeletable bool
	IsEnabled   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID        int64
	PermissionKey string
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID                  int64
	Username            string
	UsernameLower       string
	Email               string
	EmailLower          string
	DisplayName         string
	Locale              string
	Status              string
	IsInitialSuperAdmin bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type UserCredential struct {
	UserID            int64
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	CreatedAt pgtype.Timestamptz
}
