// Code generated by scripts/v3-catalog/generate.mjs. DO NOT EDIT.

export type AdminSurfacePlacement = {
  id: string
  contractVersion: string
  route: string
}

export const adminSurfacePlacements = [
  { id: "core.component.page.admin", contractVersion: "sforum.component.page.admin@1", route: "/admin" },
  { id: "core.component.page.admin.attachments", contractVersion: "sforum.component.page.admin.attachments@1", route: "/admin/attachments" },
  { id: "core.component.page.admin.database", contractVersion: "sforum.component.page.admin.database@1", route: "/admin/database" },
  { id: "core.component.page.admin.entity.meta", contractVersion: "sforum.component.page.admin.entity.meta@1", route: "/admin/entity-meta" },
  { id: "core.component.page.admin.extensions", contractVersion: "sforum.component.page.admin.extensions@1", route: "/admin/extensions" },
  { id: "core.component.page.admin.extensions.contributions", contractVersion: "sforum.component.page.admin.extensions.contributions@1", route: "/admin/extensions/contributions" },
  { id: "core.component.page.admin.extensions.events", contractVersion: "sforum.component.page.admin.extensions.events@1", route: "/admin/extensions/events" },
  { id: "core.component.page.admin.extensions.extension.id.pages.page.path", contractVersion: "sforum.component.page.admin.extensions.extension.id.pages.page.path@1", route: "/admin/extensions/:extensionId/pages/:pagePath*" },
  { id: "core.component.page.admin.extensions.pages", contractVersion: "sforum.component.page.admin.extensions.pages@1", route: "/admin/extensions/pages" },
  { id: "core.component.page.admin.extensions.plugins", contractVersion: "sforum.component.page.admin.extensions.plugins@1", route: "/admin/extensions/plugins" },
  { id: "core.component.page.admin.extensions.provider.slots", contractVersion: "sforum.component.page.admin.extensions.provider.slots@1", route: "/admin/extensions/provider-slots" },
  { id: "core.component.page.admin.extensions.route.providers", contractVersion: "sforum.component.page.admin.extensions.route.providers@1", route: "/admin/extensions/route-providers" },
  { id: "core.component.page.admin.extensions.settings", contractVersion: "sforum.component.page.admin.extensions.settings@1", route: "/admin/extensions/settings" },
  { id: "core.component.page.admin.extensions.store", contractVersion: "sforum.component.page.admin.extensions.store@1", route: "/admin/extensions/store" },
  { id: "core.component.page.admin.extensions.store.plugins", contractVersion: "sforum.component.page.admin.extensions.store.plugins@1", route: "/admin/extensions/store/plugins" },
  { id: "core.component.page.admin.extensions.store.themes", contractVersion: "sforum.component.page.admin.extensions.store.themes@1", route: "/admin/extensions/store/themes" },
  { id: "core.component.page.admin.extensions.themes", contractVersion: "sforum.component.page.admin.extensions.themes@1", route: "/admin/extensions/themes" },
  { id: "core.component.page.admin.forum.categories", contractVersion: "sforum.component.page.admin.forum.categories@1", route: "/admin/forum/categories" },
  { id: "core.component.page.admin.forum.settings", contractVersion: "sforum.component.page.admin.forum.settings@1", route: "/admin/forum/settings" },
  { id: "core.component.page.admin.forum.tags", contractVersion: "sforum.component.page.admin.forum.tags@1", route: "/admin/forum/tags" },
  { id: "core.component.page.admin.jobs", contractVersion: "sforum.component.page.admin.jobs@1", route: "/admin/jobs" },
  { id: "core.component.page.admin.moderation", contractVersion: "sforum.component.page.admin.moderation@1", route: "/admin/moderation" },
  { id: "core.component.page.admin.permissions", contractVersion: "sforum.component.page.admin.permissions@1", route: "/admin/permissions" },
  { id: "core.component.page.admin.personalization", contractVersion: "sforum.component.page.admin.personalization@1", route: "/admin/personalization" },
  { id: "core.component.page.admin.roles", contractVersion: "sforum.component.page.admin.roles@1", route: "/admin/roles" },
  { id: "core.component.page.admin.schedules", contractVersion: "sforum.component.page.admin.schedules@1", route: "/admin/schedules" },
  { id: "core.component.page.admin.search", contractVersion: "sforum.component.page.admin.search@1", route: "/admin/search" },
  { id: "core.component.page.admin.seo", contractVersion: "sforum.component.page.admin.seo@1", route: "/admin/seo" },
  { id: "core.component.page.admin.settings", contractVersion: "sforum.component.page.admin.settings@1", route: "/admin/settings" },
  { id: "core.component.page.admin.settings.avatar", contractVersion: "sforum.component.page.admin.settings.avatar@1", route: "/admin/settings/avatar" },
  { id: "core.component.page.admin.settings.features", contractVersion: "sforum.component.page.admin.settings.features@1", route: "/admin/settings/features" },
  { id: "core.component.page.admin.settings.mail", contractVersion: "sforum.component.page.admin.settings.mail@1", route: "/admin/settings/mail" },
  { id: "core.component.page.admin.site.chrome", contractVersion: "sforum.component.page.admin.site.chrome@1", route: "/admin/site-chrome" },
  { id: "core.component.page.admin.users", contractVersion: "sforum.component.page.admin.users@1", route: "/admin/users" },
  { id: "core.component.page.admin.webhooks", contractVersion: "sforum.component.page.admin.webhooks@1", route: "/admin/webhooks" },
] as const satisfies readonly AdminSurfacePlacement[]
