package migrator

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/zhuchunshu/sforum/apps/api/database/coreauthority"
)

func TestCoreMigrationAuthorityConvergesExistingDatabaseAndRepeats(t *testing.T) {
	fixture := newCoreAuthorityTestDatabase(t)
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	db, err := openMigrationSQLDatabase(fixture.databaseURL, "")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	for _, statement := range []string{
		`CREATE TABLE public.goose_db_version (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`,
		`CREATE TABLE public.core_authority_probe (id BIGINT PRIMARY KEY)`,
		`CREATE TYPE public.core_authority_state AS ENUM ('ready')`,
		`CREATE FUNCTION public.core_authority_probe_count() RETURNS BIGINT LANGUAGE SQL AS 'SELECT count(*) FROM public.core_authority_probe'`,
		`CREATE SCHEMA sforum_core_v1 AUTHORIZATION CURRENT_USER`,
		`CREATE VIEW sforum_core_v1.core_authority_probe AS SELECT id FROM public.core_authority_probe`,
		`CREATE TYPE public.river_job_state AS ENUM ('available')`,
		`CREATE TABLE public.river_job (id BIGINT PRIMARY KEY, state public.river_job_state NOT NULL)`,
		`CREATE FUNCTION public.river_job_state_in_bitmask(public.river_job_state) RETURNS BOOLEAN LANGUAGE SQL AS 'SELECT TRUE'`,
		`CREATE SCHEMA sforum_ext_s_fixture`,
		`CREATE TABLE sforum_ext_s_fixture.plugin_data (id BIGINT PRIMARY KEY)`,
	} {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("prepare legacy ownership fixture: %v", err)
		}
	}

	authority, err := prepareCoreMigrationAuthority(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	if authority.DatabaseName != fixture.databaseName || authority.SessionRole != fixture.sessionRole ||
		authority.OwnerRole != fixture.ownerRole {
		t.Fatalf("Core authority = %#v, fixture = %#v", authority, fixture)
	}
	assertCoreAuthorityOwner(t, ctx, db, "schema", "public", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "schema", "sforum_core_v1", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.goose_db_version", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.core_authority_probe", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "sforum_core_v1.core_authority_probe", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "routine", "public.core_authority_probe_count", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "type", "public.core_authority_state", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.river_job", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "routine", "public.river_job_state_in_bitmask", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "type", "public.river_job_state", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "schema", "sforum_ext_s_fixture", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "sforum_ext_s_fixture.plugin_data", fixture.sessionRole)
	assertCoreAuthorityMembership(t, ctx, db, fixture)
	if err := configureCoreMigrationDatabaseCreate(ctx, db, authority, true); err != nil {
		t.Fatal(err)
	}

	repeated, err := prepareCoreMigrationAuthority(ctx, db)
	if err != nil || repeated != authority {
		t.Fatalf("repeat Core ownership convergence = %#v, %v", repeated, err)
	}
	assertCoreAuthorityDatabaseCreateRevoked(t, ctx, db, fixture.ownerRole)
	migrationDB, err := openMigrationSQLDatabase(fixture.databaseURL, fixture.ownerRole)
	if err != nil {
		t.Fatal(err)
	}
	defer migrationDB.Close()
	if err := migrationDB.PingContext(ctx); err != nil {
		t.Fatal(err)
	}
	if err := validateCoreMigrationConnection(ctx, migrationDB, authority); err != nil {
		t.Fatal(err)
	}
}

func TestCoreMigrationAuthorityConvergesPostgres17CreatorMembership(t *testing.T) {
	fixture := newCoreAuthorityNonSuperTestDatabase(t)
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	db := openCoreAuthorityFixtureDB(t, fixture)
	defer db.Close()

	var serverVersion int
	var superuser, createRole bool
	if err := db.QueryRowContext(ctx, `
		SELECT current_setting('server_version_num')::INTEGER, rolsuper, rolcreaterole
		FROM pg_roles WHERE rolname = current_user
	`).Scan(&serverVersion, &superuser, &createRole); err != nil {
		t.Fatal(err)
	}
	if serverVersion < 170000 {
		t.Skipf("PostgreSQL 17 creator membership semantics require PostgreSQL 17+, got %d", serverVersion)
	}
	if superuser || !createRole {
		t.Fatalf("fixture login attributes = superuser:%t createrole:%t", superuser, createRole)
	}

	authority, err := prepareCoreMigrationAuthority(ctx, db)
	if err != nil {
		t.Fatalf("converge fresh non-super Core owner: %v", err)
	}
	if authority.SessionRole != fixture.sessionRole || authority.OwnerRole != fixture.ownerRole {
		t.Fatalf("Core authority = %#v, fixture = %#v", authority, fixture)
	}
	firstRows := assertCoreAuthorityCreatorMembership(t, ctx, db, fixture)
	assertCoreAuthorityDatabaseCreateRevoked(t, ctx, db, fixture.ownerRole)

	repeated, err := prepareCoreMigrationAuthority(ctx, db)
	if err != nil || repeated != authority {
		t.Fatalf("repeat non-super Core owner convergence = %#v, %v", repeated, err)
	}
	if repeatedRows := assertCoreAuthorityCreatorMembership(t, ctx, db, fixture); repeatedRows != firstRows {
		t.Fatalf("repeat Core owner membership rows = %d, want stable %d", repeatedRows, firstRows)
	}
}

func TestCoreMigratorFreshDatabaseOwnsGooseButNotRiver(t *testing.T) {
	fixture := newCoreAuthorityTestDatabase(t)
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	if err := Up(ctx, Config{DatabaseURL: fixture.databaseURL, TargetCoreVersion: "1.0.0"}); err != nil {
		t.Fatalf("migrate fresh database with Core owner: %v", err)
	}
	if err := Up(ctx, Config{DatabaseURL: fixture.databaseURL, TargetCoreVersion: "1.0.0"}); err != nil {
		t.Fatalf("repeat fresh Core-owner migration: %v", err)
	}
	db, err := openMigrationSQLDatabase(fixture.databaseURL, "")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	assertCoreAuthorityOwner(t, ctx, db, "schema", "public", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "schema", "sforum_core_v1", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "schema", coreDatabaseExtensionsSchema, fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.goose_db_version", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.goose_lock", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.users", fixture.ownerRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.river_job", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "relation", "public.river_migration", fixture.sessionRole)
	assertCoreAuthorityOwner(t, ctx, db, "extension", "pg_trgm", fixture.sessionRole)
	assertCoreAuthorityMembership(t, ctx, db, fixture)
	assertCoreAuthorityDatabaseCreateRevoked(t, ctx, db, fixture.ownerRole)
}

func TestCoreMigrationAuthorityRejectsUnsafeRoleMembershipAndForeignOwner(t *testing.T) {
	t.Run("unsafe owner role", func(t *testing.T) {
		fixture := newCoreAuthorityTestDatabase(t)
		ctx := context.Background()
		db := openCoreAuthorityFixtureDB(t, fixture)
		defer db.Close()
		role := pgx.Identifier{fixture.ownerRole}.Sanitize()
		if _, err := db.ExecContext(ctx, `CREATE ROLE `+role+` LOGIN`); err != nil {
			t.Fatal(err)
		}
		if _, err := prepareCoreMigrationAuthority(ctx, db); !errors.Is(err, ErrCoreAuthorityConflict) {
			t.Fatalf("unsafe Core owner role error = %v", err)
		}
		assertCoreAuthorityOwner(t, ctx, db, "schema", "public", "pg_database_owner")
	})

	t.Run("membership cannot SET", func(t *testing.T) {
		fixture := newCoreAuthorityTestDatabase(t)
		ctx := context.Background()
		db := openCoreAuthorityFixtureDB(t, fixture)
		defer db.Close()
		owner := pgx.Identifier{fixture.ownerRole}.Sanitize()
		session := pgx.Identifier{fixture.sessionRole}.Sanitize()
		if _, err := db.ExecContext(ctx, `CREATE ROLE `+owner+` NOLOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`); err != nil {
			t.Fatal(err)
		}
		if _, err := db.ExecContext(ctx, `GRANT `+owner+` TO `+session+` WITH ADMIN TRUE, INHERIT TRUE, SET FALSE`); err != nil {
			t.Fatal(err)
		}
		if _, err := prepareCoreMigrationAuthority(ctx, db); !errors.Is(err, ErrCoreAuthorityConflict) ||
			!strings.Contains(err.Error(), "ADMIN, INHERIT, and SET") {
			t.Fatalf("unsafe Core owner membership error = %v", err)
		}
	})

	t.Run("foreign Core object owner", func(t *testing.T) {
		fixture := newCoreAuthorityTestDatabase(t)
		ctx := context.Background()
		db := openCoreAuthorityFixtureDB(t, fixture)
		defer db.Close()
		foreignRole := fixture.ownerRole + "_foreign"
		fixture.addCleanupRole(foreignRole)
		foreign := pgx.Identifier{foreignRole}.Sanitize()
		if _, err := db.ExecContext(ctx, `CREATE ROLE `+foreign+` NOLOGIN`); err != nil {
			t.Fatal(err)
		}
		if _, err := db.ExecContext(ctx, `GRANT `+foreign+` TO `+pgx.Identifier{fixture.sessionRole}.Sanitize()); err != nil {
			t.Fatal(err)
		}
		if _, err := db.ExecContext(ctx, `CREATE TABLE public.foreign_core_owner_probe (id BIGINT)`); err != nil {
			t.Fatal(err)
		}
		if _, err := db.ExecContext(ctx, `ALTER TABLE public.foreign_core_owner_probe OWNER TO `+foreign); err != nil {
			t.Fatal(err)
		}
		if _, err := prepareCoreMigrationAuthority(ctx, db); !errors.Is(err, ErrCoreAuthorityConflict) ||
			!strings.Contains(err.Error(), "foreign_core_owner_probe") {
			t.Fatalf("foreign Core owner error = %v", err)
		}
		assertCoreAuthorityOwner(t, ctx, db, "relation", "public.foreign_core_owner_probe", foreignRole)
	})
}

type coreAuthorityTestDatabase struct {
	databaseName string
	databaseURL  string
	sessionRole  string
	ownerRole    string
	adminConfig  *pgx.ConnConfig
	cleanupRoles []string
	dropSession  bool
}

func newCoreAuthorityTestDatabase(t *testing.T) *coreAuthorityTestDatabase {
	return newCoreAuthorityTestDatabaseWithSession(t, false)
}

func newCoreAuthorityNonSuperTestDatabase(t *testing.T) *coreAuthorityTestDatabase {
	return newCoreAuthorityTestDatabaseWithSession(t, true)
}

func newCoreAuthorityTestDatabaseWithSession(t *testing.T, nonSuperSession bool) *coreAuthorityTestDatabase {
	t.Helper()
	databaseURL := strings.TrimSpace(os.Getenv("SFORUM_TEST_DATABASE_URL"))
	if databaseURL == "" {
		t.Skip("SFORUM_TEST_DATABASE_URL is required for Core authority integration tests")
	}
	baseConfig, err := pgx.ParseConfig(databaseURL)
	if err != nil {
		t.Fatal(err)
	}
	adminConfig := baseConfig.Copy()
	adminConfig.Database = "postgres"
	delete(adminConfig.RuntimeParams, "role")
	delete(adminConfig.RuntimeParams, "search_path")
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	admin, err := pgx.ConnectConfig(ctx, adminConfig)
	if err != nil {
		t.Fatalf("connect Core authority test administrator: %v", err)
	}
	defer admin.Close(context.Background())
	nonce := time.Now().UnixNano()
	fixture := &coreAuthorityTestDatabase{
		databaseName: fmt.Sprintf("sforum_p5_core_%d", nonce),
		adminConfig:  adminConfig,
	}
	if err := admin.QueryRow(ctx, `SELECT current_user`).Scan(&fixture.sessionRole); err != nil {
		t.Fatal(err)
	}
	fixture.ownerRole, err = coreauthority.OwnerRoleName(fixture.databaseName)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { fixture.cleanup(t) })
	const sessionPassword = "sforum_core_authority_test"
	if nonSuperSession {
		fixture.sessionRole = fmt.Sprintf("sforum_p5_core_login_%d", nonce)
		fixture.dropSession = true
		session := pgx.Identifier{fixture.sessionRole}.Sanitize()
		if _, err := admin.Exec(ctx, `CREATE ROLE `+session+` LOGIN INHERIT NOSUPERUSER NOCREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '`+sessionPassword+`'`); err != nil {
			t.Fatalf("create non-super Core migration login: %v", err)
		}
	}
	createDatabase := `CREATE DATABASE ` + pgx.Identifier{fixture.databaseName}.Sanitize()
	if nonSuperSession {
		createDatabase += ` OWNER ` + pgx.Identifier{fixture.sessionRole}.Sanitize()
	}
	if _, err := admin.Exec(ctx, createDatabase); err != nil {
		t.Fatalf("create isolated Core authority test database: %v", err)
	}
	targetURL, err := url.Parse(databaseURL)
	if err != nil || targetURL.Scheme == "" {
		t.Fatalf("SFORUM_TEST_DATABASE_URL must be a PostgreSQL URL: %v", err)
	}
	targetURL.Path = "/" + fixture.databaseName
	targetQuery := targetURL.Query()
	targetQuery.Del("role")
	targetQuery.Del("search_path")
	targetURL.RawQuery = targetQuery.Encode()
	if nonSuperSession {
		targetURL.User = url.UserPassword(fixture.sessionRole, sessionPassword)
	}
	fixture.databaseURL = targetURL.String()
	return fixture
}

func (f *coreAuthorityTestDatabase) addCleanupRole(roleName string) {
	f.cleanupRoles = append(f.cleanupRoles, roleName)
}

func (f *coreAuthorityTestDatabase) cleanup(t *testing.T) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	admin, err := pgx.ConnectConfig(ctx, f.adminConfig)
	if err != nil {
		t.Errorf("connect Core authority cleanup administrator: %v", err)
		return
	}
	defer admin.Close(context.Background())
	if _, err := admin.Exec(ctx, `DROP DATABASE IF EXISTS `+pgx.Identifier{f.databaseName}.Sanitize()+` WITH (FORCE)`); err != nil {
		t.Errorf("drop Core authority test database: %v", err)
		return
	}
	roles := append([]string{f.ownerRole}, f.cleanupRoles...)
	for _, roleName := range roles {
		role := pgx.Identifier{roleName}.Sanitize()
		session := pgx.Identifier{f.sessionRole}.Sanitize()
		_, _ = admin.Exec(ctx, `REVOKE `+role+` FROM `+session)
		if _, err := admin.Exec(ctx, `DROP ROLE IF EXISTS `+role); err != nil {
			t.Errorf("drop Core authority test role %s: %v", roleName, err)
		}
	}
	if f.dropSession {
		if _, err := admin.Exec(ctx, `DROP ROLE IF EXISTS `+pgx.Identifier{f.sessionRole}.Sanitize()); err != nil {
			t.Errorf("drop Core authority test login %s: %v", f.sessionRole, err)
		}
	}
}

func openCoreAuthorityFixtureDB(t *testing.T, fixture *coreAuthorityTestDatabase) *sql.DB {
	t.Helper()
	db, err := openMigrationSQLDatabase(fixture.databaseURL, "")
	if err != nil {
		t.Fatal(err)
	}
	return db
}

func assertCoreAuthorityMembership(t *testing.T, ctx context.Context, db *sql.DB, fixture *coreAuthorityTestDatabase) {
	t.Helper()
	var adminOption, inheritOption, setOption bool
	if err := db.QueryRowContext(ctx, `
		SELECT COALESCE(bool_or(memberships.admin_option), FALSE),
		       COALESCE(bool_or(memberships.inherit_option), FALSE),
		       COALESCE(bool_or(memberships.set_option), FALSE)
		FROM pg_auth_members AS memberships
		JOIN pg_roles AS granted ON granted.oid = memberships.roleid
		JOIN pg_roles AS member ON member.oid = memberships.member
		WHERE granted.rolname = $1 AND member.rolname = $2
	`, fixture.ownerRole, fixture.sessionRole).Scan(&adminOption, &inheritOption, &setOption); err != nil {
		t.Fatal(err)
	}
	if !adminOption || !inheritOption || !setOption {
		t.Fatalf("Core owner membership options = %t/%t/%t", adminOption, inheritOption, setOption)
	}
}

func assertCoreAuthorityCreatorMembership(
	t *testing.T,
	ctx context.Context,
	db *sql.DB,
	fixture *coreAuthorityTestDatabase,
) int {
	t.Helper()
	var rows, creatorAdminRows, selfGrantedAuthorityRows int
	var adminOption, inheritOption, setOption, canSet, hasPrivileges bool
	if err := db.QueryRowContext(ctx, `
		SELECT count(*),
		       count(*) FILTER (
		         WHERE memberships.admin_option
		           AND NOT memberships.inherit_option AND NOT memberships.set_option
		       ),
		       count(*) FILTER (
		         WHERE NOT memberships.admin_option
		           AND memberships.inherit_option AND memberships.set_option
		       ),
		       COALESCE(bool_or(memberships.admin_option), FALSE),
		       COALESCE(bool_or(memberships.inherit_option), FALSE),
		       COALESCE(bool_or(memberships.set_option), FALSE),
		       pg_has_role($2, $1, 'SET'), pg_has_role($2, $1, 'USAGE')
		FROM pg_auth_members AS memberships
		JOIN pg_roles AS granted ON granted.oid = memberships.roleid
		JOIN pg_roles AS member ON member.oid = memberships.member
		WHERE granted.rolname = $1 AND member.rolname = $2
	`, fixture.ownerRole, fixture.sessionRole).Scan(
		&rows, &creatorAdminRows, &selfGrantedAuthorityRows,
		&adminOption, &inheritOption, &setOption, &canSet, &hasPrivileges,
	); err != nil {
		t.Fatal(err)
	}
	if rows != 2 || creatorAdminRows != 1 || selfGrantedAuthorityRows != 1 ||
		!adminOption || !inheritOption || !setOption || !canSet || !hasPrivileges {
		t.Fatalf(
			"creator membership = rows:%d creatorAdmin:%d selfAuthority:%d admin:%t inherit:%t set:%t canSet:%t privileges:%t",
			rows, creatorAdminRows, selfGrantedAuthorityRows,
			adminOption, inheritOption, setOption, canSet, hasPrivileges,
		)
	}
	return rows
}

func assertCoreAuthorityDatabaseCreateRevoked(t *testing.T, ctx context.Context, db *sql.DB, ownerRole string) {
	t.Helper()
	var canCreate bool
	if err := db.QueryRowContext(ctx, `
		SELECT has_database_privilege($1, current_database(), 'CREATE')
	`, ownerRole).Scan(&canCreate); err != nil {
		t.Fatal(err)
	}
	if canCreate {
		t.Fatalf("Core owner %s retained database CREATE after Goose", ownerRole)
	}
}

func assertCoreAuthorityOwner(t *testing.T, ctx context.Context, db *sql.DB, objectKind string, qualifiedName string, expectedOwner string) {
	t.Helper()
	parts := strings.SplitN(qualifiedName, ".", 2)
	var query string
	var arguments []any
	switch objectKind {
	case "schema":
		query = `
			SELECT owners.rolname
			FROM pg_namespace AS namespaces
			JOIN pg_roles AS owners ON owners.oid = namespaces.nspowner
			WHERE namespaces.nspname = $1
		`
		arguments = []any{parts[0]}
	case "relation":
		query = `
			SELECT owners.rolname
			FROM pg_class AS classes
			JOIN pg_namespace AS namespaces ON namespaces.oid = classes.relnamespace
			JOIN pg_roles AS owners ON owners.oid = classes.relowner
			WHERE namespaces.nspname = $1 AND classes.relname = $2
		`
		arguments = []any{parts[0], parts[1]}
	case "routine":
		query = `
			SELECT owners.rolname
			FROM pg_proc AS routines
			JOIN pg_namespace AS namespaces ON namespaces.oid = routines.pronamespace
			JOIN pg_roles AS owners ON owners.oid = routines.proowner
			WHERE namespaces.nspname = $1 AND routines.proname = $2
		`
		arguments = []any{parts[0], parts[1]}
	case "type":
		query = `
			SELECT owners.rolname
			FROM pg_type AS types
			JOIN pg_namespace AS namespaces ON namespaces.oid = types.typnamespace
			JOIN pg_roles AS owners ON owners.oid = types.typowner
			WHERE namespaces.nspname = $1 AND types.typname = $2
		`
		arguments = []any{parts[0], parts[1]}
	case "extension":
		query = `
			SELECT owners.rolname
			FROM pg_extension AS extensions
			JOIN pg_roles AS owners ON owners.oid = extensions.extowner
			WHERE extensions.extname = $1
		`
		arguments = []any{parts[0]}
	default:
		t.Fatalf("unknown Core authority object kind %q", objectKind)
	}
	var actualOwner string
	if err := db.QueryRowContext(ctx, query, arguments...).Scan(&actualOwner); err != nil {
		t.Fatalf("inspect %s %s owner: %v", objectKind, qualifiedName, err)
	}
	if actualOwner != expectedOwner {
		t.Fatalf("%s %s owner = %s, want %s", objectKind, qualifiedName, actualOwner, expectedOwner)
	}
}
