package extensionscontroller

import "github.com/gofiber/fiber/v3"

func (h *Controller) RegisterRoutes(api fiber.Router) {
	// 前台：当前激活主题的非 secret 设置（主题 layer 消费）。
	api.Get("/site/active-theme/settings", h.publicActiveThemeSettings)

	api.Get("/admin/extensions", h.list)
	api.Get("/admin/extensions/navigation", h.navigation)
	api.Get("/admin/extensions/contribution-points", h.contributionPoints)
	api.Get("/admin/extensions/contributions", h.contributions)
	api.Get("/admin/extensions/route-providers/conflicts", h.routeProviderConflicts)
	api.Get("/admin/extensions/route-providers/selection", h.routeProviderCurrent)
	api.Get("/admin/extensions/route-providers/events", h.routeProviderEvents)
	api.Get("/admin/extensions/route-inspector", h.inspectRoute)
	api.Post("/admin/extensions/route-providers/selection", h.selectRouteProvider)
	api.Post("/admin/extensions/route-providers/selection/reset", h.resetRouteProvider)
	api.Post("/admin/extensions", h.install)
	api.Delete("/admin/extensions/:id", h.uninstall)
	api.Post("/admin/extensions/:id/enable", h.enable)
	api.Get("/admin/extensions/:id/trust", h.executableTrustStatus)
	api.Post("/admin/extensions/:id/trust/challenge", h.issueExecutableTrustChallenge)
	api.Delete("/admin/extensions/:id/trust", h.revokeExecutableTrust)
	api.Post("/admin/extensions/:id/disable", h.disable)
	api.Post("/admin/extensions/:id/upgrade", h.upgrade)
	api.Post("/admin/extensions/:id/rollback", h.rollback)
	api.Post("/admin/extensions/:id/verify", h.verify)
	api.Post("/admin/extensions/:id/activate", h.activate)
	api.Get("/admin/extensions/:id/events", h.events)
	api.Get("/admin/extensions/:id/lifecycle", h.lifecycleOperations)
	api.Get("/admin/extensions/:id/lifecycle/:operationID", h.lifecycleOperation)
	api.Post("/admin/extensions/:id/lifecycle/:operationID/recovery", h.recoverLifecycleOperation)
	api.Get("/admin/extensions/:id/migrations", h.listMigrations)
	api.Post("/admin/extensions/:id/migrations/apply", h.applyMigrations)
	api.Get("/admin/extensions/:id/settings", h.settings)
	api.Put("/admin/extensions/:id/settings", h.updateSettings)
	api.Post("/admin/extensions/:id/settings/reset", h.resetSettings)
	api.Post("/admin/extensions/:id/settings/actions/:actionId", h.executeSettingsAction)
	api.Get("/admin/extensions/:id/frontend", h.frontendStatus)
	api.Get("/admin/extensions/:id/frontend/assets/:digest/:asset", h.frontendAsset)
	api.Post("/admin/extensions/:id/frontend/confirmation", h.frontendConfirmation)
	api.Post("/admin/extensions/:id/frontend/trust", h.grantFrontendTrust)
	api.Delete("/admin/extensions/:id/frontend/trust", h.revokeFrontendTrust)
	api.Get("/admin/extensions/event-definitions", h.eventDefinitions)
	api.Get("/admin/extensions/event-deliveries", h.eventDeliveries)
	api.Get("/admin/extensions/provider-slots", h.inspectProviderSlots)

	api.All("/extensions/:extensionId/*", h.proxyExtensionRoute)
}
