package plugin

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	extensionmanifest "github.com/zhuchunshu/sforum/apps/api/app/Support/ExtensionManifest"
)

// GeneratedDocs 是一次目录文档生成的结果（内存）。
type GeneratedDocs struct {
	// Files 相对输出根的路径 → Markdown 正文。
	Files map[string]string
}

// 生成文件名（相对 catalogs 输出目录）。
const (
	DocIndex              = "README.md"
	DocEvents             = "events.md"
	DocCapabilities       = "capabilities.md"
	DocContributionPoints = "contribution-points.md"
	DocProviderSlots      = "provider-slots.md"
	DocSchedules          = "schedules.md"
	DocManifestV3         = "manifest-v3.md"
	// P7 冻结家族目录（与 hooks/services/providers/jobs/schedules/commands 对齐）。
	DocHooks         = "hooks.md"
	DocServices      = "services.md"
	DocJobs          = "jobs.md"
	DocCommands      = "commands.md"
	DocFamilies      = "families.md"
	DocNotifications = "notifications.md"
)

// genMarker 出现在每个生成文件顶部；人工编辑应改代码目录，再 re-generate。
const genMarker = "<!-- Generated by: sforum extension docs generate. Do not edit by hand. -->"

// GenerateCatalogDocs 从当前进程内的宿主目录生成 Markdown 文档集。
func GenerateCatalogDocs() GeneratedDocs {
	ensureNL := func(s string) string {
		if !strings.HasSuffix(s, "\n") {
			return s + "\n"
		}
		return s
	}
	files := map[string]string{
		DocIndex:              ensureNL(renderIndex()),
		DocEvents:             ensureNL(renderEvents()),
		DocCapabilities:       ensureNL(renderCapabilities()),
		DocContributionPoints: ensureNL(renderContributionPoints()),
		DocProviderSlots:      ensureNL(renderProviderSlots()),
		DocSchedules:          ensureNL(renderSchedules()),
		DocManifestV3:         ensureNL(renderManifestV3()),
		DocFamilies:           ensureNL(renderFamilies()),
		DocHooks:              ensureNL(renderHooks()),
		DocServices:           ensureNL(renderServices()),
		DocJobs:               ensureNL(renderJobs()),
		DocCommands:           ensureNL(renderCommands()),
		DocNotifications:      ensureNL(renderNotifications()),
	}
	return GeneratedDocs{Files: files}
}

// WriteCatalogDocs 将生成结果写入 dir（创建缺失目录，覆盖同名文件）。
func WriteCatalogDocs(dir string) error {
	docs := GenerateCatalogDocs()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// 稳定写入顺序，便于 diff 与测试。
	names := make([]string, 0, len(docs.Files))
	for name := range docs.Files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(dir, name)
		body := docs.Files[name]
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// CheckCatalogDocs 比较 dir 中已有文件与重新生成内容是否一致。
// 返回 (ok, 差异说明)。ok=true 表示无漂移。
func CheckCatalogDocs(dir string) (bool, string) {
	docs := GenerateCatalogDocs()
	var diffs []string
	for name, want := range docs.Files {
		path := filepath.Join(dir, name)
		got, err := os.ReadFile(path)
		if err != nil {
			diffs = append(diffs, fmt.Sprintf("missing %s: %v", name, err))
			continue
		}
		if string(got) != want {
			diffs = append(diffs, fmt.Sprintf("drift in %s", name))
		}
	}
	// 报告多余文件（同目录下非预期 .md 不强制失败，避免夹带手写说明时误伤）。
	if len(diffs) == 0 {
		return true, ""
	}
	sort.Strings(diffs)
	return false, strings.Join(diffs, "\n")
}

func renderHeader(title, intro string) string {
	var b strings.Builder
	b.WriteString(genMarker)
	b.WriteByte('\n')
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString(intro)
	b.WriteString("\n\n")
	b.WriteString("Source of truth: Go catalogs under `apps/api` ")
	b.WriteString("(`app/Support/Events`, `Capabilities`, `ExtensionManifest`, ")
	b.WriteString("`Jobs`, and provider slot constants). Regenerate with:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cd apps/api && go run ./cmd/sforum extension docs generate\n")
	b.WriteString("```\n\n")
	b.WriteString("Or verify CI drift:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cd apps/api && go run ./cmd/sforum extension docs generate --check\n")
	b.WriteString("```\n\n")
	return b.String()
}

func renderIndex() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Host platform catalogs",
		"Published host catalogs for plugin authors (Wave F4.2). "+
			"These pages are generated from the same data structures used by "+
			"`apps/api/sdk/plugin` and `sforum extension test`.",
	))
	b.WriteString("## Pages\n\n")
	b.WriteString("| Document | Contents |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| [events.md](./events.md) | Observe / filter / validate events plugins may declare |\n")
	b.WriteString("| [capabilities.md](./capabilities.md) | Host capability grants (risk tiers) |\n")
	b.WriteString("| [contribution-points.md](./contribution-points.md) | UI/admin contribution points |\n")
	b.WriteString("| [provider-slots.md](./provider-slots.md) | Provider slots plugins may fill |\n")
	b.WriteString("| [schedules.md](./schedules.md) | Core host schedules + plugin schedule declaration boundary |\n")
	b.WriteString("| [manifest-v3.md](./manifest-v3.md) | Manifest V3 root fields, include shards, and exact-artifact workflow |\n")
	b.WriteString("| [families.md](./families.md) | P7 frozen family matrix (hooks/services/providers/jobs/schedules/commands) |\n")
	b.WriteString("| [hooks.md](./hooks.md) | Versioned hooks: kinds, limits, host event names, InvokeHook |\n")
	b.WriteString("| [services.md](./services.md) | Plugin services + host-brokered discovery/invoke |\n")
	b.WriteString("| [jobs.md](./jobs.md) | Dynamic jobs: retry/concurrency limits + Enqueue/ExecuteJob |\n")
	b.WriteString("| [commands.md](./commands.md) | Plugin CLI commands + InvokeCommand boundary |\n")
	b.WriteString("| [notifications.md](./notifications.md) | Notification type declarations + bounded `notifications.emit@1` Host command |\n")
	b.WriteString("\n## Authoring\n\n")
	b.WriteString("- Hand-written guide: [../authoring-guide.md](../authoring-guide.md)\n")
	b.WriteString("- Go SDK: `github.com/zhuchunshu/sforum/apps/api/sdk/plugin` and `/v2`\n")
	b.WriteString("- Contract CLI: `sforum extension test [path]`\n")
	b.WriteString("- Scenario map: [../scenario-map.md](../scenario-map.md)\n")
	b.WriteString("- Reference plugins: built-in `sforum.smtp` (mail provider), `sforum.content-policy` (workflow filters), fixtures under `extensions/fixtures/plugins/`\n")
	return b.String()
}

func renderEvents() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Event catalog",
		"Plugins declare listeners only for events in this catalog. "+
			"**filter/validate** run synchronously on the write path — keep them cheap; "+
			"enqueue River jobs for heavy work. **observe** is asynchronous.",
	))
	b.WriteString("| Name | Kind | Timeout (ms) | Failure policy | Payload | Patch |\n")
	b.WriteString("| --- | --- | ---: | --- | --- | --- |\n")
	for _, e := range EventCatalog() {
		payload := joinOrDash(e.PayloadFields)
		patch := joinOrDash(e.PatchFields)
		b.WriteString(fmt.Sprintf("| `%s` | %s | %d | %s | %s | %s |\n",
			e.Name, e.Kind, e.TimeoutMS, e.FailurePolicy, payload, patch))
	}
	b.WriteString("\n### Descriptions\n\n")
	for _, e := range EventCatalog() {
		b.WriteString(fmt.Sprintf("#### `%s`\n\n", e.Name))
		b.WriteString(e.Description)
		b.WriteString("\n\n")
	}
	return b.String()
}

func renderCapabilities() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Capability catalog",
		"Capabilities constrain **plugin processes**, not end-user RBAC. "+
			"Declare `capabilities` in the manifest; the host may imply a minimal set "+
			"from backend/settings/jobs/`mail.provider`. First enable requires operator confirmation.",
	))
	b.WriteString("| Key | Risk | Label (EN) | Label (ZH) | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, c := range CapabilityCatalog() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			c.Key, c.Risk, escapePipes(c.LabelEN), escapePipes(c.LabelZH), escapePipes(c.Description)))
	}
	b.WriteString("\n### Risk tiers\n\n")
	b.WriteString("- **low** — routine host calls (Host API surface, own settings, permission checks)\n")
	b.WriteString("- **medium** — side effects operators should review (enqueue jobs, append audit)\n")
	b.WriteString("- **high** — sensitive data or network (user reads, outbound network)\n")
	return b.String()
}

func renderContributionPoints() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Contribution points",
		"Plugins may declare `contributions[]` only against host-owned points. "+
			"Payloads are validated JSON descriptors and **never executable JSON**.",
	))
	b.WriteString("| Point ID | Owner | Kind | Payload type | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, p := range ContributionPoints() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | `%s` | %s |\n",
			p.ID, p.Owner, p.Kind, p.PayloadType, escapePipes(p.Description)))
	}
	b.WriteString("\n### Kind meanings\n\n")
	b.WriteString("- **descriptor** — host renders UI from a typed payload (e.g. extension route action)\n")
	return b.String()
}

func renderProviderSlots() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Provider slots",
		"Plugins declare `providers[]` with a `slot` the host knows or a namespaced plugin-defined slot. "+
			"Selection, probe, fallback, and restore-defaults stay host-owned; vendor transport lives in the plugin.",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilyProviderSlots))
	b.WriteString("\n## Host-known slots\n\n")
	b.WriteString("| Slot | Notes |\n")
	b.WriteString("| --- | --- |\n")
	for _, slot := range ProviderSlotCatalog() {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", slot.Slot, escapePipes(slot.Description)))
	}
	limits := FrozenFamilyLimits()
	b.WriteString("\n## Versioned provider declaration\n\n")
	b.WriteString("| Field | Notes |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `id` / `contractVersion` | Versioned provider candidate identity; `contractVersion` is `id@positiveVersion` |\n")
	b.WriteString("| `slot` / `targetId` | Host-known slot or namespaced plugin slot contract |\n")
	b.WriteString("| `label` | Operator-facing selection label |\n")
	b.WriteString("| `handler` | Backend handler for `ProviderCall` |\n")
	b.WriteString("| `requestSchema` / `responseSchema` | Required for versioned V2 slots |\n")
	b.WriteString("| `fallback` | `next` or `closed` for versioned slots |\n")
	b.WriteString(fmt.Sprintf("| `timeoutMs` | Versioned slots: 1..%d |\n", limits.ProviderSlotMaximumTimeoutMS))
	b.WriteString("| `priority` | Host candidate ordering |\n")
	b.WriteString("\n## Wire RPCs\n\n")
	b.WriteString("| Direction | RPC | Role |\n")
	b.WriteString("| --- | --- | --- |\n")
	b.WriteString("| Host → plugin | `ProviderCall` | Selected versioned provider implementation |\n")
	b.WriteString("| Plugin → host | `ServiceDiscoveryService.InvokeProvider` | Consumer calls selected slot |\n")
	b.WriteString("\n**Versioned path only accepts `operation=invoke`.** ")
	b.WriteString("`pluginv2.VersionedProviderOperationInvoke` / Host `InvokeVersionedProvider` and ")
	b.WriteString("`provider_slot_execution` reject every other operation. ")
	b.WriteString("Legacy known-slot `probe`/`send` must override the generated `ProviderCall` RPC ")
	b.WriteString("or use provider-specific compatibility APIs — they must not be faked through ")
	b.WriteString("`pluginv2.ProviderRegistry` or `Host.InvokeProvider`.\n")
	b.WriteString("\nSDK: `pluginv2.ProviderRegistry` (invoke only) for versioned providers; ")
	b.WriteString("`Host.InvokeProvider` for consumers (rejects non-invoke).\n")
	return b.String()
}

func renderSchedules() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Schedule catalog",
		"Periodic work is host-owned. Core schedules below are built-in maintenance jobs. "+
			"Plugins may declare Manifest V3 `schedules[]` that reference their own `jobs[]` and a cron expression; "+
			"the host admits triggers and enqueues the exact versioned job. "+
			"**Plugins must not start private cron/goroutine loops.**",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilySchedules))
	b.WriteString("\n## Core host schedules\n\n")
	b.WriteString("| ID | Job kind | Queue | Interval | Owner | Default enabled | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, s := range CoreSchedules() {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s | %s | %t | %s |\n",
			s.ID, s.JobKind, s.Queue, formatDuration(s.Interval), s.Owner, s.Enabled, escapePipes(s.Description)))
	}
	b.WriteString("\n## Plugin schedule declaration (Manifest V3)\n\n")
	b.WriteString("| Field | Required | Notes |\n")
	b.WriteString("| --- | --- | --- |\n")
	b.WriteString("| `id` | yes | Namespaced versioned schedule id |\n")
	b.WriteString("| `contractVersion` | yes | Stable `id@positiveVersion` contract (never bare `1`) |\n")
	b.WriteString("| `jobId` | yes | Must reference a job id declared in the same package |\n")
	b.WriteString("| `cron` | yes | Host-validated cron expression |\n")
	b.WriteString("| `timezone` | no | IANA timezone when set |\n")
	b.WriteString("\nAuthoring: declare plugin schedules only via Manifest V3 `schedules[]`. ")
	b.WriteString("The public SDK exposes `CoreSchedules` (host core schedule catalog) and does **not** ")
	b.WriteString("provide `List`/`Trigger` helper methods. `Host.Schedules` is only the generated wire client field; ")
	b.WriteString("the host process does not register `ScheduleService` today, so those RPCs are not callable in practice.\n")
	return b.String()
}

func renderFamilies() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"P7 frozen extension families",
		"Six frozen platform families for plugin authors. "+
			"Each row is source-derived: manifest field, runtime registry/RPC, and an honest callable boundary. "+
			"Descriptors never invent a transport.",
	))
	b.WriteString("| Family | Manifest field | Callable transport | Catalog | SDK entry |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, surface := range FrozenFamilySurfaces() {
		callable := "no (authoring/catalog only)"
		if surface.CallableTransport {
			callable = "yes"
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | [%s](./%s) | %s |\n",
			surface.ID, surface.ManifestField, callable, surface.CatalogDoc, surface.CatalogDoc, escapePipes(surface.SDKAuthorEntry)))
	}
	b.WriteString("\n## Boundaries\n\n")
	for _, surface := range FrozenFamilySurfaces() {
		b.WriteString(fmt.Sprintf("### `%s`\n\n", surface.ID))
		b.WriteString(surface.Boundary)
		b.WriteString("\n\n**Source authorities**\n\n")
		for _, source := range surface.SourceAuthorities {
			b.WriteString(fmt.Sprintf("- %s\n", source))
		}
		if surface.HostToPluginRPC != "" {
			b.WriteString(fmt.Sprintf("\n- Host → plugin: `%s`\n", surface.HostToPluginRPC))
		}
		if surface.PluginToHostRPC != "" {
			b.WriteString(fmt.Sprintf("- Plugin → host: `%s`\n", surface.PluginToHostRPC))
		}
		b.WriteByte('\n')
	}
	limits := FrozenFamilyLimits()
	b.WriteString("## Frozen limits\n\n")
	b.WriteString("| Limit | Value |\n")
	b.WriteString("| --- | ---: |\n")
	b.WriteString(fmt.Sprintf("| Hook maximum timeout (ms) | %d |\n", limits.HookMaximumTimeoutMS))
	b.WriteString(fmt.Sprintf("| Provider slot maximum timeout (ms) | %d |\n", limits.ProviderSlotMaximumTimeoutMS))
	b.WriteString(fmt.Sprintf("| Plugin command maximum timeout (ms) | %d |\n", limits.PluginCommandMaximumTimeoutMS))
	b.WriteString(fmt.Sprintf("| Plugin job default concurrency | %d |\n", limits.PluginJobDefaultConcurrency))
	b.WriteString(fmt.Sprintf("| Plugin job maximum concurrency | %d |\n", limits.PluginJobMaximumConcurrency))
	b.WriteString(fmt.Sprintf("| Plugin job maximum attempts | %d |\n", limits.PluginJobMaximumAttempts))
	b.WriteString(fmt.Sprintf("| Plugin job maximum retry delay (s) | %d |\n", limits.PluginJobMaximumRetryDelaySec))
	b.WriteString(fmt.Sprintf("| Default sync event timeout (ms) | %d |\n", limits.DefaultSyncTimeoutMS))
	b.WriteString(fmt.Sprintf("| Default async event timeout (ms) | %d |\n", limits.DefaultAsyncTimeoutMS))
	return b.String()
}

func renderHooks() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Hook family catalog",
		"Versioned action/filter/observe hooks. Host event names below are the shared catalog plugins may target; "+
			"plugins may also declare namespaced hook contracts for cross-plugin composition through the host registry.",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilyHooks))
	b.WriteString("\n## Accepted enums\n\n")
	b.WriteString(fmt.Sprintf("- **kind**: %s\n", joinCodeList(HookKindValues())))
	b.WriteString(fmt.Sprintf("- **execution**: %s\n", joinCodeList(HookExecutionValues())))
	b.WriteString(fmt.Sprintf("- **failurePolicy**: %s\n", joinCodeList(HookFailurePolicyValues())))
	limits := FrozenFamilyLimits()
	b.WriteString(fmt.Sprintf("- **timeoutMs**: 1..%d (Protocol V2 unary deadline aligned)\n", limits.HookMaximumTimeoutMS))
	b.WriteString("\nRules: async + filter is rejected; async requires fail_open; mutableFields only on filter.\n")
	b.WriteString("\n## Host event names (shared catalog)\n\n")
	b.WriteString("| Name | Kind | Timeout (ms) | Failure policy | Payload | Patch |\n")
	b.WriteString("| --- | --- | ---: | --- | --- | --- |\n")
	for _, e := range EventCatalog() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %d | %s | %s | %s |\n",
			e.Name, e.Kind, e.TimeoutMS, e.FailurePolicy, joinOrDash(e.PayloadFields), joinOrDash(e.PatchFields)))
	}
	b.WriteString("\n## Manifest declaration fields\n\n")
	b.WriteString("| Field | Notes |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `id` / `contractVersion` | Versioned identity; `contractVersion` is `id@positiveVersion` (never bare `1`) |\n")
	b.WriteString("| `name` | Host event name or namespaced plugin contract name |\n")
	b.WriteString("| `kind` | `action` / `filter` / `observe` |\n")
	b.WriteString("| `targetId` | Optional target contract when listening to another declaration |\n")
	b.WriteString("| `handler` | Required for executable runtime registration |\n")
	b.WriteString("| `inputSchema` / `resultSchema` | Versioned schema refs (`id@version`). No separate `patchSchema` field. |\n")
	b.WriteString("| `priority` / `execution` / `failurePolicy` / `timeoutMs` / `mutableFields` | Composition and safety |\n")
	b.WriteString("\nFilter patches bind Host-derived schema `resultSchemaID+\".patch@\"+version` (not a Manifest field).\n")
	b.WriteString("Multiple declarations may target the same event `name`; Host dispatches by declaration id.\n")
	b.WriteString("Host delivers frozen `mutableFields`; SDK rejects request drift from the declaration.\n")
	b.WriteString("\nSDK: `pluginv2.HookRegistry` is for **executable** listeners only (requires handler + Execute).\n")
	b.WriteString("Passive catalog-only hook definitions must not be registered as runtime handlers.\n")
	b.WriteString("Schema binding is `id@version` identity only; no full JSON Schema value validation in the public SDK.\n")
	return b.String()
}

func renderServices() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Service family catalog",
		"Plugins publish versioned services for host-brokered discovery and typed invoke. "+
			"Consumers never dial peer plugins directly.",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilyServices))
	b.WriteString("\n## Accepted actions\n\n")
	b.WriteString(fmt.Sprintf("- %s\n", joinCodeList(ServiceActionValues())))
	b.WriteString("- Current validation allows composition action tokens, but non-`add` actions still require a `targetId`. Unsupported host composition chains fail closed.\n")
	b.WriteString("\n## Manifest declaration fields\n\n")
	b.WriteString("| Field | Notes |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `id` / `contractVersion` | Versioned service identity; `contractVersion` is `id@positiveVersion` |\n")
	b.WriteString("| `action` | Composition action (`add` for new providers) |\n")
	b.WriteString("| `targetId` | Required when action is not `add` |\n")
	b.WriteString("| `handler` | Backend operation entry |\n")
	b.WriteString("| `requestSchema` / `responseSchema` | Versioned schema refs |\n")
	b.WriteString("| `priority` | Host resolution order |\n")
	b.WriteString("\n## Wire RPCs\n\n")
	b.WriteString("| Direction | RPC | Role |\n")
	b.WriteString("| --- | --- | --- |\n")
	b.WriteString("| Host → plugin | `InvokeService` / `StreamService` | Dispatch to provider process |\n")
	b.WriteString("| Plugin → host | `ServiceDiscoveryService.List` | Enumerate authorized services |\n")
	b.WriteString("| Plugin → host | `ServiceDiscoveryService.Resolve` | Exact SemVer resolution |\n")
	b.WriteString("| Plugin → host | `ServiceDiscoveryService.Invoke` | Unary brokered call |\n")
	b.WriteString("| Plugin → host | `ServiceDiscoveryService.Stream` | Bidirectional brokered stream |\n")
	b.WriteString("\nSDK: `pluginv2.ServiceRegistry` for providers; `Host.ListServices` / `ResolveService` / `InvokeService` for consumers. ")
	b.WriteString("`ServiceDefinition.Version` must be strict SemVer, and its major must equal the Manifest service `contractVersion` `@N`; the Host rejects handshake drift.\n")
	return b.String()
}

func renderJobs() string {
	var b strings.Builder
	limits := FrozenFamilyLimits()
	b.WriteString(renderHeader(
		"Dynamic job family catalog",
		"Plugins declare versioned River jobs with frozen payload schema and bounded retry/concurrency. "+
			"Enqueue binds the live exact artifact; workers re-check the frozen contract before ExecuteJob.",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilyJobs))
	b.WriteString("\n## Retry policies\n\n")
	b.WriteString(fmt.Sprintf("- %s\n", joinCodeList(JobRetryPolicyValues())))
	b.WriteString("\n## Limits\n\n")
	b.WriteString("| Limit | Value |\n")
	b.WriteString("| --- | ---: |\n")
	b.WriteString(fmt.Sprintf("| maxAttempts | 1..%d |\n", limits.PluginJobMaximumAttempts))
	b.WriteString(fmt.Sprintf("| concurrencyLimit | 1..%d (default %d) |\n", limits.PluginJobMaximumConcurrency, limits.PluginJobDefaultConcurrency))
	b.WriteString(fmt.Sprintf("| retryDelaySeconds (bounded) | 1..%d |\n", limits.PluginJobMaximumRetryDelaySec))
	b.WriteString("| retryDelaySeconds (none/exponential) | must be 0 |\n")
	b.WriteString("\n## Manifest declaration fields\n\n")
	b.WriteString("| Field | Notes |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `id` / `contractVersion` | Versioned job contract; `contractVersion` is `id@positiveVersion` |\n")
	b.WriteString("| `name` | Stable job kind string used at enqueue / `JobRequest.job_kind` |\n")
	b.WriteString("| `handler` | Required executable handler for `ExecuteJob` |\n")
	b.WriteString("| `payloadSchema` | Versioned schema ref (`id@version`) |\n")
	b.WriteString("| `retryPolicy` / `maxAttempts` / `retryDelaySeconds` / `concurrencyLimit` | Frozen execution policy |\n")
	b.WriteString("\n`JobRequest.payload_version` is the **payload schema numeric version**, not `contractVersion`.\n")
	b.WriteString("\n## Wire RPCs\n\n")
	b.WriteString("| Direction | RPC | Status |\n")
	b.WriteString("| --- | --- | --- |\n")
	b.WriteString("| Plugin → host | `JobService.Enqueue` | Implemented (exact schema + admission) |\n")
	b.WriteString("| Plugin → host | `JobService.Cancel` | Wire only; returns `host.job_cancel_unavailable` |\n")
	b.WriteString("| Plugin → host | `JobService.Watch` | Wire only; returns `host.job_watch_unavailable` |\n")
	b.WriteString("| Host → plugin | `ExecuteJob` | Implemented (progress stream) |\n")
	b.WriteString("\nSDK: `pluginv2.JobRegistry` for execution dispatch; `Host.EnqueueJob` for versioned enqueue.\n")
	return b.String()
}

func renderCommands() string {
	var b strings.Builder
	limits := FrozenFamilyLimits()
	b.WriteString(renderHeader(
		"Plugin command family catalog",
		"Plugins declare namespaced CLI commands under the host `sforum` command registry. "+
			"The host invokes the exact runtime via `InvokeCommand` after trust, permission, and safe-mode checks.",
	))
	b.WriteString("## Callable transport boundary\n\n")
	b.WriteString(familyBoundaryParagraph(FamilyCommands))
	b.WriteString("\n## Limits\n\n")
	b.WriteString(fmt.Sprintf("- **timeoutMs**: 1..%d\n", limits.PluginCommandMaximumTimeoutMS))
	b.WriteString("- **permission**: when set, must also appear in package `permissions` or `permissionDefinitions`\n")
	b.WriteString("- **recoverySafe**: only recovery-safe commands remain available in safe mode\n")
	b.WriteString("\n## Manifest declaration fields\n\n")
	b.WriteString("| Field | Notes |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| `id` / `contractVersion` | Versioned command identity; `contractVersion` is `id@positiveVersion` |\n")
	b.WriteString("| `handler` | Required executable handler id |\n")
	b.WriteString("| `permission` | Optional operator permission gate |\n")
	b.WriteString("| `inputSchema` / `resultSchema` | Versioned schema refs |\n")
	b.WriteString("| `description` | CLI help text |\n")
	b.WriteString("| `recoverySafe` | Safe-mode eligibility |\n")
	b.WriteString("| `timeoutMs` | Host-enforced deadline (1..max) |\n")
	b.WriteString("\n## Wire RPCs\n\n")
	b.WriteString("| Direction | RPC | Role |\n")
	b.WriteString("| --- | --- | --- |\n")
	b.WriteString("| Host → plugin | `InvokeCommand` | CLI/host execution against exact artifact |\n")
	b.WriteString("| Plugin → host | — | **None.** Plugins cannot invoke peer plugin commands over Host API. |\n")
	b.WriteString("\nSDK: `pluginv2.CommandRegistry` validates executable declarations and dispatches `InvokeCommand`.\n")
	return b.String()
}

func familyBoundaryParagraph(familyID string) string {
	for _, surface := range FrozenFamilySurfaces() {
		if surface.ID == familyID {
			callable := "Authoring/catalog only — no honest callable transport from the plugin process."
			if surface.CallableTransport {
				callable = "Callable transport exists (see wire RPCs)."
			}
			return surface.Boundary + "\n\n" + callable + "\n"
		}
	}
	return ""
}

func joinCodeList(items []string) string {
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = "`" + item + "`"
	}
	return strings.Join(parts, ", ")
}

type manifestV3SchemaDocument struct {
	Required   []string                   `json:"required"`
	Properties map[string]json.RawMessage `json:"properties"`
	Defs       map[string]json.RawMessage `json:"$defs"`
}

type manifestV3SchemaDef struct {
	Properties map[string]json.RawMessage `json:"properties"`
}

func manifestV3SchemaFields() ([]string, map[string]bool, map[string]bool, map[string]string) {
	var schema manifestV3SchemaDocument
	if err := json.Unmarshal(extensionmanifest.ManifestV3JSONSchema(), &schema); err != nil {
		return nil, nil, nil, nil
	}
	required := make(map[string]bool, len(schema.Required))
	for _, name := range schema.Required {
		required[name] = true
	}
	includeShards := map[string]bool{}
	if raw, ok := schema.Defs["includes"]; ok {
		var includes manifestV3SchemaDef
		_ = json.Unmarshal(raw, &includes)
		for name := range includes.Properties {
			includeShards[name] = true
		}
	}
	fields := make([]string, 0, len(schema.Properties))
	shapes := make(map[string]string, len(schema.Properties))
	for name, raw := range schema.Properties {
		fields = append(fields, name)
		shapes[name] = manifestV3SchemaShape(raw, schema.Defs, 0)
	}
	// Settings accepts the legacy array and the versioned Settings Document;
	// its precise union is validated by the custom manifest decoder.
	shapes["settings"] = "array | object"
	sort.Strings(fields)
	return fields, required, includeShards, shapes
}

func manifestV3SchemaShape(raw json.RawMessage, defs map[string]json.RawMessage, depth int) string {
	if depth > 12 {
		return "recursive"
	}
	var property struct {
		Type                 json.RawMessage            `json:"type"`
		Ref                  string                     `json:"$ref"`
		OneOf                []json.RawMessage          `json:"oneOf"`
		Items                json.RawMessage            `json:"items"`
		Properties           map[string]json.RawMessage `json:"properties"`
		AdditionalProperties json.RawMessage            `json:"additionalProperties"`
		Const                json.RawMessage            `json:"const"`
		Enum                 []json.RawMessage          `json:"enum"`
	}
	if err := json.Unmarshal(raw, &property); err != nil {
		return "unknown"
	}
	if len(property.Type) > 0 {
		var scalar string
		if json.Unmarshal(property.Type, &scalar) == nil {
			return scalar
		}
		var union []string
		if json.Unmarshal(property.Type, &union) == nil {
			return strings.Join(union, " | ")
		}
	}
	if property.Ref != "" {
		const prefix = "#/$defs/"
		if strings.HasPrefix(property.Ref, prefix) {
			if definition, ok := defs[strings.TrimPrefix(property.Ref, prefix)]; ok {
				return manifestV3SchemaShape(definition, defs, depth+1)
			}
		}
		return "reference"
	}
	if len(property.OneOf) > 0 {
		parts := make([]string, 0, len(property.OneOf))
		seen := map[string]bool{}
		for _, option := range property.OneOf {
			shape := manifestV3SchemaShape(option, defs, depth+1)
			if shape != "" && !seen[shape] {
				seen[shape] = true
				parts = append(parts, shape)
			}
		}
		return strings.Join(parts, " | ")
	}
	if len(property.Items) > 0 {
		return "array"
	}
	if len(property.Properties) > 0 || len(property.AdditionalProperties) > 0 {
		return "object"
	}
	if len(property.Const) > 0 {
		return jsonValueShape(property.Const)
	}
	if len(property.Enum) > 0 {
		return jsonValueShape(property.Enum[0])
	}
	return "any"
}

func jsonValueShape(raw json.RawMessage) string {
	var value any
	if json.Unmarshal(raw, &value) != nil {
		return "unknown"
	}
	switch value.(type) {
	case string:
		return "string"
	case float64:
		return "integer"
	case bool:
		return "boolean"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	case nil:
		return "null"
	default:
		return "value"
	}
}

func renderManifestV3() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Manifest V3 schema catalog",
		"Manifest V3 is the explicit exact-artifact contract. This page is generated from the embedded Draft 2020-12 JSON Schema used by package preflight.",
	))
	fields, required, includeShards, shapes := manifestV3SchemaFields()
	b.WriteString("## Root fields\n\n")
	b.WriteString("| Field | Shape | Required at root | Include shard |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, field := range fields {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", field, escapePipes(shapes[field]), yesNo(required[field]), yesNo(includeShards[field])))
	}
	b.WriteString("\n## Declaration families\n\n")
	b.WriteString("- Runtime and registries: `backend`, `routes`, `guards`, `hooks`, `events`, `jobs`, `schedules`, `providers`, `services`, and `commands`.\n")
	b.WriteString("- Presentation and content: `components`, `templates`, `assets`, `content`, `adminSurfaces`, `navigation`, and `regions`.\n")
	b.WriteString("- Data and identity: `migrations`, `database`, `cache`, `queries`, `queryResultFilters`, `identity`, `permissionDefinitions`, and `media`.\n")
	b.WriteString("- Package composition: `dependencies`, `lifecycle`, `openapi`, `packageFiles`, and `includes`.\n")
	b.WriteString("\nThemes remain presentation-only. Plugin permission definitions use `assignmentPolicy: host`; install or enable code never grants roles. Permission `label` and `description` may be a default string or an extension-owned locale map; the Host resolves them for its permission catalog without copying extension text into Core locale files. Raw request guards, raw/kernel database authority, lifecycle execution, backend binaries, migrations, and L2 files enter exact-artifact trust review before first execution.\n")
	b.WriteString("\n## Exact-artifact workflow\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cd apps/api\n")
	b.WriteString("go run ./cmd/sforum extension digest --write <package-root>\n")
	b.WriteString("go run ./cmd/sforum extension validate <package-root>\n")
	b.WriteString("go run ./cmd/sforum extension test <package-root>\n")
	b.WriteString("```\n\n")
	b.WriteString("`digest --write` refreshes inline `packageFiles` SHA-256 values after local file changes and revalidates the package. Validation resolves all include shards without executing package code.\n")
	b.WriteString("\n## Compatibility\n\n")
	b.WriteString("- Omitted `manifestVersion` remains the V1 compatibility contract.\n")
	b.WriteString("- Explicit V2 remains accepted.\n")
	b.WriteString("- V3 packages must set `manifestVersion: 3`; V3-only declarations in V1/V2 packages fail instead of upgrading implicitly.\n")
	b.WriteString("- Future manifest versions fail closed until the host implements them.\n")
	b.WriteString("\nAuthoritative schemas: `apps/api/app/Support/ExtensionManifest/schemas/manifest-v3.schema.json` and `contracts/openapi/schemas/extensions-v3-*.yaml`. Reference fixtures: `apps/api/app/Support/ExtensionManifest/testdata/v3/`.\n")
	return b.String()
}

func renderNotifications() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Notification emission",
		"Manifest V3 plugins may declare inert, namespaced notification types and emit them only through the exact-runtime Host API v2 command.",
	))
	b.WriteString("## Frozen contracts\n\n")
	b.WriteString("| Contract | Value |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| Host command | `notifications.emit@1` |\n")
	b.WriteString("| Input schema | `sforum.notifications.emit.input@1` |\n")
	b.WriteString("| Result schema | `sforum.notifications.emit.result@1` |\n")
	b.WriteString("| Maximum recipients per request | 50 explicit active user ids |\n")
	b.WriteString("| Maximum structured payload | 16384 bytes |\n")
	b.WriteString("| Maximum payload schema | 65536 bytes |\n")
	b.WriteString("| Request rate | 60 committed requests per extension per rolling minute |\n")
	b.WriteString("\n`notificationTypes[].id` must be owned by the manifest namespace. `payloadSchema` resolves to one exact `packageFiles` schema id/version/digest. Types cannot set `required: true`; lifecycle code cannot assign preferences. Targets are declared Host route, extension route, entity, or none descriptors, never arbitrary URLs.\n")
	b.WriteString("\n## Authority\n\n")
	b.WriteString("The actorless command accepts only the broker-attested extension, artifact, trust grant, runtime epoch, and instance. The Host validates deadline, payload schema/version, active recipients, target equality, idempotency, count, rate, and effective recipient policy in the command transaction. Plugin-supplied actor/session/cookie evidence is rejected by the broker and input decoder. Bulk broadcast is not part of this contract.\n")
	b.WriteString("\nAccepted command audits contain only exact artifact identity and bounded impact counts. Rejection audits contain stable reasons and sizes/counts, never payload values or recipient ids. Historical rows keep versioned structured payloads; an inactive/uninstalled type renders through the Host fallback and cannot emit again.\n")
	b.WriteString("\nGo SDK: `(*pluginv2.Host).NotificationEmitRequest` and `(*pluginv2.Host).EmitNotification`. Reference fixture: `extensions/fixtures/plugins/sforum-notification-reference`.\n")
	return b.String()
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

// ProviderSlotInfo 是文档/SDK 用的槽位说明。
type ProviderSlotInfo struct {
	Slot        string `json:"slot"`
	Description string `json:"description"`
}

// ProviderSlotCatalog 返回带说明的 provider 槽位列表。
func ProviderSlotCatalog() []ProviderSlotInfo {
	// 与 KnownProviderSlots 顺序一致，补充作者可读说明。
	notes := map[string]string{
		"mail.provider":               "Outbound mail transport (e.g. built-in sforum.smtp). Implies net.outbound when selected as a plugin provider.",
		"search.provider":             "Full-text search engine transport. Core owns documents/ACL/jobs and the default in-process site engine (sforum.search-site, protected builtin). Optional engines (e.g. sforum.search-meilisearch) implement the same slot.",
		"attachment.storage.provider": "Object storage for attachments. Core keeps local (and existing OSS/COS/FTP/SFTP) drivers; plugins may implement the slot (E6, selection plugin:<extensionId>). See decision 2026-07-12-attachment-storage-plugin-provider.",
		"human_verification.provider": "Human verification / CAPTCHA-style checks (core Altcha default).",
		"auth.risk.provider":          "Login/registration risk signals (core default).",
		"editor.sanitizer.provider":   "Rich-text sanitizer policy (core default).",
	}
	slots := KnownProviderSlots()
	out := make([]ProviderSlotInfo, 0, len(slots))
	for _, slot := range slots {
		desc := notes[slot]
		if desc == "" {
			desc = "Host-owned provider slot."
		}
		out = append(out, ProviderSlotInfo{Slot: slot, Description: desc})
	}
	return out
}

func joinOrDash(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = "`" + item + "`"
	}
	return strings.Join(parts, ", ")
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func formatDuration(d time.Duration) string {
	if d == 0 {
		return "—"
	}
	if d%time.Hour == 0 {
		h := int(d / time.Hour)
		if h%24 == 0 {
			return fmt.Sprintf("%dd", h/24)
		}
		return fmt.Sprintf("%dh", h)
	}
	if d%time.Minute == 0 {
		return fmt.Sprintf("%dm", int(d/time.Minute))
	}
	return d.String()
}

// DefaultCatalogDocsDir 相对仓库根的默认输出目录。
const DefaultCatalogDocsDir = "docs/extensions/catalogs"

// ResolveCatalogDocsDir 在已知 repo root 下解析输出目录。
func ResolveCatalogDocsDir(repoRoot, override string) string {
	if strings.TrimSpace(override) != "" {
		if filepath.IsAbs(override) {
			return override
		}
		return filepath.Join(repoRoot, override)
	}
	return filepath.Join(repoRoot, DefaultCatalogDocsDir)
}

// DocFileNames 返回稳定排序的生成文件名列表。
func DocFileNames() []string {
	names := []string{
		DocIndex,
		DocEvents,
		DocCapabilities,
		DocContributionPoints,
		DocProviderSlots,
		DocSchedules,
		DocManifestV3,
		DocFamilies,
		DocHooks,
		DocServices,
		DocJobs,
		DocCommands,
	}
	sort.Strings(names)
	return names
}
