package plugin

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GeneratedDocs 是一次目录文档生成的结果（内存）。
type GeneratedDocs struct {
	// Files 相对输出根的路径 → Markdown 正文。
	Files map[string]string
}

// 生成文件名（相对 catalogs 输出目录）。
const (
	DocIndex              = "README.md"
	DocEvents             = "events.md"
	DocCapabilities       = "capabilities.md"
	DocContributionPoints = "contribution-points.md"
	DocProviderSlots      = "provider-slots.md"
	DocSchedules          = "schedules.md"
)

// genMarker 出现在每个生成文件顶部；人工编辑应改代码目录，再 re-generate。
const genMarker = "<!-- Generated by: sforum extension docs generate. Do not edit by hand. -->"

// GenerateCatalogDocs 从当前进程内的宿主目录生成 Markdown 文档集。
func GenerateCatalogDocs() GeneratedDocs {
	ensureNL := func(s string) string {
		if !strings.HasSuffix(s, "\n") {
			return s + "\n"
		}
		return s
	}
	files := map[string]string{
		DocIndex:              ensureNL(renderIndex()),
		DocEvents:             ensureNL(renderEvents()),
		DocCapabilities:       ensureNL(renderCapabilities()),
		DocContributionPoints: ensureNL(renderContributionPoints()),
		DocProviderSlots:      ensureNL(renderProviderSlots()),
		DocSchedules:          ensureNL(renderSchedules()),
	}
	return GeneratedDocs{Files: files}
}

// WriteCatalogDocs 将生成结果写入 dir（创建缺失目录，覆盖同名文件）。
func WriteCatalogDocs(dir string) error {
	docs := GenerateCatalogDocs()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// 稳定写入顺序，便于 diff 与测试。
	names := make([]string, 0, len(docs.Files))
	for name := range docs.Files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(dir, name)
		body := docs.Files[name]
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// CheckCatalogDocs 比较 dir 中已有文件与重新生成内容是否一致。
// 返回 (ok, 差异说明)。ok=true 表示无漂移。
func CheckCatalogDocs(dir string) (bool, string) {
	docs := GenerateCatalogDocs()
	var diffs []string
	for name, want := range docs.Files {
		path := filepath.Join(dir, name)
		got, err := os.ReadFile(path)
		if err != nil {
			diffs = append(diffs, fmt.Sprintf("missing %s: %v", name, err))
			continue
		}
		if string(got) != want {
			diffs = append(diffs, fmt.Sprintf("drift in %s", name))
		}
	}
	// 报告多余文件（同目录下非预期 .md 不强制失败，避免夹带手写说明时误伤）。
	if len(diffs) == 0 {
		return true, ""
	}
	sort.Strings(diffs)
	return false, strings.Join(diffs, "\n")
}

func renderHeader(title, intro string) string {
	var b strings.Builder
	b.WriteString(genMarker)
	b.WriteByte('\n')
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString(intro)
	b.WriteString("\n\n")
	b.WriteString("Source of truth: Go catalogs under `apps/api` ")
	b.WriteString("(`app/Support/Events`, `Capabilities`, `ExtensionManifest`, ")
	b.WriteString("`Jobs`, and provider slot constants). Regenerate with:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cd apps/api && go run ./cmd/sforum extension docs generate\n")
	b.WriteString("```\n\n")
	b.WriteString("Or verify CI drift:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cd apps/api && go run ./cmd/sforum extension docs generate --check\n")
	b.WriteString("```\n\n")
	return b.String()
}

func renderIndex() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Host platform catalogs",
		"Published host catalogs for plugin authors (Wave F4.2). "+
			"These pages are generated from the same data structures used by "+
			"`apps/api/sdk/plugin` and `sforum extension test`.",
	))
	b.WriteString("## Pages\n\n")
	b.WriteString("| Document | Contents |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString("| [events.md](./events.md) | Observe / filter / validate events plugins may declare |\n")
	b.WriteString("| [capabilities.md](./capabilities.md) | Host capability grants (risk tiers) |\n")
	b.WriteString("| [contribution-points.md](./contribution-points.md) | UI/admin contribution points |\n")
	b.WriteString("| [provider-slots.md](./provider-slots.md) | Provider slots plugins may fill |\n")
	b.WriteString("| [schedules.md](./schedules.md) | Core host schedules (plugins must not private-cron) |\n")
	b.WriteString("\n## Authoring\n\n")
	b.WriteString("- Hand-written guide: [../authoring-guide.md](../authoring-guide.md)\n")
	b.WriteString("- Go SDK: `github.com/zhuchunshu/sforum/apps/api/sdk/plugin`\n")
	b.WriteString("- Contract CLI: `sforum extension test [path]`\n")
	b.WriteString("- Scenario map: [../scenario-map.md](../scenario-map.md)\n")
	b.WriteString("- Reference plugins: built-in `sforum.smtp` (mail provider), `sforum.content-policy` (workflow filters), fixtures under `extensions/fixtures/plugins/`\n")
	return b.String()
}

func renderEvents() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Event catalog",
		"Plugins declare listeners only for events in this catalog. "+
			"**filter/validate** run synchronously on the write path — keep them cheap; "+
			"enqueue River jobs for heavy work. **observe** is asynchronous.",
	))
	b.WriteString("| Name | Kind | Timeout (ms) | Failure policy | Payload | Patch |\n")
	b.WriteString("| --- | --- | ---: | --- | --- | --- |\n")
	for _, e := range EventCatalog() {
		payload := joinOrDash(e.PayloadFields)
		patch := joinOrDash(e.PatchFields)
		b.WriteString(fmt.Sprintf("| `%s` | %s | %d | %s | %s | %s |\n",
			e.Name, e.Kind, e.TimeoutMS, e.FailurePolicy, payload, patch))
	}
	b.WriteString("\n### Descriptions\n\n")
	for _, e := range EventCatalog() {
		b.WriteString(fmt.Sprintf("#### `%s`\n\n", e.Name))
		b.WriteString(e.Description)
		b.WriteString("\n\n")
	}
	return b.String()
}

func renderCapabilities() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Capability catalog",
		"Capabilities constrain **plugin processes**, not end-user RBAC. "+
			"Declare `capabilities` in the manifest; the host may imply a minimal set "+
			"from backend/settings/jobs/`mail.provider`. First enable requires operator confirmation.",
	))
	b.WriteString("| Key | Risk | Label (EN) | Label (ZH) | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, c := range CapabilityCatalog() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			c.Key, c.Risk, escapePipes(c.LabelEN), escapePipes(c.LabelZH), escapePipes(c.Description)))
	}
	b.WriteString("\n### Risk tiers\n\n")
	b.WriteString("- **low** — routine host calls (Host API surface, own settings, permission checks)\n")
	b.WriteString("- **medium** — side effects operators should review (enqueue jobs, append audit)\n")
	b.WriteString("- **high** — sensitive data or network (user reads, outbound network)\n")
	return b.String()
}

func renderContributionPoints() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Contribution points",
		"Plugins may declare `contributions[]` only against host-owned points. "+
			"Payloads are validated JSON descriptors or trusted admin component refs — "+
			"**never executable JSON**. See also [trusted-admin-components.md](../trusted-admin-components.md).",
	))
	b.WriteString("| Point ID | Owner | Kind | Payload type | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, p := range ContributionPoints() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | `%s` | %s |\n",
			p.ID, p.Owner, p.Kind, p.PayloadType, escapePipes(p.Description)))
	}
	b.WriteString("\n### Kind meanings\n\n")
	b.WriteString("- **descriptor** — host renders UI from a typed payload (e.g. extension route action)\n")
	b.WriteString("- **component** — trusted client Vue component in a host slot (requires `frontend.admin`)\n")
	return b.String()
}

func renderProviderSlots() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Provider slots",
		"Plugins declare `providers[]` with a `slot` the host knows. "+
			"Selection and restore-defaults stay host-owned; vendor transport lives in the plugin.",
	))
	b.WriteString("| Slot | Notes |\n")
	b.WriteString("| --- | --- |\n")
	for _, slot := range ProviderSlotCatalog() {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", slot.Slot, escapePipes(slot.Description)))
	}
	return b.String()
}

func renderSchedules() string {
	var b strings.Builder
	b.WriteString(renderHeader(
		"Core schedule catalog",
		"Periodic maintenance jobs are registered only through the host schedule registry. "+
			"**Plugins must not start private cron/goroutine loops.** "+
			"Future plugin schedules will also declare through this registry (not in process).",
	))
	b.WriteString("| ID | Job kind | Queue | Interval | Owner | Default enabled | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, s := range CoreSchedules() {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s | %s | %t | %s |\n",
			s.ID, s.JobKind, s.Queue, formatDuration(s.Interval), s.Owner, s.Enabled, escapePipes(s.Description)))
	}
	return b.String()
}

// ProviderSlotInfo 是文档/SDK 用的槽位说明。
type ProviderSlotInfo struct {
	Slot        string `json:"slot"`
	Description string `json:"description"`
}

// ProviderSlotCatalog 返回带说明的 provider 槽位列表。
func ProviderSlotCatalog() []ProviderSlotInfo {
	// 与 KnownProviderSlots 顺序一致，补充作者可读说明。
	notes := map[string]string{
		"mail.provider":               "Outbound mail transport (e.g. built-in sforum.smtp). Implies net.outbound when selected as a plugin provider.",
		"search.provider":             "Full-text search backend. Core ships Meilisearch; slot reserved for future plugin drivers.",
		"attachment.storage.provider": "Object storage for attachments. Core owns local/OSS/COS/FTP/SFTP drivers in v1; slot name is stable for docs and future plugins.",
		"human_verification.provider": "Human verification / CAPTCHA-style checks (core Altcha default).",
		"auth.risk.provider":          "Login/registration risk signals (core default).",
		"editor.sanitizer.provider":   "Rich-text sanitizer policy (core default).",
	}
	slots := KnownProviderSlots()
	out := make([]ProviderSlotInfo, 0, len(slots))
	for _, slot := range slots {
		desc := notes[slot]
		if desc == "" {
			desc = "Host-owned provider slot."
		}
		out = append(out, ProviderSlotInfo{Slot: slot, Description: desc})
	}
	return out
}

func joinOrDash(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = "`" + item + "`"
	}
	return strings.Join(parts, ", ")
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func formatDuration(d time.Duration) string {
	if d == 0 {
		return "—"
	}
	if d%time.Hour == 0 {
		h := int(d / time.Hour)
		if h%24 == 0 {
			return fmt.Sprintf("%dd", h/24)
		}
		return fmt.Sprintf("%dh", h)
	}
	if d%time.Minute == 0 {
		return fmt.Sprintf("%dm", int(d/time.Minute))
	}
	return d.String()
}

// DefaultCatalogDocsDir 相对仓库根的默认输出目录。
const DefaultCatalogDocsDir = "docs/extensions/catalogs"

// ResolveCatalogDocsDir 在已知 repo root 下解析输出目录。
func ResolveCatalogDocsDir(repoRoot, override string) string {
	if strings.TrimSpace(override) != "" {
		if filepath.IsAbs(override) {
			return override
		}
		return filepath.Join(repoRoot, override)
	}
	return filepath.Join(repoRoot, DefaultCatalogDocsDir)
}

// DocFileNames 返回稳定排序的生成文件名列表。
func DocFileNames() []string {
	names := []string{
		DocIndex,
		DocEvents,
		DocCapabilities,
		DocContributionPoints,
		DocProviderSlots,
		DocSchedules,
	}
	sort.Strings(names)
	return names
}
