root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/sforum-worker ./cmd/worker"
bin = "./tmp/sforum-worker"
include_ext = ["go"]
exclude_dir = ["tmp", "internal/store/sqlc"]
delay = 1000
stop_on_error = true

[log]
time = true
